-- ═══════════════════════════════════════════════════════════════════════════════
-- FIX — completa qa_cido_catalogo (tipo='morfologia') em PRODUÇÃO com as 599
-- entradas que já existem no projeto "FlowLab - test" (eqz) e faltam em
-- produção (jqx). Nenhuma migration deste repositório insere essas linhas —
-- foram carregadas manualmente no teste, fora do controle de versão
-- (achado do usuário: "Candidato" de Registro de Câncer batia muito mais no
-- teste do que em produção pro mesmo período, porque os catálogos divergem:
-- prod tinha 167 códigos, teste tinha 743, com 599 exclusivos do teste e 23
-- exclusivos de produção — não é superset, união real).
--
-- Este script só ADICIONA os 599 que faltam em produção (ON CONFLICT DO
-- NOTHING — idempotente, seguro rodar de novo). NÃO remove nem sobrescreve
-- nada — os 23 códigos exclusivos de produção continuam intactos.
--
-- COMO RODAR: Dashboard de PRODUÇÃO (jqxeqmeikqclmmongclj) → SQL Editor →
-- colar este arquivo inteiro → Run.
-- ═══════════════════════════════════════════════════════════════════════════════

BEGIN;

INSERT INTO qa_cido_catalogo (codigo, tipo, descricao, ativo) VALUES
  ('80001', 'morfologia', 'Neoplasia de comportamento incerto se benigno ou maligno', true),
  ('80003', 'morfologia', 'Neoplasia maligna', true),
  ('80011', 'morfologia', 'Células tumorais, incerto se benignas ou malignas', true),
  ('80013', 'morfologia', 'Células tumorais malignas', true),
  ('80023', 'morfologia', 'Tumor maligno de células pequenas', true),
  ('80033', 'morfologia', 'Tumor maligno de células gigantes', true),
  ('80043', 'morfologia', 'Tumor maligno de células fusiformes', true),
  ('80053', 'morfologia', 'Tumor maligno de células claras', true),
  ('80113', 'morfologia', 'Epitelioma maligno', true),
  ('80143', 'morfologia', 'Carcinoma de grandes células, rabdóide', true),
  ('80223', 'morfologia', 'Carcinoma pleomórfico', true),
  ('80303', 'morfologia', 'Carcinoma de células gigantes e fusocelular', true),
  ('80313', 'morfologia', 'Carcinoma de células gigantes', true),
  ('80323', 'morfologia', 'Carcinoma fusocelular, SOE', true),
  ('80333', 'morfologia', 'Carcinoma pseudosarcomatoso', true),
  ('80343', 'morfologia', 'Carcinoma de células poligonais', true),
  ('80353', 'morfologia', 'Carcinoma de células gigantes semelhantes à osteoclasto', true),
  ('80401', 'morfologia', 'Tumorlet, SOE', true),
  ('80433', 'morfologia', 'Carcinoma de células pequenas, fusiformes', true),
  ('80443', 'morfologia', 'Carcinoma de células pequenas, intermediarias', true),
  ('80453', 'morfologia', 'Carcinoma de células pequenas e de células grandes', true),
  ('80463', 'morfologia', 'Carcinoma de células não pequenas', true),
  ('80522', 'morfologia', 'Carcinoma escamoso papilar, não invasivo', true),
  ('80523', 'morfologia', 'Carcinoma escamocelular papilar', true),
  ('80733', 'morfologia', 'Carcinoma escamoso de células pequenas, não ceratinizado', true),
  ('80743', 'morfologia', 'Carcinoma escamoso de células fusiformes', true),
  ('80762', 'morfologia', 'Carcinoma escamocelular in situ com invasão questionável do estroma', true),
  ('80772', 'morfologia', 'Neoplasia intra-epitelial escamosa, grau iii', true),
  ('80783', 'morfologia', 'Carcinoma escamoso com formação córnea', true),
  ('80802', 'morfologia', 'Eritroplasia de queyrat', true),
  ('80833', 'morfologia', 'Carcinoma escamoso, basaloide', true),
  ('80901', 'morfologia', 'Tumor basocelular', true),
  ('80923', 'morfologia', 'Carcinoma basocelular infiltrativo, SOE', true),
  ('80933', 'morfologia', 'Carcinoma basocelular, fibroepitelial', true),
  ('80973', 'morfologia', 'Carcinoma basocelular nodular', true),
  ('80983', 'morfologia', 'Carcinoma basal adenóide', true),
  ('81023', 'morfologia', 'Tricolemocarcinoma', true),
  ('81201', 'morfologia', 'Papiloma urotelial, SOE', true),
  ('81202', 'morfologia', 'Carcinoma de células transicionais in situ', true),
  ('81211', 'morfologia', 'Papiloma de células transicionais, tipo invertido, SOE', true),
  ('81213', 'morfologia', 'Carcinoma schneideriano', true),
  ('81223', 'morfologia', 'Carcinoma de células transicionais fusiformes', true),
  ('81243', 'morfologia', 'Carcinoma cloacogênico', true),
  ('81301', 'morfologia', 'Neoplasia de células transicionais, papilar, de baixo potencial de malignidade', true),
  ('81302', 'morfologia', 'Carcinoma de células de transição papilar, não invasivo', true),
  ('81313', 'morfologia', 'Carcinoma de células de transição, micropapilar', true),
  ('81401', 'morfologia', 'Adenoma atípico', true),
  ('81413', 'morfologia', 'Adenocarcinoma esquirroso', true),
  ('81423', 'morfologia', 'Linite plástica', true),
  ('81433', 'morfologia', 'Adenocarcinoma de propagação superficial', true),
  ('81482', 'morfologia', 'Neoplasia intra-epitelial glandular, grau iii', true),
  ('81501', 'morfologia', 'Tumor de células das ilhotas, SOE', true),
  ('81503', 'morfologia', 'Carcinoma de células das ilhotas', true),
  ('81513', 'morfologia', 'Insulinoma maligno', true),
  ('81521', 'morfologia', 'Glucagonoma, SOE', true),
  ('81523', 'morfologia', 'Glucagonoma maligno', true),
  ('81531', 'morfologia', 'Gastrinoma, SOE', true),
  ('81533', 'morfologia', 'Gastrinoma maligno', true),
  ('81543', 'morfologia', 'Adenocarcinoma exócrino misto, de células das ilhotas', true),
  ('81551', 'morfologia', 'Vipoma, SOE', true),
  ('81553', 'morfologia', 'Vipoma maligno', true),
  ('81561', 'morfologia', 'Somatostatinoma, SOE', true),
  ('81563', 'morfologia', 'Somatostatinoma maligno', true),
  ('81571', 'morfologia', 'Enteroglucagonoma, SOE', true),
  ('81573', 'morfologia', 'Enteroglucagonoma maligno', true),
  ('81623', 'morfologia', 'Tumor de klatskin', true),
  ('81713', 'morfologia', 'Carcinoma hepatocelular fibrolamelar', true),
  ('81723', 'morfologia', 'Carcinoma hepatocelular esquirroso', true),
  ('81733', 'morfologia', 'Carcinoma hepatocelular tipo fusocelular', true),
  ('81743', 'morfologia', 'Carcinoma hepatocelular de células claras', true),
  ('81753', 'morfologia', 'Carcinoma hepatocelular pleomórfico', true),
  ('81803', 'morfologia', 'Carcinoma hepatocelular e colangiocarcinoma combinados', true),
  ('81903', 'morfologia', 'Adenocarcinoma trabecular', true),
  ('82012', 'morfologia', 'Carcinoma in situ cribriforme', true),
  ('82013', 'morfologia', 'Carcinoma cribriforme, SOE', true),
  ('82102', 'morfologia', 'Adenocarcinoma in situ em pólipo adenomatoso', true),
  ('82143', 'morfologia', 'Carcinoma de células parietais', true),
  ('82153', 'morfologia', 'Adenocarcinoma de glândulas da região anal', true),
  ('82203', 'morfologia', 'Adenocarcinoma em polipose adenomatosa do cólon', true),
  ('82213', 'morfologia', 'Adenocarcinoma em pólipos adenomatosos múltiplos', true),
  ('82302', 'morfologia', 'Carcinoma ductal in situ, tipo solido', true),
  ('82303', 'morfologia', 'Carcinoma solido, SOE', true),
  ('82313', 'morfologia', 'Carcinoma simples', true),
  ('82413', 'morfologia', 'Carcinoide de células enterocromafínicas', true),
  ('82421', 'morfologia', 'Carcinoide de células semelhantes à enterocromafínicas, SOE', true),
  ('82423', 'morfologia', 'Tumor maligno de células semelhantes à enterocromafínicas', true),
  ('82433', 'morfologia', 'Carcinoide de células caliciformes', true),
  ('82443', 'morfologia', 'Carcinoide composto', true),
  ('82451', 'morfologia', 'Carcinoide tubular', true),
  ('82453', 'morfologia', 'Tumor adenocarcinoide', true),
  ('82463', 'morfologia', 'Carcinoma neuroendócrino, SOE', true),
  ('82481', 'morfologia', 'Apudoma', true),
  ('82493', 'morfologia', 'Tumor carcinoide atípico', true),
  ('82501', 'morfologia', 'Adenomatose pulmonar', true),
  ('82503', 'morfologia', 'Adenocarcinoma bronquiolo-alveolar, SOE', true),
  ('82513', 'morfologia', 'Adenocarcinoma alveolar', true),
  ('82533', 'morfologia', 'Carcinoma bronquiolo-alveolar mucinoso', true),
  ('82543', 'morfologia', 'Carcinoma bronquiolo-alveolar misto, mucinoso e não mucinoso', true),
  ('82553', 'morfologia', 'Adenocarcinoma com subtipos mistos', true),
  ('82612', 'morfologia', 'Adenocarcinoma in situ em adenoma viloso', true),
  ('82632', 'morfologia', 'Adenocarcinoma in situ em adenoma tubuloviloso', true),
  ('82633', 'morfologia', 'Adenocarcinoma em adenoma tubuloviloso', true),
  ('82723', 'morfologia', 'Carcinoma da glândula pituitária,soe', true),
  ('82803', 'morfologia', 'Carcinoma acidófilo', true),
  ('82813', 'morfologia', 'Carcinoma misto acidófilo-basófilo', true),
  ('83003', 'morfologia', 'Carcinoma basófilo', true),
  ('83111', 'morfologia', 'Tumor hipernefroide', true),
  ('83131', 'morfologia', 'Adenofibroma de células claras, malignidade limítrofe', true),
  ('83133', 'morfologia', 'Adenocarcinofibroma de células claras', true),
  ('83143', 'morfologia', 'Carcinoma rico em lipides', true),
  ('83153', 'morfologia', 'Carcinoma rico em glicogênio', true),
  ('83163', 'morfologia', 'Carcinoma de células renais, associado a cisto', true),
  ('83173', 'morfologia', 'Carcinoma de células renais, tipo cromófobo', true),
  ('83183', 'morfologia', 'Carcinoma de células renais sarcomatoide', true),
  ('83203', 'morfologia', 'Carcinoma de células granulares', true),
  ('83223', 'morfologia', 'Adenocarcinoma de células claras em água de rocha', true),
  ('83301', 'morfologia', 'Adenoma folicular atípico', true),
  ('83313', 'morfologia', 'Adenocarcinoma folicular bem diferenciado', true),
  ('83323', 'morfologia', 'Adenocarcinoma folicular, trabecular', true),
  ('83333', 'morfologia', 'Adenocarcinoma fetal', true),
  ('83353', 'morfologia', 'Carcinoma folicular pouco invasivo', true),
  ('83373', 'morfologia', 'Carcinoma insular', true),
  ('83403', 'morfologia', 'Carcinoma papilar, variante folicular', true),
  ('83413', 'morfologia', 'Microcarcinoma papilar', true),
  ('83423', 'morfologia', 'Carcinoma papilar, células oxifílicas', true),
  ('83433', 'morfologia', 'Carcinoma papilar, encapsulado', true),
  ('83443', 'morfologia', 'Carcinoma papilar, células colunares', true),
  ('83463', 'morfologia', 'Carcinoma misto medular folicular', true),
  ('83473', 'morfologia', 'Carcinoma misto medular papilar', true),
  ('83503', 'morfologia', 'Carcinoma esclerosante não-encapsulado', true),
  ('83601', 'morfologia', 'Adenomas endócrinos múltiplos', true),
  ('83801', 'morfologia', 'Adenoma endometrioide de malignidade limítrofe', true),
  ('83811', 'morfologia', 'Adenofibroma endometrioide de malignidade limítrofe', true),
  ('83813', 'morfologia', 'Adenofibroma endometrioide maligno', true),
  ('83833', 'morfologia', 'Adenocarcinoma endometrioide de células ciliares', true),
  ('83843', 'morfologia', 'Adenocarcinoma tipo endocervical', true),
  ('84001', 'morfologia', 'Tumor de glândula sudorípara, SOE', true),
  ('84013', 'morfologia', 'Adenocarcinoma apócrino', true),
  ('84023', 'morfologia', 'Hidradenoma nodular maligno', true),
  ('84033', 'morfologia', 'Espiradenoma écrino maligno', true),
  ('84073', 'morfologia', 'Carcinoma ductal de glândula sudorípara esclerosante', true),
  ('84081', 'morfologia', 'Adenoma papilar digitiforme agressivo', true),
  ('84083', 'morfologia', 'Adenocarcinoma papilar écrino', true),
  ('84133', 'morfologia', 'Adenocarcinoma écrino', true),
  ('84203', 'morfologia', 'Adenocarcinoma ceruminoso', true),
  ('84301', 'morfologia', 'Tumor mucoepidermoide', true),
  ('84403', 'morfologia', 'Cistadenocarcinoma, SOE', true),
  ('84421', 'morfologia', 'Cistadenoma seroso de malignidade limítrofe', true),
  ('84441', 'morfologia', 'Tumor cístico de células claras, malignidade limítrofe', true),
  ('84503', 'morfologia', 'Cistadenocarcinoma papilar, SOE', true),
  ('84511', 'morfologia', 'Cistadenoma papilar de malignidade limítrofe', true),
  ('84521', 'morfologia', 'Tumor pseudopapilar solido', true),
  ('84523', 'morfologia', 'Carcinoma pseudopapilar solido', true),
  ('84531', 'morfologia', 'Tumor papilar intraductal mucinoso com displasia moderada', true),
  ('84532', 'morfologia', 'Carcinoma papilar intraductal mucinoso, não invasivo', true),
  ('84533', 'morfologia', 'Carcinoma papilar intraductal mucinoso, invasivo', true),
  ('84621', 'morfologia', 'Tumor cístico papilar seroso de malignidade limítrofe', true),
  ('84631', 'morfologia', 'Tumor papilar de superfície serosa, malignidade limítrofe', true),
  ('84701', 'morfologia', 'Tumor cístico mucinoso com displasia moderada', true),
  ('84702', 'morfologia', 'Cistadenocarcinoma mucinoso, não invasivo', true),
  ('84713', 'morfologia', 'Cistadenocarcinoma mucinoso papilar', true),
  ('84721', 'morfologia', 'Tumor cístico mucinoso de malignidade limítrofe', true),
  ('84731', 'morfologia', 'Cistadenoma mucinoso papilar de malignidade limítrofe', true),
  ('84813', 'morfologia', 'Adenocarcinoma produtor de mucina', true),
  ('84823', 'morfologia', 'Adenocarcinoma mucinoso, tipo endocervical', true),
  ('85012', 'morfologia', 'Comedocarcinoma não infiltrante', true),
  ('85013', 'morfologia', 'Comedocarcinoma, SOE', true),
  ('85023', 'morfologia', 'Carcinoma secretor da mama', true),
  ('85032', 'morfologia', 'Adenocarcinoma papilar intraductal não infiltrante', true),
  ('85033', 'morfologia', 'Adenocarcinoma papilar intraductal com invasão', true),
  ('85043', 'morfologia', 'Carcinoma intracístico, SOE', true),
  ('85072', 'morfologia', 'Carcinoma intraductal micropapilar', true),
  ('85083', 'morfologia', 'Carcinoma cístico hiperssecretor', true),
  ('85123', 'morfologia', 'Carcinoma medular com estroma linfóide', true),
  ('85133', 'morfologia', 'Carcinoma medular atípico', true),
  ('85143', 'morfologia', 'Carcinoma ductal desmoplásico', true),
  ('85213', 'morfologia', 'Carcinoma ductular infiltrante', true),
  ('85222', 'morfologia', 'Carcinoma in situ intraductal e lobular', true),
  ('85223', 'morfologia', 'Carcinoma ductal infiltrante e lobular', true),
  ('85233', 'morfologia', 'Carcinoma ductal infiltrativo misto, com outros tipos de carcinoma', true),
  ('85243', 'morfologia', 'Carcinoma lobular infiltrante misto com outros tipos de carcinoma', true),
  ('85303', 'morfologia', 'Carcinoma inflamatório', true),
  ('85403', 'morfologia', 'Doença de paget, mamaria', true),
  ('85413', 'morfologia', 'Doença de paget e carcinoma ductal infiltrante da mama', true),
  ('85423', 'morfologia', 'Doença de paget extramamaria', true),
  ('85433', 'morfologia', 'Doença de paget e carcinoma intraductal da mama', true),
  ('85501', 'morfologia', 'Tumor de células acinosas', true),
  ('85513', 'morfologia', 'Cistadenocarcinoma de células acinosas', true),
  ('85703', 'morfologia', 'Adenocarcinoma com metaplasia escamosa', true),
  ('85713', 'morfologia', 'Adenocarcinoma com metaplasia cartilaginosa e óssea', true),
  ('85723', 'morfologia', 'Adenocarcinoma com metaplasia fusocelular', true),
  ('85733', 'morfologia', 'Adenocarcinoma com metaplasia apócrina', true),
  ('85743', 'morfologia', 'Adenocarcinoma com diferenciação neuroendócrina', true),
  ('85753', 'morfologia', 'Carcinoma metaplásico, SOE', true),
  ('85763', 'morfologia', 'Adenocarcinoma hepatoide', true),
  ('85801', 'morfologia', 'Timoma, SOE', true),
  ('85803', 'morfologia', 'Timoma maligno, SOE', true),
  ('85811', 'morfologia', 'Timoma, tipo a, SOE', true),
  ('85813', 'morfologia', 'Timoma, tipo a, maligno', true),
  ('85821', 'morfologia', 'Timoma, tipo ab, SOE', true),
  ('85823', 'morfologia', 'Timoma, tipo ab maligno', true),
  ('85831', 'morfologia', 'Timoma tipo b1, SOE', true),
  ('85833', 'morfologia', 'Timoma tipo b1 maligno', true),
  ('85841', 'morfologia', 'Timoma tipo b2, SOE', true),
  ('85843', 'morfologia', 'Timoma tipo b2 maligno', true),
  ('85851', 'morfologia', 'Timoma tipo b3, SOE', true),
  ('85853', 'morfologia', 'Timoma tipo b3, maligno', true),
  ('85863', 'morfologia', 'Carcinoma tímico, SOE', true),
  ('85883', 'morfologia', 'Tumor epitelial fusocelular semelhante a células tímicas', true),
  ('85893', 'morfologia', 'Carcinoma com elementos semelhantes ao timus', true),
  ('85901', 'morfologia', 'Tumor do estroma dos cordões sexuais, SOE', true),
  ('85911', 'morfologia', 'Tumor do estroma dos cordões sexuais com diferenciação incompleta', true),
  ('85921', 'morfologia', 'Tumor do estroma dos cordões sexuais, formas mistas', true),
  ('85931', 'morfologia', 'Tumor do estroma com poucos elementos dos cordões sexuais', true),
  ('86003', 'morfologia', 'Tecoma maligno', true),
  ('86201', 'morfologia', 'Tumor de células da granulosa, tipo adulto', true),
  ('86203', 'morfologia', 'Tumor maligno de células da granulosa', true),
  ('86211', 'morfologia', 'Tumor de células da teca-granulosa', true),
  ('86221', 'morfologia', 'Tumor juvenil de células da granulosa', true),
  ('86231', 'morfologia', 'Tumor dos cordões sexuais com túbulos anulares', true),
  ('86301', 'morfologia', 'Androblastoma, SOE', true),
  ('86303', 'morfologia', 'Androblastoma maligno', true),
  ('86311', 'morfologia', 'Tumor de células de sertoli-leydig com diferenciação intermediaria', true),
  ('86313', 'morfologia', 'Tumor de células de sertoli-leydig, pouco diferenciada', true),
  ('86321', 'morfologia', 'Ginandroblastoma', true),
  ('86331', 'morfologia', 'Tumor de células de sertoli-leydig, retiforme', true),
  ('86341', 'morfologia', 'Tumor de células de sertoli-leydig com diferenciação intermediaria e elementos heterologos', true),
  ('86343', 'morfologia', 'Tumor de células de sertoli-leydig pouco diferenciado com elementos heterologos', true),
  ('86401', 'morfologia', 'Tumor de células de sertoli, SOE', true),
  ('86403', 'morfologia', 'Carcinoma de células de sertoli', true),
  ('86421', 'morfologia', 'Tumor de células de sertoli, grandes células e calcificadas', true),
  ('86501', 'morfologia', 'Tumor de células de leydig, SOE', true),
  ('86503', 'morfologia', 'Tumor maligno de células de leydig', true),
  ('86703', 'morfologia', 'Tumor de células esteróide, maligno', true),
  ('86801', 'morfologia', 'Paraganglioma, SOE', true),
  ('86803', 'morfologia', 'Paraganglioma maligno', true),
  ('86811', 'morfologia', 'Paraganglioma simpático', true),
  ('86821', 'morfologia', 'Paraganglioma parassimpático', true),
  ('86901', 'morfologia', 'Tumor do glomo jugular, SOE', true),
  ('86911', 'morfologia', 'Tumor do corpo aórtico', true),
  ('86921', 'morfologia', 'Tumor do corpo carotídeo', true),
  ('86931', 'morfologia', 'Paraganglioma extra-supra-renal, SOE', true),
  ('86933', 'morfologia', 'Paraganglioma extra-supra-renal maligno', true),
  ('87003', 'morfologia', 'Feocromocitoma maligno', true),
  ('87103', 'morfologia', 'Glomangiossarcoma', true),
  ('87113', 'morfologia', 'Tumor glômico maligno', true),
  ('87202', 'morfologia', 'Melanoma in situ', true),
  ('87213', 'morfologia', 'Melanoma nodular', true),
  ('87223', 'morfologia', 'Melanoma de células baloniformes', true),
  ('87233', 'morfologia', 'Melanoma maligno em regressão', true),
  ('87281', 'morfologia', 'Melanocitoma meningeano', true),
  ('87283', 'morfologia', 'Melanomatose meningeana', true),
  ('87303', 'morfologia', 'Melanoma amelanótico', true),
  ('87403', 'morfologia', 'Melanoma maligno em nevo juncional', true),
  ('87412', 'morfologia', 'Melanose pré-cancerosa, SOE', true),
  ('87413', 'morfologia', 'Melanoma maligno em melanose pré-cancerosa', true),
  ('87422', 'morfologia', 'Lentigo maligno', true),
  ('87433', 'morfologia', 'Melanoma de propagação superficial', true),
  ('87443', 'morfologia', 'Melanoma lentiginoso maligno das extremidades', true),
  ('87463', 'morfologia', 'Melanoma lentiginoso de mucosa', true),
  ('87611', 'morfologia', 'Nevo pigmentado gigante, SOE', true),
  ('87613', 'morfologia', 'Melanoma maligno em nevo pigmentado gigante', true),
  ('87621', 'morfologia', 'Lesão proliferativa dérmica em nevos congênitos', true),
  ('87703', 'morfologia', 'Melanoma misto epitelioide e fusocelular', true),
  ('87713', 'morfologia', 'Melanoma de células epitelioides', true),
  ('87723', 'morfologia', 'Melanoma fusocelular, SOE', true),
  ('87733', 'morfologia', 'Melanoma fusocelular, tipo a', true),
  ('87743', 'morfologia', 'Melanoma fusocelular, tipo b', true),
  ('87803', 'morfologia', 'Nevo azul maligno', true),
  ('88013', 'morfologia', 'Sarcoma fusocelular', true),
  ('88033', 'morfologia', 'Sarcoma de células pequenas', true),
  ('88063', 'morfologia', 'Tumor desmoplásico de células pequenas e redondas', true),
  ('88101', 'morfologia', 'Fibroma celular', true),
  ('88123', 'morfologia', 'Fibrossarcoma periostal', true),
  ('88133', 'morfologia', 'Fibrossarcoma de fáscia', true),
  ('88143', 'morfologia', 'Fibrossarcoma infantil', true),
  ('88153', 'morfologia', 'Tumor maligno fibroso, solitário', true),
  ('88211', 'morfologia', 'Fibromatose agressiva', true),
  ('88221', 'morfologia', 'Fibromatose abdominal', true),
  ('88241', 'morfologia', 'Miofibromatose', true),
  ('88251', 'morfologia', 'Tumor miofibroblástico, SOE', true),
  ('88271', 'morfologia', 'Tumor miofibroblástico peribrônquico', true),
  ('88301', 'morfologia', 'Histiocitoma fibroso atípico', true),
  ('88303', 'morfologia', 'Histiocitoma fibroso maligno', true),
  ('88333', 'morfologia', 'Dermatofibrossarcoma protuberante pigmentado', true),
  ('88341', 'morfologia', 'Fibroblastoma de células gigantes', true),
  ('88351', 'morfologia', 'Tumor fibrohistiocítico plexiforme', true),
  ('88361', 'morfologia', 'Histiocitoma fibroso angiomatoide', true),
  ('88411', 'morfologia', 'Angiomixoma', true),
  ('88501', 'morfologia', 'Lipoma atípico', true),
  ('88533', 'morfologia', 'Lipossarcoma de células redondas', true),
  ('88543', 'morfologia', 'Lipossarcoma pleomórfico', true),
  ('88553', 'morfologia', 'Lipossarcoma misto', true),
  ('88573', 'morfologia', 'Lipossarcoma fibroblástico', true),
  ('88583', 'morfologia', 'Lipossarcoma dediferenciado', true),
  ('88901', 'morfologia', 'Leiomiomatose, SOE', true),
  ('88943', 'morfologia', 'Angiomiossarcoma', true),
  ('88953', 'morfologia', 'Miossarcoma', true),
  ('88963', 'morfologia', 'Leiomiossarcoma mixoide', true),
  ('88971', 'morfologia', 'Tumor de músculo liso de malignidade limítrofe', true),
  ('88981', 'morfologia', 'Leiomioma metastatizante', true),
  ('89013', 'morfologia', 'Rabdomiossarcoma pleomórfico tipo adulto', true),
  ('89023', 'morfologia', 'Rabdomiossarcoma tipo misto', true),
  ('89213', 'morfologia', 'Rabdomiossarcoma com diferenciação gangliônica', true),
  ('89343', 'morfologia', 'Carcinofibroma', true),
  ('89351', 'morfologia', 'Tumor estromal, SOE', true),
  ('89353', 'morfologia', 'Sarcoma estromal, SOE', true),
  ('89361', 'morfologia', 'Tumor estromal gastrointestinal, SOE', true),
  ('89363', 'morfologia', 'Sarcoma estromal gastrointestinal', true),
  ('89413', 'morfologia', 'Carcinoma em adenoma pleomórfico', true),
  ('89503', 'morfologia', 'Tumor misto mulleriano', true),
  ('89513', 'morfologia', 'Tumor misto mesodérmico', true),
  ('89591', 'morfologia', 'Nefroblastoma cístico parcialmente diferenciado', true),
  ('89593', 'morfologia', 'Nefroma maligno cistico', true),
  ('89601', 'morfologia', 'Nefroma meroblástico', true),
  ('89633', 'morfologia', 'Tumor rabdóide maligno', true),
  ('89643', 'morfologia', 'Sarcoma de células claras do rim', true),
  ('89703', 'morfologia', 'Hepatoblastoma', true),
  ('89713', 'morfologia', 'Pancreatoblastoma', true),
  ('89723', 'morfologia', 'Blastoma pulmonar', true),
  ('89733', 'morfologia', 'Blastoma pleuropulmonar', true),
  ('89741', 'morfologia', 'Sialoblastoma', true),
  ('89813', 'morfologia', 'Carcinossarcoma embrionário', true),
  ('89823', 'morfologia', 'Mioepitelioma maligno', true),
  ('89901', 'morfologia', 'Mesenquimoma, SOE', true),
  ('89903', 'morfologia', 'Mesenquimoma maligno', true),
  ('89913', 'morfologia', 'Sarcoma embrionário', true),
  ('90001', 'morfologia', 'Tumor de brenner de malignidade limítrofe', true),
  ('90003', 'morfologia', 'Tumor de brenner maligno', true),
  ('90141', 'morfologia', 'Adenofibroma seroso, malignidade limítrofe', true),
  ('90143', 'morfologia', 'Adenocarcinofibroma seroso', true),
  ('90151', 'morfologia', 'Adenofibroma mucinoso, malignidade limítrofe', true),
  ('90153', 'morfologia', 'Adenocarcinofibroma mucinoso', true),
  ('90201', 'morfologia', 'Tumor filodes malignidade limítrofe', true),
  ('90203', 'morfologia', 'Tumor filodes maligno', true),
  ('90413', 'morfologia', 'Sarcoma sinovial fusocelular', true),
  ('90423', 'morfologia', 'Sarcoma sinovial de células epitelioides', true),
  ('90443', 'morfologia', 'Sarcoma de células claras, SOE', true),
  ('90503', 'morfologia', 'Mesotelioma maligno', true),
  ('90513', 'morfologia', 'Mesotelioma fibroso maligno', true),
  ('90523', 'morfologia', 'Mesotelioma epitelioide maligno', true),
  ('90533', 'morfologia', 'Mesotelioma bifásico maligno', true),
  ('90551', 'morfologia', 'Mesotelioma cístico, SOE', true),
  ('90603', 'morfologia', 'Disgerminoma', true),
  ('90613', 'morfologia', 'Seminoma, SOE', true),
  ('90623', 'morfologia', 'Seminoma anaplásico', true),
  ('90633', 'morfologia', 'Seminoma espermatocítico', true),
  ('90642', 'morfologia', 'Neoplasia intratubular de células germinativas', true),
  ('90643', 'morfologia', 'Germinoma', true),
  ('90653', 'morfologia', 'Tumor de células germinativas não seminomatoso', true),
  ('90703', 'morfologia', 'Carcinoma embrionário, SOE', true),
  ('90713', 'morfologia', 'Tumor de saco vitelino', true),
  ('90723', 'morfologia', 'Poliembrioma', true),
  ('90731', 'morfologia', 'Gonadoblastoma', true),
  ('90801', 'morfologia', 'Teratoma, SOE', true),
  ('90803', 'morfologia', 'Teratoma maligno, SOE', true),
  ('90813', 'morfologia', 'Teratocarcinoma', true),
  ('90823', 'morfologia', 'Teratoma maligno indiferenciado', true),
  ('90833', 'morfologia', 'Teratoma maligno intermediário', true),
  ('90843', 'morfologia', 'Teratoma com transformação maligna', true),
  ('90853', 'morfologia', 'Tumor misto de células germinativas', true),
  ('90903', 'morfologia', 'Estroma ovariano maligno', true),
  ('90911', 'morfologia', 'Carcinoide do estroma', true),
  ('91001', 'morfologia', 'Mola hidatiforme invasiva', true),
  ('91013', 'morfologia', 'Coriocarcinoma combinado com outros elementos de células germinativas', true),
  ('91023', 'morfologia', 'Teratoma maligno trofoblástico', true),
  ('91041', 'morfologia', 'Tumor trofoblástico de localização placentária', true),
  ('91053', 'morfologia', 'Tumor trofoblástico epitelioide', true),
  ('91101', 'morfologia', 'Tumor mesonéfrico, SOE', true),
  ('91103', 'morfologia', 'Mesonefroma maligno', true),
  ('91243', 'morfologia', 'Sarcoma das células de kupffer', true),
  ('91301', 'morfologia', 'Hemangioendotelioma, SOE', true),
  ('91303', 'morfologia', 'Hemangioendotelioma maligno', true),
  ('91331', 'morfologia', 'Hemangioendotelioma epitelioide, SOE', true),
  ('91333', 'morfologia', 'Hemangioendotelioma epitelioide maligno', true),
  ('91351', 'morfologia', 'Angioendotelioma papilar endovascular', true),
  ('91361', 'morfologia', 'Hemangioendotelioma fusocelular', true),
  ('91501', 'morfologia', 'Hemangiopericitoma, SOE', true),
  ('91503', 'morfologia', 'Hemangiopericitoma maligno', true),
  ('91611', 'morfologia', 'Hemangioblastoma', true),
  ('91703', 'morfologia', 'Linfangiossarcoma', true),
  ('91741', 'morfologia', 'Linfangiomiomatose', true),
  ('91843', 'morfologia', 'Osteossarcoma em doença de paget do osso', true),
  ('91863', 'morfologia', 'Osteossarcoma central', true),
  ('91873', 'morfologia', 'Osteossarcoma intra-osseo, bem diferenciado', true),
  ('91923', 'morfologia', 'Osteossarcoma paraostal', true),
  ('91933', 'morfologia', 'Osteossarcoma periostal', true),
  ('91943', 'morfologia', 'Osteossarcoma de superfície de alto grau', true),
  ('91953', 'morfologia', 'Osteossarcoma intra-cortical', true),
  ('92001', 'morfologia', 'Osteoblastoma agressivo', true),
  ('92101', 'morfologia', 'Osteocondromatose, SOE', true),
  ('92201', 'morfologia', 'Condromatose, SOE', true),
  ('92213', 'morfologia', 'Condrossarcoma justacortical', true),
  ('92303', 'morfologia', 'Condroblastoma maligno', true),
  ('92313', 'morfologia', 'Condrossarcoma mixoide', true),
  ('92403', 'morfologia', 'Condrossarcoma mesenquimal', true),
  ('92423', 'morfologia', 'Condrossarcoma de células claras', true),
  ('92433', 'morfologia', 'Condrossarcoma dediferenciado', true),
  ('92501', 'morfologia', 'Tumor de células gigantes do osso, SOE', true),
  ('92503', 'morfologia', 'Tumor maligno de células gigantes do osso', true),
  ('92511', 'morfologia', 'Tumor de células gigantes de partes moles, SOE', true),
  ('92513', 'morfologia', 'Tumor maligno de células gigantes de partes moles', true),
  ('92523', 'morfologia', 'Tumor maligno de células gigantes tenossinovial', true),
  ('92613', 'morfologia', 'Adamantinoma de ossos longos', true),
  ('92701', 'morfologia', 'Tumor odontogênico, SOE', true),
  ('92703', 'morfologia', 'Tumor odontogênico maligno', true),
  ('92903', 'morfologia', 'Odontossarcoma ameloblástico', true),
  ('93103', 'morfologia', 'Ameloblastoma maligno', true),
  ('93303', 'morfologia', 'Fibrossarcoma ameloblástico', true),
  ('93411', 'morfologia', 'Tumor odontogênico de células claras', true),
  ('93423', 'morfologia', 'Carcinossarcoma odontogenico', true),
  ('93501', 'morfologia', 'Craniofaringioma', true),
  ('93511', 'morfologia', 'Craniofaringioma adamantinomatoso', true),
  ('93521', 'morfologia', 'Craniofaringioma papilar', true),
  ('93601', 'morfologia', 'Pinealoma', true),
  ('93611', 'morfologia', 'Pineocitoma', true),
  ('93623', 'morfologia', 'Pineoblastoma', true),
  ('93643', 'morfologia', 'Tumor neuroectodérmico periférico', true),
  ('93653', 'morfologia', 'Tumor de Askin', true),
  ('93703', 'morfologia', 'Cordoma, SOE', true),
  ('93713', 'morfologia', 'Cordoma condróide', true),
  ('93723', 'morfologia', 'Cordoma dediferenciado', true),
  ('93813', 'morfologia', 'Gliomatose cerebral', true),
  ('93823', 'morfologia', 'Glioma misto', true),
  ('93831', 'morfologia', 'Subependimoma', true),
  ('93841', 'morfologia', 'Astrocitoma subependimal de células gigantes', true),
  ('93901', 'morfologia', 'Papiloma atípico de plexo coróide', true),
  ('93903', 'morfologia', 'Carcinoma de plexo coróide', true),
  ('93913', 'morfologia', 'Ependimoma, SOE', true),
  ('93923', 'morfologia', 'Ependimoma anaplásico', true),
  ('93933', 'morfologia', 'Ependimoma papilar', true),
  ('93941', 'morfologia', 'Ependimoma mixopapilar', true),
  ('94003', 'morfologia', 'Astrocitoma, SOE', true),
  ('94013', 'morfologia', 'Astrocitoma anaplásico', true),
  ('94103', 'morfologia', 'Astrocitoma protoplasmático', true),
  ('94113', 'morfologia', 'Astrocitoma gemistocítico', true),
  ('94121', 'morfologia', 'Astrocitoma desmoplástico infantil', true),
  ('94203', 'morfologia', 'Astrocitoma fibrilar', true),
  ('94211', 'morfologia', 'Astrocitoma pilocítico', true),
  ('94233', 'morfologia', 'Espongioblastoma polar', true),
  ('94243', 'morfologia', 'Xantoastrocitoma pleomórfico', true),
  ('94303', 'morfologia', 'Astroblastoma', true),
  ('94403', 'morfologia', 'Glioblastoma, SOE', true),
  ('94413', 'morfologia', 'Glioblastoma de células gigantes', true),
  ('94421', 'morfologia', 'Gliofibroma', true),
  ('94423', 'morfologia', 'Gliossarcoma', true),
  ('94441', 'morfologia', 'Glioma cordóide', true),
  ('94503', 'morfologia', 'Oligodendroglioma, SOE', true),
  ('94513', 'morfologia', 'Oligodendroglioma anaplásico', true),
  ('94603', 'morfologia', 'Oligodendroblastoma', true),
  ('94703', 'morfologia', 'Meduloblastoma, SOE', true),
  ('94713', 'morfologia', 'Meduloblastoma desmoplásico nodular', true),
  ('94723', 'morfologia', 'Medulomioblastoma', true),
  ('94733', 'morfologia', 'Tumor neuroectodérmico primitivo, SOE', true),
  ('94743', 'morfologia', 'Meduloblastoma de células grandes', true),
  ('94803', 'morfologia', 'Sarcoma cerebelar, SOE', true),
  ('94903', 'morfologia', 'Ganglioneuroblastoma', true),
  ('95003', 'morfologia', 'Neuroblastoma, SOE', true),
  ('95013', 'morfologia', 'Meduloepitelioma, SOE', true),
  ('95023', 'morfologia', 'Meduloepitelioma teratoide', true),
  ('95033', 'morfologia', 'Neuroepitelioma, SOE', true),
  ('95043', 'morfologia', 'Espongioneuroblastoma', true),
  ('95051', 'morfologia', 'Ganglioglioma, SOE', true),
  ('95053', 'morfologia', 'Ganglioglioma anaplásico', true),
  ('95061', 'morfologia', 'Neurocitoma central', true),
  ('95083', 'morfologia', 'Tumor teratoide/rabdóide atípico', true),
  ('95103', 'morfologia', 'Retinoblastoma, SOE', true),
  ('95113', 'morfologia', 'Retinoblastoma diferenciado', true),
  ('95123', 'morfologia', 'Retinoblastoma indiferenciado', true),
  ('95133', 'morfologia', 'Retinoblastoma difuso', true),
  ('95141', 'morfologia', 'Retinoblastoma com regressão espontânea', true),
  ('95203', 'morfologia', 'Tumor neurogênico olfativo', true),
  ('95213', 'morfologia', 'Neurocitoma olfatório', true),
  ('95223', 'morfologia', 'Neuroblastoma olfativo', true),
  ('95233', 'morfologia', 'Neuroepitelioma olfativo', true),
  ('95301', 'morfologia', 'Meningiomatose, SOE', true),
  ('95303', 'morfologia', 'Meningioma maligno', true),
  ('95381', 'morfologia', 'Meningioma de células claras', true),
  ('95383', 'morfologia', 'Meningioma papilar', true),
  ('95391', 'morfologia', 'Meningioma atípico', true),
  ('95393', 'morfologia', 'Sarcomatose meningea', true),
  ('95401', 'morfologia', 'Neurofibromatose, SOE', true),
  ('95403', 'morfologia', 'Tumor maligno da bainha de nervo periférico', true),
  ('95601', 'morfologia', 'Neurinomatose', true),
  ('95603', 'morfologia', 'Neurilemoma maligno', true),
  ('95613', 'morfologia', 'Tumor maligno da bainha de nervo periférico com diferenciação rabdomioblástica', true),
  ('95713', 'morfologia', 'Perineuroma maligno', true),
  ('95803', 'morfologia', 'Tumor de células granulares, maligno', true),
  ('95813', 'morfologia', 'Sarcoma alveolar de partes moles', true),
  ('95913', 'morfologia', 'Linfoma maligno não-hodgkin, SOE', true),
  ('96543', 'morfologia', 'Linfoma de Hodgkin, depleção linfocítica, com fibrose difusa', true),
  ('96553', 'morfologia', 'Linfoma de Hodgkin, depleção linfocítica, reticular', true),
  ('96613', 'morfologia', 'Granuloma de Hodgkin', true),
  ('96623', 'morfologia', 'Sarcoma de Hodgkin', true),
  ('96643', 'morfologia', 'Linfoma de Hodgkin, esclerose nodular, fase celular', true),
  ('96653', 'morfologia', 'Linfoma de Hodgkin, esclerose nodular, grau i', true),
  ('96673', 'morfologia', 'Linfoma de Hodgkin, esclerose nodular, grau ii', true),
  ('96713', 'morfologia', 'Linfoma maligno linfoplasmocitario', true),
  ('96753', 'morfologia', 'Linfoma maligno, misto de células pequenas e grandes, difuso', true),
  ('96783', 'morfologia', 'Efusão por linfoma primário', true),
  ('96793', 'morfologia', 'Linfoma maligno do mediastino de células grandes b', true),
  ('96843', 'morfologia', 'Linfoma maligno de células grandes b, difuso, imunoblástico, SOE', true),
  ('96913', 'morfologia', 'Linfoma folicular grau ii', true),
  ('96953', 'morfologia', 'Linfoma folicular grau i', true),
  ('96983', 'morfologia', 'Linfoma folicular grau iii', true),
  ('97003', 'morfologia', 'Micose fungoide', true),
  ('97013', 'morfologia', 'Síndrome de sezary', true),
  ('97083', 'morfologia', 'Linfoma subcutâneo, tipo paniculite de células t', true),
  ('97093', 'morfologia', 'Linfoma cutâneo de células t, SOE', true),
  ('97163', 'morfologia', 'Linfoma hepatoesplênica, tipo gama-delta', true),
  ('97173', 'morfologia', 'Linfoma intestinal de células t', true),
  ('97183', 'morfologia', 'Lesão linfoproliferativa cutânea primaria de células t (cd30+)', true),
  ('97273', 'morfologia', 'Linfoma linfoblástico de células precursoras, SOE', true),
  ('97313', 'morfologia', 'Plasmocitoma, SOE', true),
  ('97323', 'morfologia', 'Mieloma múltiplo', true),
  ('97333', 'morfologia', 'Leucemia de plasmócitos', true),
  ('97343', 'morfologia', 'Plasmocitoma extramedular', true),
  ('97401', 'morfologia', 'Mastocitoma, SOE', true),
  ('97403', 'morfologia', 'Sarcoma de mastócitos', true),
  ('97413', 'morfologia', 'Mastocitose maligna', true),
  ('97423', 'morfologia', 'Leucemia de mastócitos', true),
  ('97503', 'morfologia', 'Histiocitose maligna', true),
  ('97511', 'morfologia', 'Histiocitose de células de Langherans, SOE', true),
  ('97521', 'morfologia', 'Histiocitose de células de Langherans unifocal', true),
  ('97531', 'morfologia', 'Histiocitose de células de Langherans, multifocal', true),
  ('97543', 'morfologia', 'Histiocitose de células de Langherans, disseminada', true),
  ('97553', 'morfologia', 'Sarcoma histiocítico', true),
  ('97563', 'morfologia', 'Sarcoma de células de Langherans', true),
  ('97573', 'morfologia', 'Sarcoma de células dendríticas digitiforme', true),
  ('97583', 'morfologia', 'Sarcoma de células dendríticas folicular', true),
  ('97603', 'morfologia', 'Doença imunoproliferativa, SOE', true),
  ('97613', 'morfologia', 'Macroglobulinemia de waldenstrom', true),
  ('97623', 'morfologia', 'Doença da cadeia pesada, SOE', true),
  ('97643', 'morfologia', 'Doença imunoproliferativa do intestino delgado', true),
  ('97651', 'morfologia', 'Gamopatia monoclonal de significado não determinado', true),
  ('97661', 'morfologia', 'Lesão imunoproliferativa angiocêntrica', true),
  ('97671', 'morfologia', 'Linfadenopatia angio-imunoblástica', true),
  ('97681', 'morfologia', 'Doença linfoproliferativa gama-t', true),
  ('97691', 'morfologia', 'Doença de deposito de imunoglobulina', true),
  ('98003', 'morfologia', 'Leucemia, SOE', true),
  ('98013', 'morfologia', 'Leucemia aguda, SOE', true),
  ('98053', 'morfologia', 'Leucemia aguda, bifenotípica', true),
  ('98203', 'morfologia', 'Leucemia linfóide, SOE', true),
  ('98263', 'morfologia', 'Leucemia de células de burkitt', true),
  ('98273', 'morfologia', 'Leucemia de células t do adulto / linfoma', true),
  ('98311', 'morfologia', 'Leucemia linfocítica de células grandes tipo t granulares', true),
  ('98323', 'morfologia', 'Leucemia prolinfocítica, SOE', true),
  ('98333', 'morfologia', 'Leucemia prolinfocítica, tipo células b', true),
  ('98343', 'morfologia', 'Leucemia prolinfocítica, tipo células t', true),
  ('98353', 'morfologia', 'Leucemia linfoblástica de células precursoras, SOE', true),
  ('98363', 'morfologia', 'Leucemia linfoblástica de células precursoras tipo b', true),
  ('98373', 'morfologia', 'Leucemia linfoblastica de celulas t precursoras', true),
  ('98403', 'morfologia', 'Leucemia mieloide aguda tipo m6', true),
  ('98633', 'morfologia', 'Leucemia mieloide crônica, SOE', true),
  ('98663', 'morfologia', 'Leucemia promielocítica aguda, t (15;17)', true),
  ('98673', 'morfologia', 'Leucemia mielomonocítica aguda', true),
  ('98703', 'morfologia', 'Leucemia basofílica aguda', true),
  ('98713', 'morfologia', 'Leucemia mieloide aguda com eosinófilos anormais na medula', true),
  ('98723', 'morfologia', 'Leucemia mieloide aguda, com diferenciação mínima', true),
  ('98733', 'morfologia', 'Leucemia mieloide aguda sem maturação', true),
  ('98743', 'morfologia', 'Leucemia mieloide aguda com maturação', true),
  ('98753', 'morfologia', 'Leucemia crônica mielogênica, bcr/abl positiva', true),
  ('98763', 'morfologia', 'Leucemia mieloide crônica atípica, bcr/abl negativa', true),
  ('98913', 'morfologia', 'Leucemia monocítica aguda', true),
  ('98953', 'morfologia', 'Leucemia mieloide aguda com displasia de multilinhagem', true),
  ('98963', 'morfologia', 'Leucemia mieloide aguda, t (8;21)', true),
  ('98973', 'morfologia', 'Leucemia mieloide aguda, com anormalidade em 11q23', true),
  ('99103', 'morfologia', 'Leucemia megacarioblástica aguda', true),
  ('99203', 'morfologia', 'Leucemia mieloide aguda relacionada ao tratamento, SOE', true),
  ('99313', 'morfologia', 'Panmielose aguda com mielofibrose', true),
  ('99453', 'morfologia', 'Leucemia mielomonocítica crônica, SOE', true),
  ('99463', 'morfologia', 'Leucemia mielomonocítica juvenil', true),
  ('99483', 'morfologia', 'Leucemia de células tipo nk agressiva', true),
  ('99503', 'morfologia', 'Policitemia vera', true),
  ('99603', 'morfologia', 'Doença mieloproliferativa crônica, SOE', true),
  ('99613', 'morfologia', 'Mieloesclerose com metaplasia mieloide', true),
  ('99623', 'morfologia', 'Trombocitemia essencial', true),
  ('99633', 'morfologia', 'Leucemia crônica neutrofílica', true),
  ('99643', 'morfologia', 'Síndrome hipereosinofílico', true),
  ('99701', 'morfologia', 'Alterações linfoproliferativas, SOE', true),
  ('99751', 'morfologia', 'Doença mieloproliferativa, SOE', true),
  ('99803', 'morfologia', 'Anemia refrataria', true),
  ('99823', 'morfologia', 'Anemia refrataria com sideroblastos', true),
  ('99833', 'morfologia', 'Anemia refrataria com excesso de blastos', true),
  ('99843', 'morfologia', 'Anemia refrataria com excesso de blastos, em transformação', true),
  ('99853', 'morfologia', 'Citopenia refrataria com displasia multilinhagem', true),
  ('99863', 'morfologia', 'Síndrome mielodisplásica com deleção 5q', true),
  ('99873', 'morfologia', 'Síndrome mielodisplásica relacionada à terapia, SOE', true),
  ('99893', 'morfologia', 'Síndrome mielodisplásica, SOE', true),
  ('99901', 'morfologia', 'Clinicamente tumor, SOE', true),
  ('99903', 'morfologia', 'Clinicamente tumor maligno, SOE', true),
  ('M8000/3', 'morfologia', 'Neoplasia maligna, SOE', true),
  ('M8010/3', 'morfologia', 'Carcinoma, SOE', true),
  ('M8070/3', 'morfologia', 'Carcinoma de células escamosas, SOE', true),
  ('M8090/3', 'morfologia', 'Carcinoma basocelular, SOE', true),
  ('M8140/3', 'morfologia', 'Adenocarcinoma, SOE', true),
  ('M8500/3', 'morfologia', 'Carcinoma ductal infiltrante, SOE', true),
  ('M8520/3', 'morfologia', 'Carcinoma lobular infiltrante', true),
  ('M8720/3', 'morfologia', 'Melanoma maligno, SOE', true)
ON CONFLICT (codigo) DO NOTHING;

COMMIT;

-- Conferência (rodar depois do COMMIT):
-- select tipo, count(*) from qa_cido_catalogo group by tipo;
-- -- esperado: morfologia = 766 (167 + 599), topografia inalterado.
