export {
  VALID_TRANSITIONS,
  TRANSITION_ACTIONS,
  canTransition,
  getValidNextStatuses,
  isTerminalStatus,
  canEditQuotation,
  canModifyItems,
  canModifySuppliers,
  canSelectWinner,
  canCancel,
  validateTransition,
  getStatusProgress,
  getStatusStep,
} from './stateMachine';
