-- ═══════════════════════════════════════════════════════════════════════════════
-- Fase 7 — Etapa A (frente 1): Catálogo de exames (ac_exames)
--
-- Catálogo dos exames que o funcionário seleciona no check-in (lê o pedido e marca
-- os exames do paciente). Importado da planilha "Comparativo de Valores A C"
-- (Google Sheets, aba Orçamento Particular). Só os campos operacionais: nome,
-- mnemônico, código TUSS e material; preço/convênio ficam fora.
--
-- `is_cultura` marca os exames microbiológicos de cultura (detecção pelo nome:
-- contém "cultura") — são eles que geram uma linha de acompanhamento em ac_culturas.
-- Editável à mão depois (marcar/desmarcar exceções).
--
-- Seed idempotente: só popula se a tabela estiver vazia (preserva edições). 529 exames, 8 culturas.
-- RLS permissiva por authenticated (gate real = frontend), consistente com Fase 6/7C.
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION ac_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── 1. ac_exames ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ac_exames (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome        text NOT NULL,
  mnemonico   text,
  codigo_tuss text,
  material    text,          -- tipo de amostra: S (soro), U (urina), F (fezes)…
  is_cultura  boolean NOT NULL DEFAULT false,
  ativo       boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ac_exames_cultura ON ac_exames(is_cultura) WHERE is_cultura;
CREATE INDEX IF NOT EXISTS idx_ac_exames_ativo   ON ac_exames(ativo) WHERE ativo;

DROP TRIGGER IF EXISTS trg_ac_exames_updated_at ON ac_exames;
CREATE TRIGGER trg_ac_exames_updated_at
  BEFORE UPDATE ON ac_exames
  FOR EACH ROW EXECUTE FUNCTION ac_set_updated_at();

-- ─── 2. RLS ──────────────────────────────────────────────────────────────────
ALTER TABLE ac_exames ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ac_exames_select_all"  ON ac_exames;
DROP POLICY IF EXISTS "ac_exames_insert_auth" ON ac_exames;
DROP POLICY IF EXISTS "ac_exames_update_auth" ON ac_exames;
DROP POLICY IF EXISTS "ac_exames_delete_auth" ON ac_exames;
CREATE POLICY "ac_exames_select_all"  ON ac_exames FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY "ac_exames_insert_auth" ON ac_exames FOR INSERT TO authenticated WITH CHECK (TRUE);
CREATE POLICY "ac_exames_update_auth" ON ac_exames FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "ac_exames_delete_auth" ON ac_exames FOR DELETE TO authenticated USING (TRUE);

-- ─── 3. Seed (idempotente: só se vazia) ──────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM ac_exames) THEN
    INSERT INTO ac_exames (nome, mnemonico, codigo_tuss, material, is_cultura) VALUES
      ('Alfa-fetoproteína (pesquisa e/ou dosagem)', 'A.FETO', '40316068', 'S', false),
      ('1,25-DIHIDROXIVITAMINA D', 'VIT-D3', '40305015', 'S', false),
      ('17 ALFA HIDROXIPROGESTERONA', '17-PG', '40316017', 'S', false),
      ('17-HIDROXIPREGNENOLONA - PESQUISA E/OU DOSAGEM', NULL, '40305090', 'S', false),
      ('25-HIDROXIVITAMINA D - S', '25-VD3', '40302830', 'S', false),
      ('5 NUCLEOTIDASE', 'NUC', '40301028', 'S', false),
      ('ÁCIDO 5 HIDRÓXI INDOL ACÉTICO, DOSAGEM NA URINA', NULL, '40305112', NULL, false),
      ('ÁCIDO CÍTRICO - PESQUISA E/OU DOSAGEM NA URINA', NULL, '40311015', 'UR', false),
      ('ÁCIDO CÍTRICO- PESQUISA/DOSAGEM NO SANGUE', NULL, '40322270', 'S', false),
      ('ÁCIDO FÓLICO', 'FOLICO', '40301087', 'S', false),
      ('ÁCIDO HIPÚRICO', 'A-HIP', '40313042', 'U', false),
      ('ÁCIDO LÁTICO - LACTATO - S', 'AL', '40301109', 'S', false),
      ('ÁCIDO METIL MALÔNICO - PESQUISA E/OU DOSAGEM', NULL, '40313301', NULL, false),
      ('ÁCIDO METIL-HIPÚRICO', 'A-MH', '40313069', 'U', false),
      ('ÁCIDO OXÁLICO - OXALATO - U', 'AC-OXA', '40301125', 'U', false),
      ('ÁCIDO TRANS, TRANS-MUCÔNICO', 'ATTM', NULL, 'U', false),
      ('ÁCIDO ÚRICO', 'ACU', '40301150', 'S', false),
      ('ÁCIDO ÚRICO - U', 'ACU', '40301180', 'U', false),
      ('ÁCIDO ÚRICO - U-24', 'ACU-24', '40301180', 'U-24', false),
      ('ÁCIDO VALPROICO - VALPROATO DE SÓDIO', 'VAL', '40301168', 'S', false),
      ('ACTH', 'ACTH', '40316041', 'S', false),
      ('ALBUMINA - PESQUISA E/OU DOSAGEM', NULL, '40301222', NULL, false),
      ('ALDOSTERONA - S', 'ALDO-S', '40316050', 'S', false),
      ('ALFA 1 ANTI TRIPSINA', 'A1A', '40301249', 'S', false),
      ('ALFA 1 GLICOPROTEÍNA ÁCIDA', 'A.GLIC', '40301257', 'S', false),
      ('ALUMÍNIO - S', 'ALUM', '40301273', 'S', false),
      ('ALUMÍNIO - U', 'ALUM', '40313190', 'U', false),
      ('AMILASE - S', 'AMI', '40301281', 'S', false),
      ('ANDROSTENEDIONA', 'AND', '40316076', 'S', false),
      ('ANTI - CITOPLASMA DE NEUTRÓFILOS', NULL, '40306402', NULL, false),
      ('ANTI - LKM 1', NULL, '40306097', NULL, false),
      ('Anti HBS - Hepatite B', 'HBS', '40306992', 'S', false),
      ('ANTI-DNA - PESQUISA E/OU DOSAGEM', 'AADNA', '40306062', 'S', false),
      ('ANTI-GAD', NULL, '40305341', 'S', false),
      ('ANTI-ILHOTA', NULL, '40306208', 'S', false),
      ('ANTI-INSULINA', NULL, '40316092', 'S', false),
      ('ANTIBIOGRAMA AUTOMATIZADO', NULL, '40310426', NULL, false),
      ('ANTICOAGULANTE LÚPICO - S', 'LUP-VV', '40304019', 'S', false),
      ('ANTICORPOS ANTI CHIKUNGUNYA IGG E IGM', 'CHIKU', '40324176', 'S', false),
      ('ANTICORPOS ANTI DNA - CADEIA SIMPLES', 'DNA-SS', NULL, 'S', false),
      ('ANTICORPOS ANTI ENDOMÍSIO IGM', 'END-M', '40306259', 'S', false),
      ('ANTICORPOS ANTI HERPES VÍRUS 8 IGG', 'HV8', NULL, 'S', false),
      ('ANTICORPOS ANTI HERPES VÍRUS 8 IGM', 'HV8-M', NULL, 'S', false),
      ('ANTICORPOS ANTI TRANSGLUTAMINASE TECIDUAL IGG', 'TRAN-G', '40308553', 'S', false),
      ('ANTICORPOS ANTI TRANSGLUTAMINASE TECIDUAL IGG', NULL, '40308561', 'S', false),
      ('Antígeno do Fator de Von Willebrand', NULL, '40304191', NULL, false),
      ('ANTÍGENO HLA-B-27, PESQUISA - PCR', 'HLAPCR', '40306887', 'S', false),
      ('ANTIGLIADINA (GLÚTEN) - IGA - PESQUISA E/OU DOSAGEM', NULL, '40306305', 'S', false),
      ('ANTIGLIADINA (GLÚTEN) - IGG - PESQUISA E/OU DOSAGEM', NULL, '40306313', 'S', false),
      ('ANTITROMBINA III', NULL, '40304060', NULL, false),
      ('APOLIPOPROTEÍNA A-1', 'APOA', '40301354', 'S', false),
      ('APOLIPOPROTEÍNA B', 'APOB', '40301362', 'S', false),
      ('AQUAPORINA 4- ANTICORPOS IgG', NULL, '40316661', 'S', false),
      ('ASLO - PESQUISA E/OU DOSAGEM, ANTIESTREPTOLISINA', NULL, '40306445', NULL, false),
      ('ATIVIDADE PLASMÁTICA DA RENINA', 'RENI', '40316432', 'S', false),
      ('AVALIÇÃO DO RISCO FETAL - TESTE TRIPLO', NULL, '40502155', 'S', false),
      ('BAAR - BACILOSCOPIA', 'BAAR', NULL, 'DIV', false),
      ('Bacterioscopia - Coloração de Gram - CONVENCIONAL', NULL, NULL, NULL, false),
      ('BCR::ABL1 quantitativo P190', NULL, '40503542', NULL, false),
      ('BETA HCG QUANTITATIVO', 'HCGDIL', '40305767', 'S', false),
      ('BETA-2-GLICOPROTEÍNA I, ANTICORPOS IgG E IgM', NULL, '40308898', NULL, false),
      ('BETA-2-MICROGLOBULINA - PESQUISA E/OU DOSAGEM', NULL, '40306470', 'S', false),
      ('BILIRRUBINAS', 'BIL', '40301397', 'S', false),
      ('BIÓPSIA COM COLORAÇÃO ESPECIAL', 'BCE', NULL, 'DIV', false),
      ('BIOPSIA DE COLO UTERINO', NULL, NULL, NULL, false),
      ('BIOPSIA DE ENDOMETRIO', NULL, NULL, NULL, false),
      ('BIOPSIA DE POLIPO', NULL, NULL, NULL, false),
      ('BIOPSIA DE VESICULA BILIAR', NULL, '40316170', NULL, false),
      ('BIOPSIA MULTIFRAGMENTOS (Ex: Restos Ovulares, RTU, diversos fragmentos de prostata, entre outros)', NULL, NULL, NULL, false),
      ('BIOPSIA SEXTANTE - PROSTATA (Seis Frascos)', NULL, NULL, NULL, false),
      ('BIOPSIA SIMPLES (1º frasco - 250, R$ 2º em diante R$ 175)', NULL, '40601200', NULL, false),
      ('C-TELOPEPTÍDEO - CTX-I', NULL, '40305449', 'S', false),
      ('CA 125', NULL, '40316378', NULL, false),
      ('CA 15-3', 'CA15', '40316378', 'S', false),
      ('CA 19.9', NULL, '40316378', NULL, false),
      ('CA 72-4', 'CA72', '40316378', 'S', false),
      ('CADEIAS LEVES LIVRES KAPPA/LAMBDA (FREELITE)', 'KLFREE', NULL, 'U-24', false),
      ('CÁLCIO - S', 'CA', '40301400', 'S', false),
      ('CÁLCIO - U-24', 'CA-U', '40301400', 'U-24', false),
      ('CÁLCIO IÔNICO', 'CA-IO', '40301419', 'S', false),
      ('CÁLCIO IÔNICO - CALCULADO', 'CAIOCL', '40301474', 'S', false),
      ('CALCITONINA', 'CAL-C', '40316165', 'S', false),
      ('CALPROTECTINA, DETECÇÃO NAS FEZES', NULL, '40303330', 'F', false),
      ('CAPACIDADE LIVRE DE COMBINAÇÃO DO FERRO', 'CL-CF', '40301427', 'S', false),
      ('CAPACIDADE TOTAL DE COMBINAÇÃO DO FERRO', 'CT-CF', '40301555', 'S', false),
      ('CAPSULA MAMARIA >> MAMOPLASTIA', NULL, NULL, NULL, false),
      ('CAPTURA HÍBRIDA PARA HPV - DIV', 'CHHPV', '40601293', 'DIV', false),
      ('CARDIOLIPINA IgA, AUTO ANTICORPOS', 'CARDIA', '40306135', 'S', false),
      ('CARDIOLIPINA IgG, AUTO ANTICORPOS', 'CARDIG', '40306143', 'S', false),
      ('CARDIOLIPINA IgM, AUTO ANTICORPOS', 'CARDIM', '40306151', 'S', false),
      ('CARIÓTIPO COM BANDA G - S', 'CARIB', '40501051', 'S', false),
      ('CARIÓTIPO COM BANDA G PARA 100 CÉLULAS', 'CAR100', NULL, 'S', false),
      ('CARIÓTIPO COM BANDA G PARA 50 CÉLULAS', 'CAR50', NULL, 'S', false),
      ('CATECOLAMINAS - FRAÇÕES - S', 'CATEC', NULL, 'S', false),
      ('CCP, ANTICORPOS ANTI', 'CCP', '49901010', 'S', false),
      ('CD4 - SUBPOPULAÇÃO LINFOCITÁRIA', 'CD4', '40307433', 'S', false),
      ('CEA', 'CEA', '40316122', 'S', false),
      ('CÉLULA PARIETAL, ANTICORPOS ANTI', 'A.CP', '40306429', 'S', false),
      ('CERULOPLASMINA - PESQUISA E/OU DOSAGEM', NULL, '40301478', NULL, false),
      ('CHAGAS IGG - PESQUISA E/OU DOSAGEM', NULL, '40306615', NULL, false),
      ('CHLAMYDIA TRACHOMATIS IgG, ANTICORPOS ANTI', 'CHLA-G', '40306631', 'S', false),
      ('CHLAMYDIA TRACHOMATIS IgM, ANTICORPOS ANTI', 'CHLA-M', '40306640', 'S', false),
      ('CHLAMYDIA TRACHOMATIS-NEISSERIA GONORRHOEAE (PCR)', 'PCRC', '40314278', 'UR', false),
      ('CHLAMYDIA TRACHOMATIS-NEISSERIA GONORRHOEAE (PCR) - DIV', 'PCRC', NULL, 'DIV', false),
      ('CHLAMYDIA TRACHOMATIS-NEISSERIA GONORRHOEAE (PCR) - U', 'PCRC', NULL, 'U', false),
      ('CHUMBO - S', 'PB-S', '40313107', 'S', false),
      ('CICLOSPORINA', 'CICLO', '40301486', 'S', false),
      ('CISTATINA C- DOSAGEM NO SANGUE', NULL, '40322424', 'S', false),
      ('CITOLOGIA CONVENCIONAL', NULL, NULL, NULL, false),
      ('CITOLOGIA DE LIQUIDOS', NULL, NULL, NULL, false),
      ('CITOLOGIA DE PUNÇÃO ASPIRATIVA DE AGULHA FINA', 'PAAF', NULL, 'DIV', false),
      ('CITOLOGIA EM MEIO LÍQUIDO', 'CML', NULL, 'DIV', false),
      ('CITOLOGIA ONCÓTICA', 'CO', NULL, 'DIV', false),
      ('CITOLOGIA ONCÓTICA GERAL', 'COG', NULL, 'DIV', false),
      ('CITOMEGALOVÍRUS IgG, ANTICORPOS', 'CMG-ES', '40306666', 'S', false),
      ('CITOMEGALOVÍRUS IgG, ANTICORPOS (ELFA)', 'CMV', '40306666', 'S', false),
      ('CITOMEGALOVÍRUS IGM - PESQUISA E/OU DOSAGEM', NULL, '40306674', NULL, false),
      ('CITOMEGALOVÍRUS IgM, ANTICORPOS', 'CMM-ES', '40306674', 'S', false),
      ('CITOMEGALOVIRUS IgM, ANTICORPOS (ELFA)', 'CMV-GM', '40306674', 'S', false),
      ('CLORETOS - S', 'CL', '90094654', 'S', false),
      ('CLORO - PESQUISA E/OU DOSAGEM', NULL, '40301559', 'S', false),
      ('COAGULOGRAMA + ATIVIDADES', 'COAG', '40304922', 'S', false),
      ('COBRE - S', 'COBRE', '40301567', 'S', false),
      ('COBRE - U', 'COBRE', '40301567', 'U', false),
      ('COBRE - U-24', 'COBRE', '40301567', 'U-24', false),
      ('Cocaína, pesquisa e/ou Dosagem', NULL, '40301575', NULL, false),
      ('COENZIMA Q10', NULL, '40319067', NULL, false),
      ('COFATOR RISTOCETINA - FATOR V. WILLEBRAND', NULL, '40304574', NULL, false),
      ('COLESTEROL HDL', 'HDL', '40301583', 'S', false),
      ('COLESTEROL LDL', 'LDL', '40301591', 'S', false),
      ('COLESTEROL TOTAL - S', 'C', '40301605', 'S', false),
      ('COLESTEROL VLDL', 'VLDL', '40302695', 'S', false),
      ('COMPLEMENTO C4 - PESQUISA E/OU DOSAGEM', NULL, '40306712', NULL, false),
      ('COMPLEMENTO DO CH-50', 'CCH', '40306747', 'S', false),
      ('COMPLEMENTO SÉRICO C3', 'C3', '40306704', 'S', false),
      ('COMPLEMENTO SÉRICO C4', 'C4', '40306712', 'S', false),
      ('COMPOSTO S 11 DESOXI-CORTISOL', 'CS11', '40316181', 'S', false),
      ('COOMBS DIRETO', 'CBD', '40304108', 'S', false),
      ('COOMBS INDIRETO - ANTICORPOS IRREGULARES PESQUISA', 'CBI', '40304884', 'S', false),
      ('COPROCULTURA', 'CTF', '40310175', 'F', true),
      ('COPROCULTURA-FEZES', NULL, '40310183', NULL, true),
      ('COPROLÓGICO FUNCIONAL (CARACTERES, PH, DIGESTIBILIDADE, AMÔNIA, ÁCIDOS ORGÂNICOS E INTERPRETAÇÃO)', NULL, '40303039', 'F', false),
      ('CORE BIOPSY / Frasco', NULL, NULL, NULL, false),
      ('CORTISOL BASAL - SORO', 'CORT-B', '40316190', 'S', false),
      ('CORTISOL LIVRE', NULL, '40305210', NULL, false),
      ('CORTISOL SALIVAR BASAL', 'CORSBASAL', '40316190', NULL, false),
      ('CORTISOL SALIVAR MANHA', 'CORSMAN', '40316190', NULL, false),
      ('CORTISOL SALIVAR TARDE', 'CORSTARDE', '40316190', NULL, false),
      ('CORTISOL SALIVAR NOITE', 'CORSNOITE', '40316190', 'SAL', false),
      ('CREATININA - S', 'CRE', '40301630', 'S', false),
      ('CREATININA - U', 'CRE-U', '40301630', 'U', false),
      ('CREATININA - U-24', 'CRE-U', '40301630', 'U-24', false),
      ('CREATININA, CLEARANCE', 'C-CRE', '40301508', 'S+U', false),
      ('CREATINOFOSFOQUINASE', 'CPK', '40301648', 'S', false),
      ('CREATINOFOSFOQUINASE FRAÇÃO MB - MASSA', 'CMB-M', NULL, 'S', false),
      ('CRIOGLOBULINAS - Pesquisa', NULL, '40308014', NULL, false),
      ('CROMO - S', 'CROMO', '40313310', 'S', false),
      ('CULTURA + ANTIBIOGRAMA', 'CT+ABD', NULL, 'DIV', true),
      ('CULTURA BACTERIANA (EM DIVERSOS MATERIAIS BIOLÓGICOS)', NULL, '40310124', NULL, true),
      ('CULTURA PARA FUNGOS + ANTIFUNGIGRAMA', NULL, NULL, NULL, true),
      ('CULTURA SELETIVA PARA STREPTOCOCCUS GRUPO B', 'CSSB', NULL, 'DIV', true),
      ('CULTURA, URINA COM CONTAGEM DE COLÔNIAS', NULL, '40310213', NULL, true),
      ('DAOPLUS Análise da Atividade da Enzima Diamina Oxidase (DAO)', NULL, '40316000', NULL, false),
      ('DEHIDROEPIANDROSTERONA', 'DHE', '40316211', 'S', false),
      ('DEHIDROGENASE LÁCTICA - S', 'LDH', '40301729', 'S', false),
      ('DENGUE, ANTICORPOS IgG', 'DENGUE', '40306798', 'S', false),
      ('DENGUE, ANTICORPOS IgM', 'DENGM', '40306798', 'S', false),
      ('DENGUE NS1', 'NS1', '40324192', 'S', false),
      ('DESIDROGENASE ALFA-HIDROXIBUTIRATO - PESQUISA E/OU DOSAGEM', NULL, '40301699', 'S', false),
      ('DETECÇÃO DE EPSTEIN BARR', NULL, '40314359', NULL, false),
      ('DIALDEÍDO MALÔNICO', NULL, '40313140', 'S', false),
      ('DIHIDROTESTOSTERONA', 'DHT-RE', '40316220', 'S', false),
      ('DÍMERO D', 'DIME-D', '40304906', 'S', false),
      ('ELASTASE PANCREÁTICA FECAL', 'ELASPF', '40303284', 'F', false),
      ('ELETROFORESE DE HEMOGLOBINA', 'ELFHB', '40304353', 'S', false),
      ('ELETROFORESE DE LIPOPROTEÍNAS', 'ELFLIP', '40301788', 'S', false),
      ('ELETROFORESE DE PROTEÍNAS - S', 'ELFPRO', '40301761', 'S', false),
      ('ELETROFORESE DE PROTEÍNAS DE ALTA RESOLUÇÃO', NULL, '40302717', 'S', false),
      ('ENDOMÍSIO IgA, ANTICORPOS ANTI', 'AAEIGA', '40306259', 'S', false),
      ('ENDOMÍSIO IgG - ANTICORPOS ANTI', 'AT-END', NULL, 'S', false),
      ('EPSTEIN BARR IgG - ANTICORPOS', 'EP-BRG', '40307565', 'S', false),
      ('EPSTEIN BARR IgM - ANTICORPOS', 'EP-BR', '40307581', 'S', false),
      ('ERITROPOIETINA', 'ERITRO', '40305295', 'S', false),
      ('ESQUISTOSSOMOSE, ANTICORPO IgG', 'SCH-IF', '40307719', 'S', false),
      ('ESTRADIOL, 17 BETA', 'E2', '40316246', 'S', false),
      ('ESTRIOL LIVRE', 'FE3-S', '40316254', 'S', false),
      ('ESTRONA', 'ESTRON', '40316262', 'S', false),
      ('ESTUDO GENÉTICO DA APOLIPOPROTEÍNA E - S', 'APOE-G', NULL, 'S', false),
      ('ESTUDO GENÉTICO DA HEMOCROMATOSE PLUS - DIV', 'HEMOPL', NULL, 'DIV', false),
      ('ESTUDO GENÉTICO DA MUTAÇÃO S65C PARA HEMOCROMATOSE', NULL, '40302060', 'S', false),
      ('ESTUDO GENÉTICO DAS MUTAÇÕES C282Y E H63D PARA HEMOCROMATOSE', NULL, '40712046', 'S', false),
      ('ESTUDO MOLECULAR DA MUTAÇÃO R337H NO GENE TP53', 'TP53SQ', '40503402', 'S', false),
      ('EVEROLIMUS, DOSAGEM', NULL, '40322319', NULL, false),
      ('EXAME DIRETO A FRESCO - URINA, FEZES, SECREÇÃO E ESPERMA', NULL, '41301188', NULL, false),
      ('EXAME MICOLÓGICO DIRETO', NULL, '41301226', NULL, false),
      ('FAN - PESQUISA DE ANTICORPOS ANTICÉLULA - S', 'HEP2', '40306852', 'S', false),
      ('FATOR ANTINÚCLEO, (FAN) - PESQUISA E/OU DOSAGEM', NULL, '40306852', NULL, false),
      ('FATOR DE CRESCIMENTO VASCULAR ENDOTELIAL (VEGF)', 'VEGF', '40316807', 'S', false),
      ('FATOR INTRÍNSECO, AUTO ANTICORPOS', NULL, '40308650', NULL, false),
      ('FATOR NATRIURÉTICO ATRIAL', 'FNA', '40302776', 'S', false),
      ('FATOR REUMATÓIDE - S', 'FR', '40306860', 'S', false),
      ('FATOR V DE LEIDEN POR PCR - PESQUISA', NULL, '40314057', 'S', false),
      ('FATOR V, DOSAGEM', NULL, '40304183', NULL, false),
      ('FENOBARBITAL', 'FENO', '40301834', 'S', false),
      ('FERRITINA SÉRICA', 'FERRI', '40316270', 'S', false),
      ('FERRO SÉRICO', 'FE', '40301842', 'S', false),
      ('FIBRINOGENIO - S', 'FIB-A', '40304264', 'S', false),
      ('FILÁRIA, PESQUISA - Sangue total ou esfregaço', NULL, '40304272', NULL, false),
      ('FOSFATASE ALCALINA', 'PAL', '40301885', 'S', false),
      ('FOSFATIDILSERINA, ANTICORPOS IgM, IgG e IgA', NULL, '40308685', 'S', false),
      ('FÓSFORO - S', 'P', '40301931', 'S', false),
      ('FÓSFORO - U', 'P', '40301931', 'U', false),
      ('FRUTOSAMINA', 'P-GLI', '40301958', 'S', false),
      ('FUNGOS - PESQUISA', 'FUNGOS', NULL, 'DIV', false),
      ('GAMA GT', 'YGT', '40301990', 'S', false),
      ('PAINEL GENETICO - GENERA BASIC', NULL, NULL, NULL, false),
      ('PAINEL GENETICO - GENERA PREMIUM', NULL, NULL, NULL, false),
      ('GH - HORMÔNIO DE CRESCIMENTO', 'HGH', '40316203', 'S', false),
      ('GLIADINA IgA, ANTICORPOS ANTI', 'AAG', '40306305', 'S', false),
      ('GLIADINA IgG, ANTICORPOS ANTI', 'AAGG', '40306313', 'S', false),
      ('GLIADINA IgM, ANTICORPOS ANTI', 'GLIA-M', NULL, 'S', false),
      ('GLICOSE - 2 HORAS PÓS-PRANDIAL', 'G-PP', '40302040', 'S', false),
      ('GLICOSE - JEJUM - S', 'G', '40302040', 'S', false),
      ('GLOBULINA LIGADORA DE HORMÔNIOS SEXUAIS - SHBG', 'SHBG', '40316300', 'S', false),
      ('GLUTATIONA PEROXIDASE', NULL, '40304116', 'S', false),
      ('GORDURA FECAL, DOSAGEM', NULL, '40303055', 'F', false),
      ('GRUPO SANGUÍNEO + FATOR RH/DU', 'GS-RH', '40304299', 'S', false),
      ('HAV IgG, ANTI', 'HAV-G', '40306933', 'S', false),
      ('HAV IgM, ANTI', 'HAV-M', '40306941', 'S', false),
      ('HBC IgG, ANTI', 'HBC-G', NULL, 'S', false),
      ('HBC IgM, ANTI', 'HBC-M', '40306968', 'S', false),
      ('HBC TOTAL, ANTI', 'HBCT', NULL, 'S', false),
      ('HBE-AG', 'HBE-G', '40306984', 'S', false),
      ('HBE, ANTI', 'HBE', '40306976', 'S', false),
      ('HBsAg', 'AU', '40307018', 'S', false),
      ('HCV PCR QUANTITATIVO EM TEMPO REAL - S', 'PTRHCV', '40314103', 'S', false),
      ('HCV, ANTI', 'HCV', '40307026', 'S', false),
      ('HELICOBACTER PYLORI (ANTÍGENO) - fezes', NULL, '40303209', NULL, false),
      ('HEMATOCRITO', NULL, '40304337', NULL, false),
      ('HEMOGLOBINA GLICADA (HBA1C)', 'GLIHB', '40302075', 'S', false),
      ('HEMOGRAMA COM CONTAGEM DE PLAQUETAS OU FRAÇÕES', 'HG', '40304361', 'S', false),
      ('HEMOSSEDIMENTAÇÃO, (VHS) - PESQUISA E/OU DOSAGEM', 'HS', '40304370', 'S', false),
      ('HEPATITE A - HAV - IGG - PESQUISA E/OU DOSAGEM', NULL, '40306933', NULL, false),
      ('HEPATITE A - HAV - IGM - PESQUISA E/OU DOSAGEM', NULL, '40306941', NULL, false),
      ('HEPATITE B - HBCAC - IGG (ANTI-CORE IGG OU ACOREG) - PESQUISA E/OU DOSAGEM', NULL, '40306950', NULL, false),
      ('HEPATITE E - ANTICORPOS IGG', NULL, '40324362', 'S', false),
      ('HEPATITE E - ANTICORPOS, IGM', NULL, '40324370', 'S', false),
      ('HEPATOGRAMA', NULL, '40312151', NULL, false),
      ('HERPESVÍRUS SIMPLES I E II IgG', 'HVI-IG', '40307085', 'S', false),
      ('HERPESVÍRUS SIMPLES I E II IgM', 'HVI-IM', '40307093', 'S', false),
      ('HERPESVÍRUS SIMPLES II, ANTICORPOS IgG', 'HV-IIG', '40307085', 'S', false),
      ('HISTAMINA', NULL, '40307131', NULL, false),
      ('HISTERECTOMIA (UTERO + 1 ANEXO BILATERAIS)', NULL, NULL, NULL, false),
      ('HISTERECTOMIA (UTERO + 2 ANEXOS BILATERAIS)', NULL, NULL, NULL, false),
      ('HISTOPATOLÓGICO DE PELE', 'HPELE', NULL, 'DIV', false),
      ('HIV - CARGA VIRAL PCR - PESQUISA', NULL, '40314120', NULL, false),
      ('HIV 1 E 2 PESQUISA DE ANTÍGENO E ANTICORPOS - S', 'HIV-ME', '40307182', 'S', false),
      ('HOMOCISTEÍNA', 'HOMOCI', '40302113', 'S', false),
      ('HORMÔNIO ANTI-MULLERIANO', NULL, '40316890', NULL, false),
      ('HORMÔNIO FOLÍCULO ESTIMULANTE - FSH', 'FSH', '40316289', 'S', false),
      ('HORMÔNIO LUTEINIZANTE - LH', 'LH', '40316335', 'S', false),
      ('HPV DETECÇÃO E GENOTIPAGEM DE ALTO RISCO', 'HPV-AR', NULL, 'DIV', false),
      ('HTLV I / II POR PCR (CADA) - PESQUISA', NULL, '40314162', NULL, false),
      ('HTLV I E II, ANTICORPOS ANTI - PESQUISA - S', 'HTLV1', '40307212', 'S', false),
      ('IA2, ANTI', 'IA2', '40306208', 'S', false),
      ('IGA - PESQUISA E/OU DOSAGEM', NULL, '40307220', NULL, false),
      ('IgE Componente Pelo de Gato – Fel d2 (e220)', NULL, '40307263', NULL, false),
      ('IgE Específico – Tartrazina (c717)', NULL, '40002213', NULL, false),
      ('IgE Específico – Vermelho Carmim (F340)', NULL, '40307255', NULL, false),
      ('IGE ESPECÍFICO DERMATOPHAGOIDES PTERONYSSINUS (D1)', 'IGE-DP', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA ÁCIDO BENZOICO C703', 'C703', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA ALFA LACTOALBUMINA (F76)', 'F76', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA AMENDOIM (F13)', 'F13', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA BERINJELA F262', 'F262', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA BETA LACTOGLOBULINA (F77)', 'F77', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA CAMARÃO (F24)', 'F24', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA CASEÍNA (F78)', 'F78', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA CASPA DE CÃO (E5)', 'E5', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA CLARA DE OVO (F1)', 'F1', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA EXTRATO DE COCHONILHA (F340)', 'F340', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA GEMA DE OVO (F75)', 'F75', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA GLÚTEN (F79)', 'F79', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA GLYCYPHAGUS DOMESTICUS D73', 'D73', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA GRÃO DE SOJA (F14)', 'F14', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA LEITE (F2)', 'F2', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA OVO (F245)', 'F245', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA PEIXE-BACALHAU (F3)', 'F3', '40307263', 'S', false),
      ('IGE ESPECÍFICO PARA TRIGO (F4)', 'F4', '40307263', 'S', false),
      ('IgE Insetos – Barata (I6)', NULL, '40307263', NULL, false),
      ('IGE MÚLTIPLO (FX2)', 'FX2', '40307344', 'S', false),
      ('IGE MÚLTIPLO (FX5)', 'FX5', '40307344', 'S', false),
      ('IGE MÚLTIPLO (HX2)', 'HX2', '40307344', 'S', false),
      ('IGE MÚLTIPLO (MX1)', 'MX1', '40307344', 'S', false),
      ('IGE MÚLTIPLO PARA FX74', 'FX74', '40307344', 'S', false),
      ('IgE Painel Alimentos (FX5E)', NULL, '40307271', NULL, false),
      ('IgE Painel Epitélios (EX2)', NULL, '40307255', NULL, false),
      ('IgE Poeira Doméstica – rDer p23 (d209)', NULL, '40307263', NULL, false),
      ('IgE Poeira e Ácaro (HX2)', NULL, '40307255', NULL, false),
      ('IGE TOTAL', 'IGE', '40307271', 'S', false),
      ('IGE, GRUPO ESPECÍFICO, - PESQUISA E/OU DOSAGEM', NULL, '40307255', NULL, false),
      ('IGE, POR ALÉRGENO (CADA) - PESQUISA E/OU DOSAGEM', NULL, '40307263', NULL, false),
      ('IGF-1 - SOMATOMEDINA C', 'SMC', '40316440', 'S', false),
      ('IGFBP-3 - PROTEÍNA LIGADORA-3 DO IGF', 'IGFBP3', '40305406', 'S', false),
      ('IGRA - Interferon Gama (Tuberculose)', NULL, '40324648', NULL, false),
      ('IMUNO-HISTOQUIMICA', NULL, NULL, NULL, false),
      ('IMUNO-HISTOQUIMICA - SEGUNDO BLOCO', NULL, NULL, NULL, false),
      ('IMUNOFENOTIPAGEM - PAINEL PROLIFERATIVO - S', 'IFPP', '40302725', 'S', false),
      ('IMUNOFIXAÇÃO - S', 'IMUFIX', NULL, 'S', false),
      ('IMUNOFIXAÇÃO - U-24', 'IMUFIX', NULL, 'U-24', false),
      ('IMUNOGLOBULINAS', 'IG', '40316343', 'S', false),
      ('IMUNOGLOBULINAS IgA', 'I-IA', '40324478', 'S', false),
      ('IMUNOGLOBULINAS IgG PESQUISA E/OU DOSAGEM', 'I-IG', '40307280', 'S', false),
      ('IMUNOGLOBULINAS IgM', 'I-IM', '40324087', 'S', false),
      ('IMUNOHISTOQUÍMICA GERAL', 'IH', NULL, 'DIV', false),
      ('IMUNOHISTOQUÍMICA GERAL COM ANTICORPO ISOLADO', 'IH-ISO', NULL, 'DIV', false),
      ('INDICAN- PESQUISA URINA', NULL, '40502082', 'U', false),
      ('ÍNDICE DE IMUNOPRODUÇÃO (ELETROF. E IGG EM SORO E LÍQUOR) - PESQUISA E/OU DOSAGEM', NULL, '40309096', 'D', false),
      ('INDICE DE SATURAÇÃO DE FERRO', NULL, '40321231', NULL, false),
      ('ÍNDICE DE TIROXINA LIVRE', 'T3+T4', '40316351', 'S', false),
      ('INDICE HOMA', 'HOMA-A', '40302041', 'S', false),
      ('INFECÇÕES SEXUALMENTE TRANSMISSÍVEIS, PCR - DIV', 'DSTPCR', NULL, 'DIV', false),
      ('INFECÇÕES SEXUALMENTE TRANSMISSÍVEIS, PCR - U', 'DSTPCR', NULL, 'U', false),
      ('INIBINA A - INA', NULL, '40321240', NULL, false),
      ('INIBINA B - INB', NULL, '40321258', NULL, false),
      ('INSULINA', 'INSU', '40316360', 'S', false),
      ('INSULINA BASAL', 'INSU-B', '40316360', 'S', false),
      ('INSULINA, AUTO ANTICORPOS ANTI', 'A.INS', '40316092', 'S', false),
      ('INTERLEUCINA 6- IL 6', NULL, '40321282', 'S', false),
      ('INVESTIGAÇÃOO HISTOPATOLÓGICA FETO-PLACENTÁRIA', NULL, NULL, NULL, false),
      ('IODO EM URINA', NULL, '40321878', 'U', false),
      ('LACTATO DESIDROGENASE - LDH', NULL, '40301729', NULL, false),
      ('LACTOSE, TESTE DE TOLERÂNCIA PADRÃO', 'LAC-T', '40302164', 'S', false),
      ('LAMOTRIGINA - PESQUISA E/OU DOSAGEM', NULL, '40302741', NULL, false),
      ('LEPTINA', 'LEPTI', '40305422', 'S', false),
      ('LIPASE - S', 'LIPASE', '40302199', 'S', false),
      ('LIPOPROTEÍNA - a', 'LIPOPA', '40302210', 'S', false),
      ('LÍTIO', 'LI', '40302229', 'S', false),
      ('MACRO PROLACTINA', 'BPRL', '40305775', 'S', false),
      ('MAGNÉSIO - S', 'MAG', '40302237', 'S', false),
      ('MAMOPLASTIA (BILATERAL)', NULL, NULL, NULL, false),
      ('MAMOPLASTIA UNILATERAL', NULL, NULL, NULL, false),
      ('MANGANÊS', 'MN', '40321967', 'S', false),
      ('METANEFRINAS PLASMÁTICAS', NULL, '81032200', 'S', false),
      ('Micologico Direto', NULL, NULL, NULL, false),
      ('MICOPLASMA PNEUMONIAE - IGG - PESQUISA E/OU DOSAGEM', NULL, '40307522', NULL, false),
      ('MICOPLASMA PNEUMONIAE - IGM - PESQUISA E/OU DOSAGEM', NULL, '40307530', NULL, false),
      ('MICROALBUMINÚRIA - U', 'M-ALB', '40311171', 'U', false),
      ('MICROALBUMINÚRIA - U-24', 'M-ALB', '40311171', 'U-24', false),
      ('MICROBIOMA VAGINAL', NULL, NULL, NULL, false),
      ('MIOGLOBINA, PESQUISA - NA URINA', NULL, '40311341', 'U', false),
      ('MIOGLOBINA, PESQUISA E/OU DOSAGEM', NULL, '40302245', 'S', false),
      ('MIOGLOBINA, SORO', 'MIOGL', '40302245', 'S', false),
      ('Mutação de MTHFR', NULL, NULL, NULL, false),
      ('Mutação do gene PAI', NULL, NULL, NULL, false),
      ('Mutação fator V de Leiden', NULL, NULL, NULL, false),
      ('MUTAÇÂO MPL (W515L e W515K)', NULL, '40503666', 'S', false),
      ('MUTAÇÕES A1298C E C677T DA MTHFR', NULL, '40314286', 'S', false),
      ('MUTAÇÕES NO EXON 9 DO GENE DA CALRETICULINA (CALR)', NULL, '40323986', 'S', false),
      ('MYCOPLASMA HOMINIS/UREAPLASMA UREALYTICUM - PCR', NULL, NULL, NULL, false),
      ('Nicotina qualitativa urina (amostra isolada)', NULL, '40321436', NULL, false),
      ('NT-proBNP - PEPTÍDEO NATRIURÉTICO CEREBRAL', 'BNP', '40302776', 'S', false),
      ('PAINEL CANDIDA', NULL, NULL, NULL, false),
      ('Painel de Trombofilias', NULL, NULL, NULL, false),
      ('PAINEL IST I (7 Patógenos)', NULL, NULL, NULL, false),
      ('PAINEL IST IV', NULL, NULL, NULL, false),
      ('PAINEL IST VIII ( IST I + Strep )', NULL, NULL, NULL, false),
      ('Painel Lactobacillus', NULL, NULL, NULL, false),
      ('PAINEL MOLECULAR PARA DOENÇA DE ALZHEIMER', 'P-ALZH', NULL, 'DIV', false),
      ('PAINEL PARA CÂNCER DE MAMA E OVÁRIO HEREDITÁRIOS', 'MAOV', '40304326', 'S', false),
      ('PAINEL PARA CÂNCER HEREDITÁRIO', 'PC-HER', NULL, 'S', false),
      ('PAINEL PARA CÂNCER HEREDITÁRIO EXPANDIDO', 'PCHA', '40503801', 'S', false),
      ('PAINEL SARS-COV-2, RSV, FLU A E FLU B, PCR REAL TIME', 'T4RV', NULL, 'DIV', false),
      ('PAINEL SOMÁTICO PARA GENES DA VIA DE REPARO HOMÓLOGA DO DNA', 'CP-HRR', NULL, 'DIV', false),
      ('PAINEL ULCERA GENITAL', NULL, NULL, NULL, false),
      ('PAINEL VAGINOSE', NULL, NULL, NULL, false),
      ('Painel X (4 Patógenos)', NULL, NULL, NULL, false),
      ('PARASITOLÓGICO', 'FP', '40303110', 'F', false),
      ('PARASITOLÓGICO - MIF', 'FPM', '40303128', 'F', false),
      ('PARATORMÔNIO - PTH OU FRAÇÃO (CADA) - PESQUISA E/OU DOSAGEM', NULL, '40305465', NULL, false),
      ('PARATORMÔNIO PTH INTACTO (MOLÉCULA INTEIRA)', 'PTH', '40316424', 'S', false),
      ('PARVOVÍRUS B19 IgG, ANTICORPOS ANTI', 'PARVOG', NULL, 'S', false),
      ('PARVOVÍRUS B19 IgM, ANTICORPOS ANTI', 'PARVOM', NULL, 'S', false),
      ('PCR - Herpes I e II', NULL, NULL, NULL, false),
      ('PCR - PROTEÍNA C REATIVA QUANTITATIVA', 'PCRNUS', '40308383', 'S', false),
      ('PCR - PROTEÍNA C REATIVA QUANTITATIVA ALTA SENSIBILIDADE', 'PC-RQ', '40308391', 'S', false),
      ('PCR CLAMÃDIA/ GONOCOCOS', NULL, NULL, NULL, false),
      ('PCR HPV ALTO RISCO', NULL, NULL, NULL, false),
      ('PCR HPV GENOTIPAGEM 28 TIPOS', NULL, NULL, NULL, false),
      ('PCR HPV GENOTIPAGEM 35 TIPOS', NULL, NULL, NULL, false),
      ('PCR HPV Quant 21', NULL, NULL, NULL, false),
      ('PCR PARA HPV A/B', NULL, NULL, NULL, false),
      ('PEÇA CIRÚRGICA', 'PCRS', '40601218', 'DIV', false),
      ('PECA CIRURGICA COMPLEXA', NULL, NULL, NULL, false),
      ('PEÇA CIRÚRGICA POR ÓRGÃO ADICIONAL', 'PCRSN', '40601226', 'DIV', false),
      ('PECA CIRURGICA SIMPLES (Ex: Mama)', NULL, NULL, NULL, false),
      ('PECA DE COLO UTERINO - CONIZACAO, CAF, LEEP ou a frio', NULL, NULL, NULL, false),
      ('Pele - Por frasco', NULL, NULL, NULL, false),
      ('PEPTÍDEO C', 'PEP', '40316394', 'S', false),
      ('PERFIL COMPLETO ÁCIDOS GRAXOS', NULL, '40302890', NULL, false),
      ('Perfil de Trombose (04 mutaÃ§Ãµes)', NULL, NULL, NULL, false),
      ('Perfil de Trombose (06 mutaÃ§Ãµes)', NULL, NULL, NULL, false),
      ('PERFIL DOS ÁCIDOS GRAXOS', NULL, '40302903', NULL, false),
      ('PERFIL LIPÍDICO', 'LIPIDG', '40302750', 'S', false),
      ('Pesquisa da Mutação V600E no Gene BRAF - Tumor', NULL, '40503780', NULL, false),
      ('PESQUISA DE BANDAS OLIGOCLONAIS POR ISOFOCALIZAÇÃO - PESQUISA E/OU DOSAGEM EM LÍQUIDOS ORGÂNICOS', NULL, '40309134', 'L', false),
      ('Pesquisa de Mutação no Gene Jak2 V617F - Sangue', NULL, '40503372', NULL, false),
      ('Pesquisa de Mutações nos Genes KRAS e NRAS - Tumor', NULL, '40503771', NULL, false),
      ('PLACENTA, CORDAO E MEMBRANAS', NULL, '40316170', NULL, false),
      ('POTÁSSIO - S', 'K', '40302318', 'S', false),
      ('PRECIVITY AD2 (ALZHEIMER) - FLEURY', 'BIOL-F', NULL, 'S', false),
      ('PREGNENOLONA', NULL, '40317030', 'S', false),
      ('PROGESTERONA', 'PG', '40316408', 'S', false),
      ('PROLACTINA', 'PRL', '40316416', 'S', false),
      ('PROSTAGLANDINA E2 - urina 24h', NULL, '90010158', 'UR24', false),
      ('PROSTATECTOMIA RADICAL', NULL, NULL, NULL, false),
      ('Proteína Beta Trace (Prostaglandina D2 Sintetase)', NULL, '40306470', 'S', false),
      ('PROTEÍNA C ANTIGÊNICA', 'PC-ANT', '40323706', 'S', false),
      ('Proteína C Funcional', NULL, '40304507', NULL, false),
      ('PROTEINA C REATIVA', NULL, '40308383', NULL, false),
      ('PROTEÍNA S LIVRE, DOSAGEM', NULL, '40304787', 'S', false),
      ('PROTEÍNA S TOTAL, DOSAGEM', 'PS-ATT', '40314197', 'S', false),
      ('PROTEÍNAS - DOSAGEM - U-12', 'PROTE', NULL, 'U-12', false),
      ('PROTEÍNAS - DOSAGEM - U-24', 'PROTE', NULL, 'U-24', false),
      ('PROTEÍNAS TOTAIS - PESQUISA E/OU DOSAGEM', NULL, '40302377', NULL, false),
      ('PROTEÍNAS TOTAIS ALBUMINA E GLOBULINA - PESQUISA E/OU DOSAGEM', 'PROTF', '40302385', 'S', false),
      ('PROTROMBINA, PESQUISA DE MUTAÇÃO', NULL, '40319326', 'S', false),
      ('PROVAS DE FUNÇÃO TIREOIDEANA (T3, T4, ÍNDICES E TSH)', 'PERFIT', '40305627', 'S', false),
      ('PSA LIVRE / TOTAL', 'PSALT', '40316130', 'S', false),
      ('PSA ULTRA SENSÍVEL', 'PSA', '40316149', 'S', false),
      ('PTF - PROTEÍNAS TOTAIS e FRAÇÕES', NULL, '40304312', NULL, false),
      ('PUNCAO ASPIRATIVA PAAF (Tireoide, Mama, PulmÃ£o)', NULL, NULL, NULL, false),
      ('RECEPTOR SOLÚVEL DE TRANSFERRINA - TRANSFERRINA', NULL, '40322246', NULL, false),
      ('RENINA DIRETA', 'RENDI', '40316432', 'S', false),
      ('RESERVA ALCALINA (BICARBONATO) - PESQUISA E/OU DOSAGEM', NULL, '40302407', NULL, false),
      ('Resseccao Transuretral - RTU de Bexiga ou Prostata', NULL, NULL, NULL, false),
      ('RETICULINA, ANTICORPOS ANTI', NULL, '40308820', 'S', false),
      ('RETICULÓCITOS', 'RET', '40304558', 'S', false),
      ('RNP, AUTO ANTICORPOS ANTI', 'RNP', '40306100', 'S', false),
      ('RT-PCR EXPRESS CORONAVÍRUS SARS-CoV-2', 'TRMCOV', NULL, 'DIV', false),
      ('RUBÉOLA - IGG - PESQUISA E/OU DOSAGEM', NULL, '40307697', NULL, false),
      ('RUBÉOLA - IGM - PESQUISA E/OU DOSAGEM', NULL, '40307700', NULL, false),
      ('RUBÉOLA IgG, ANTICORPOS ANTI - S', 'RUB-G', '40307697', 'S', false),
      ('RUBÉOLA IgG, ANTICORPOS ANTI (ELFA)', 'RUBE-G', '40307697', 'S', false),
      ('RUBÉOLA IgM, ANTICORPOS ANTI - S', 'RUB-M', '40307700', 'S', false),
      ('RUBÉOLA IgM, ANTICORPOS ANTI (ELFA)', 'RUBE-M', '40307700', 'S', false),
      ('SACCHAROMYCES CEREVISIAE, ANTICORPOS IgG E IgA', 'ASCA', '40324419', 'S', false),
      ('SANGUE OCULTO ANTICORPOS MONOCLONAIS', 'S.OC.', '40303136', 'F', false),
      ('SARS COV-2, ANTICORPOS IgG', 'COVIGG', NULL, 'S', false),
      ('SCHISTOSOMOSE - IGM - PESQUISA E/OU DOSAGEM', NULL, '40307727', NULL, false),
      ('SELÊNIO SÉRICO', 'SELE', '40313255', 'S', false),
      ('SEROTONINA', NULL, '40321550', NULL, false),
      ('SEROTONINA TOTAL', 'SERO', '49901028', 'S', false),
      ('SEXAGEM FETAL', NULL, '40312330', 'S', false),
      ('SÍFILIS - FTA-ABS-IGG - PESQUISA', NULL, '40307735', NULL, false),
      ('SÍFILIS - FTA-ABS-IGM - PESQUISA', NULL, '40307743', NULL, false),
      ('SÍFILIS - TPHA - PESQUISA', NULL, '40307751', NULL, false),
      ('SÍFILIS - VDRL', NULL, '40307760', NULL, false),
      ('SÍFILIS ANTICORPO TOTAL - PESQUISA E/OU DOSAGEM', NULL, '40308286', 'S', false),
      ('SM, AUTO ANTICORPOS ANTI', 'SM', '40306127', 'S', false),
      ('SÓDIO - S', 'NA', '40302423', 'S', false),
      ('SÓDIO - U', 'NA-U', '40302423', 'U', false),
      ('SOROLOGIA  SALMONELLA TYPHI', NULL, '40307891', NULL, false),
      ('SOROLOGIA COVID-19 (Anticorpos totais anti SARS-CoV-2)', 'COV-LC', NULL, 'S', false),
      ('SSA/RO, AUTO ANTICORPOS ANTI', 'SSA', '40306119', 'S', false),
      ('SSB/LA, AUTO ANTICORPOS ANTI', 'SSB', '40306089', 'S', false),
      ('STREPTOCOCCUS AGALACTIAE - PCR - MEIO LI[QUIDO', NULL, NULL, NULL, false),
      ('SULFATO DE DEHIDROEPIANDROSTERONA', 'SDHEA', '40316459', 'S', false),
      ('SUPEROXIDO DISMUTASE', NULL, '40322254', 'S', false),
      ('T3 LIVRE - S', 'T3 L', '40316467', 'S', false),
      ('T3 RETENCAO', NULL, '40316475', NULL, false),
      ('T3 REVERSO', 'RT3', '40316483', 'S', false),
      ('T3 TOTAL - S', 'T3-RIE', '40316556', 'S', false),
      ('T4 LIVRE - S', 'T4 L', '40316491', 'S', false),
      ('T4 TOTAL - S', 'T4-RIE', '40316548', 'S', false),
      ('TEMPO ATIVIDADE PROTROMBINA (R.N.I.) - S', 'RNI', '40304590', 'S', false),
      ('TEMPO DE TROMBOPLASTINA PARCIAL ATIVADO - S', 'TTP', '40304639', 'S', false),
      ('TESTE DO PEZINHO AMPLIADO', 'PEZAMP', '40312178', 'S', false),
      ('TESTE DO PEZINHO BÁSICO', 'PEZBAS', '40312160', 'S', false),
      ('TESTOSTERONA TOTAL', 'T1', '40316513', 'S', false),
      ('TESTOSTERONA BIODISPONÍVEL', 'T1BIOD', '40316505', 'S', false),
      ('TESTOSTERONA LIVRE CALCULADA', 'TLIVC', '40316505', 'S', false),
      ('TESTOSTERONA LIVRE SALIVAR', NULL, '40317390', 'SL', false),
      ('TIREOESTIMULANTE, HORMÔNIO (TSH) - PESQUISA E/OU DOSAGEM', NULL, '40316521', NULL, false),
      ('TIREOGLOBULINA - S', 'TIR-G', '40316530', 'S', false),
      ('TIREOGLOBULINA, ANTICORPOS ANTI', 'TIREO', '40316106', 'S', false),
      ('TIREOPEROXIDASE, ANTICORPOS ANTI - TPO', 'MICRO', '40306348', 'S', false),
      ('TOXOPLASMOSE IgG, ANTICORPOS', 'ELISAG', '40307824', 'S', false),
      ('TOXOPLASMOSE IgG, ANTICORPOS (ELFA)', 'ELFAG', '40307824', 'S', false),
      ('TOXOPLASMOSE IgM, ANTICORPOS', 'ELISAM', '40307832', 'S', false),
      ('TRAB- ANTICORPO ANTI- RECEPTOR TSH', 'AIT', '40316084', 'S', false),
      ('TRANSAMINASE OXALACÉTICA - TGO', 'TGO', '40302504', 'S', false),
      ('TRANSAMINASE PIRÚVICA - TGP', 'TGP', '40302512', 'S', false),
      ('TRANSFERRINA', 'TRA', '40302520', 'S', false),
      ('transferrina fixação', NULL, '40301427', NULL, false),
      ('TREPONEMA IgM', 'FTAM', '40307743', 'S', false),
      ('TREPONEMA PALLIDUM, PESQUISA DE ANTICORPOS IgG', 'FTA', '40307735', 'S', false),
      ('TRIGLICÉRIDES - S', 'TRI', '40302547', 'S', false),
      ('Triptase - Dosagem', NULL, '40321665', 'S', false),
      ('TROPONINA I', 'TROPOT', '40302571', 'S', false),
      ('TRYPANOSOMA CRUZI IgG (IMUNOFLUORESCÊNCIA)', 'IF-TC', '40306615', 'S', false),
      ('TRYPANOSOMA CRUZI IgM (IMUNOFLUORESCÊNCIA)', 'TC-IM', '40306623', 'S', false),
      ('TSH ULTRA SENSÍVEL - S', 'TSH-B', '40316521', 'S', false),
      ('TTG, ANTICORPOS ANTI-TRANSGLUTAMINASE TECIDUAL-IgA', 'TTG', '40308553', 'S', false),
      ('UREIA - S', 'U', '40302580', 'S', false),
      ('EAS - URINA ROTINA', 'EAS', '40311210', 'DIV', false),
      ('UROCULTURA COM ANTIBIOGRAMA', 'CT+ABU', '40310213', 'U', true),
      ('V.D.R.L. QUANTITATIVO - LIQ', 'VD', '40307760', 'LIQ', false),
      ('V.D.R.L. QUANTITATIVO - S', 'VD', '40307760', 'S', false),
      ('VARICELLA ZOSTER IgG, ANTI - S', 'VARIG', '40308162', 'S', false),
      ('VARICELLA ZOSTER IgM, ANTI - S', 'VARIM', '40308170', 'S', false),
      ('VARICELLA ZOSTER VÍRUS, PCR', NULL, '40314405', 'S', false),
      ('VASOPRESSINA - HORMÔNIO ANTIDIURÉTICO', 'VASO', '40316564', 'S', false),
      ('VITAMINA A', 'VITA', '40302601', 'S', false),
      ('VITAMINA B1 - PESQUISA E/OU DOSAGEM', 'B1', '40302784', 'S', false),
      ('VITAMINA B12', 'B12', '40316572', 'S', false),
      ('VITAMINA B2 - PESQUISA E/OU DOSAGEM', 'B2', '40302792', 'S', false),
      ('VITAMINA B3- PESQUISA E/OU DOSAGEM', 'B3', '40302806', 'S', false),
      ('VITAMINA B5', NULL, '40322262', 'S', false),
      ('VITAMINA B6 - PESQUISA E/OU DOSAGEM', 'B6', '40302814', 'S', false),
      ('VITAMINA B7 (BIOTINA)', NULL, '40322122', 'S', false),
      ('VITAMINA C', 'VITC', '40301060', 'S', false),
      ('VITAMINA E', 'VITE', '40302610', 'S', false),
      ('VITAMINA K', NULL, '40302849', 'S', false),
      ('ZIKA VÍRUS ANTICORPOS IGG', 'ZIKA-G', NULL, 'S', false),
      ('ZIKA VÍRUS ANTICORPOS IGM', 'ZIKA-M', NULL, 'S', false),
      ('ZINCO (SORO)', 'ZN-SO', '40313328', 'S', false),
      ('CADMIO - SORO', NULL, NULL, NULL, false),
      ('CADMIO - URINARIO POS JORNADA', NULL, NULL, NULL, false),
      ('CADMIO - URINARIO PRE JORNADA', NULL, NULL, NULL, false);
  END IF;
END $$;

