-- ═══════════════════════════════════════════════════════════════════════════════
-- Envio ao Apoio (Álvaro/DASA) — port do projeto envio_alvaro para o módulo AC
--
-- O laboratório NÃO analisa internamente: a requisição médica é digitalizada,
-- passa por OCR (Gemini), é conferida contra o apLIS e vira um XML AOL enviado ao
-- webservice do Álvaro. Estas tabelas portam o modelo do Supabase avulso do
-- envio_alvaro (lista_alvaro / fila_envio / requisicoes) para o banco do FlowLab:
--
--   ac_apoio_exames       ← lista_alvaro   (catálogo de códigos/materiais/preços AOL)
--   ac_apoio_fila         ← fila_envio     (fila de envio + histórico de enviados/erros)
--   ac_apoio_requisicoes  ← requisicoes    (índice codigo_lis → OS do Álvaro, p/ laudos)
--
-- Molde: ac_recoletas (Fase 6B) — RLS permissiva por authenticated para leitura e
-- escrita simples do SPA (gate = frontend + canManageColetas). O envio real ao
-- Álvaro e o pipeline de OCR passam pela API (service role) porque dependem de
-- segredos (AOL_*, GEMINI_API_KEY, APLIS_*). Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════

-- Função de updated_at compartilhada do módulo (idempotente; já existe desde a Fase 3).
CREATE OR REPLACE FUNCTION ac_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── ac_apoio_exames — catálogo de exames do apoio (códigos AOL) ─────────────────
-- Fonte de verdade para o enriquecimento pós-OCR e para o catálogo embutido no
-- prompt do Gemini. cod_exame é a chave de negócio (upsert da UI).
CREATE TABLE IF NOT EXISTS ac_apoio_exames (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cod_exame          text NOT NULL UNIQUE,          -- ex.: 'TSH'
  descricao_exame    text NOT NULL,                 -- ex.: 'Hormônio Tireoestimulante...'
  descricao_material text,                          -- ex.: 'soro'
  cod_material       text,                          -- ex.: '543' (código AOL do material)
  preco              numeric,                       -- preço de tabela do apoio (opcional)
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_ac_apoio_exames_updated_at ON ac_apoio_exames;
CREATE TRIGGER trg_ac_apoio_exames_updated_at
  BEFORE UPDATE ON ac_apoio_exames
  FOR EACH ROW EXECUTE FUNCTION ac_set_updated_at();

-- ─── ac_apoio_fila — fila de envio + histórico ───────────────────────────────────
-- Um item = uma requisição digitalizada pronta (ou tentada) para envio ao Álvaro.
-- 'aguardando'/'enviando' aparecem na aba Fila; 'enviado'/'erro' viram o Histórico.
-- xml_envio guarda senha/chave como placeholder '__ENV__' — os valores reais são
-- injetados só no backend, na hora do envio (nunca chegam ao navegador nem ao banco).
CREATE TABLE IF NOT EXISTS ac_apoio_fila (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  status            text NOT NULL DEFAULT 'aguardando'
                      CHECK (status IN ('aguardando','enviando','enviado','erro')),
  numero_requisicao text,          -- código da requisição no LIS (apLIS)
  filename          text,          -- nome/paths dos arquivos digitalizados (auditoria)
  paciente          jsonb,         -- {nome, cpf, datanasc, sexo, email, fonte}
  medico            jsonb,         -- {nome, crm}
  exames            jsonb,         -- exames extraídos/enriquecidos (com códigos AOL)
  xml_envio         text,          -- XML AOL com credenciais em placeholder
  alvaro_response   text,          -- resposta crua do webservice (última tentativa)
  erro_mensagem     text,          -- resumo do erro de negócio/HTTP (NULL em sucesso)
  resumo            jsonb,         -- contadores do pipeline (divergências, totais)
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ac_apoio_fila_status  ON ac_apoio_fila(status);
CREATE INDEX IF NOT EXISTS idx_ac_apoio_fila_updated ON ac_apoio_fila(updated_at DESC);

DROP TRIGGER IF EXISTS trg_ac_apoio_fila_updated_at ON ac_apoio_fila;
CREATE TRIGGER trg_ac_apoio_fila_updated_at
  BEFORE UPDATE ON ac_apoio_fila
  FOR EACH ROW EXECUTE FUNCTION ac_set_updated_at();

-- ─── ac_apoio_requisicoes — índice requisição LIS → OS do Álvaro ─────────────────
-- Upsert a cada envio bem-sucedido (chave = codigo_lis). É o elo para buscar o
-- laudo no Álvaro depois (codigo_os = idAlvaro da resposta de inclusão).
CREATE TABLE IF NOT EXISTS ac_apoio_requisicoes (
  codigo_lis  text PRIMARY KEY,                    -- nº da requisição no LIS
  codigo_os   text NOT NULL,                       -- idAlvaro (OS no apoio)
  nome        text NOT NULL,                       -- snapshot do paciente
  datanasc    date NOT NULL,
  data_coleta timestamptz NOT NULL,
  laudo       jsonb,                               -- {http_status, resposta_alvaro}
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_ac_apoio_requisicoes_updated_at ON ac_apoio_requisicoes;
CREATE TRIGGER trg_ac_apoio_requisicoes_updated_at
  BEFORE UPDATE ON ac_apoio_requisicoes
  FOR EACH ROW EXECUTE FUNCTION ac_set_updated_at();

-- ─── RLS — permissiva por authenticated (gate real = frontend) ───────────────────
ALTER TABLE ac_apoio_exames       ENABLE ROW LEVEL SECURITY;
ALTER TABLE ac_apoio_fila         ENABLE ROW LEVEL SECURITY;
ALTER TABLE ac_apoio_requisicoes  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ac_apoio_exames_select_all"  ON ac_apoio_exames;
DROP POLICY IF EXISTS "ac_apoio_exames_insert_auth" ON ac_apoio_exames;
DROP POLICY IF EXISTS "ac_apoio_exames_update_auth" ON ac_apoio_exames;
DROP POLICY IF EXISTS "ac_apoio_exames_delete_auth" ON ac_apoio_exames;
CREATE POLICY "ac_apoio_exames_select_all"  ON ac_apoio_exames FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY "ac_apoio_exames_insert_auth" ON ac_apoio_exames FOR INSERT TO authenticated WITH CHECK (TRUE);
CREATE POLICY "ac_apoio_exames_update_auth" ON ac_apoio_exames FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "ac_apoio_exames_delete_auth" ON ac_apoio_exames FOR DELETE TO authenticated USING (TRUE);

DROP POLICY IF EXISTS "ac_apoio_fila_select_all"  ON ac_apoio_fila;
DROP POLICY IF EXISTS "ac_apoio_fila_insert_auth" ON ac_apoio_fila;
DROP POLICY IF EXISTS "ac_apoio_fila_update_auth" ON ac_apoio_fila;
DROP POLICY IF EXISTS "ac_apoio_fila_delete_auth" ON ac_apoio_fila;
CREATE POLICY "ac_apoio_fila_select_all"  ON ac_apoio_fila FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY "ac_apoio_fila_insert_auth" ON ac_apoio_fila FOR INSERT TO authenticated WITH CHECK (TRUE);
CREATE POLICY "ac_apoio_fila_update_auth" ON ac_apoio_fila FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "ac_apoio_fila_delete_auth" ON ac_apoio_fila FOR DELETE TO authenticated USING (TRUE);

-- Requisições enviadas: escrita só pelo backend (service role ignora RLS) — o SPA
-- apenas consulta o vínculo requisição → OS.
DROP POLICY IF EXISTS "ac_apoio_requisicoes_select_all" ON ac_apoio_requisicoes;
CREATE POLICY "ac_apoio_requisicoes_select_all" ON ac_apoio_requisicoes FOR SELECT TO authenticated USING (TRUE);

-- ─── Bucket privado p/ as requisições digitalizadas ──────────────────────────────
-- O SPA sobe os arquivos direto (authenticated) e passa os paths para a API rodar o
-- OCR; leitura via signed URL. PRIVADO: são documentos médicos com dados de paciente.
INSERT INTO storage.buckets (id, name, public)
VALUES ('ac-apoio-requisicoes', 'ac-apoio-requisicoes', false)
ON CONFLICT (id) DO UPDATE SET public = false;

DROP POLICY IF EXISTS "ac_apoio_requisicoes_storage_insert" ON storage.objects;
DROP POLICY IF EXISTS "ac_apoio_requisicoes_storage_select" ON storage.objects;
DROP POLICY IF EXISTS "ac_apoio_requisicoes_storage_delete" ON storage.objects;

CREATE POLICY "ac_apoio_requisicoes_storage_insert"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'ac-apoio-requisicoes');

CREATE POLICY "ac_apoio_requisicoes_storage_select"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'ac-apoio-requisicoes');

CREATE POLICY "ac_apoio_requisicoes_storage_delete"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'ac-apoio-requisicoes');
