-- ============================================================================
-- Lotes: responsável pelo fechamento, preenchido do apLIS para os lotes que já
-- existem (depende de 20260929150000).
--
-- Fonte: fathistorico (último evento Tipo 54 / StatusLote 3 de cada lote) →
-- autusuario.NomUsuario, lido em 29/09 para os 1518 lotes de produção com
-- aplis_id do apLIS. 1515 têm o evento:
--   Renata Queiroz Bento                      723
--   Rívia Freire Araujo Barretos Borba        494
--   Raquel dos Santos Avelino                 259
--   Ana Lúcia Tavares                          31
--   Maria Eduarda Fonseca Bomfim                6
--   Lucas Dourado Soares Mendes                 1
--   Marcos da Costa Avelar Junior               1
-- Sem evento de fechamento no apLIS (3): 5134, 6125, 6647 — ficam NULL.
--
-- Só preenche onde está vazio: não sobrescreve o que a criação de título
-- gravar entre hoje e o push. Rodar de novo não muda nada.
-- ============================================================================

BEGIN;

UPDATE lotes l
   SET responsavel_fechamento = v.nome
  FROM (VALUES
  ('1996', 'Raquel dos Santos Avelino'),
  ('3781', 'Rívia Freire Araujo Barretos Borba'),
  ('3930', 'Raquel dos Santos Avelino'),
  ('3992', 'Rívia Freire Araujo Barretos Borba'),
  ('4033', 'Raquel dos Santos Avelino'),
  ('4421', 'Raquel dos Santos Avelino'),
  ('4460', 'Raquel dos Santos Avelino'),
  ('4625', 'Rívia Freire Araujo Barretos Borba'),
  ('4671', 'Raquel dos Santos Avelino'),
  ('4728', 'Rívia Freire Araujo Barretos Borba'),
  ('4729', 'Rívia Freire Araujo Barretos Borba'),
  ('4730', 'Ana Lúcia Tavares'),
  ('4732', 'Ana Lúcia Tavares'),
  ('4736', 'Ana Lúcia Tavares'),
  ('4750', 'Rívia Freire Araujo Barretos Borba'),
  ('4763', 'Rívia Freire Araujo Barretos Borba'),
  ('4779', 'Rívia Freire Araujo Barretos Borba'),
  ('4780', 'Rívia Freire Araujo Barretos Borba'),
  ('4781', 'Raquel dos Santos Avelino'),
  ('4786', 'Raquel dos Santos Avelino'),
  ('4787', 'Renata Queiroz Bento'),
  ('4788', 'Ana Lúcia Tavares'),
  ('4789', 'Rívia Freire Araujo Barretos Borba'),
  ('4792', 'Raquel dos Santos Avelino'),
  ('4797', 'Ana Lúcia Tavares'),
  ('4799', 'Ana Lúcia Tavares'),
  ('4800', 'Ana Lúcia Tavares'),
  ('4802', 'Ana Lúcia Tavares'),
  ('4803', 'Ana Lúcia Tavares'),
  ('4804', 'Ana Lúcia Tavares'),
  ('4805', 'Ana Lúcia Tavares'),
  ('4806', 'Ana Lúcia Tavares'),
  ('4807', 'Ana Lúcia Tavares'),
  ('4808', 'Rívia Freire Araujo Barretos Borba'),
  ('4809', 'Rívia Freire Araujo Barretos Borba'),
  ('4810', 'Ana Lúcia Tavares'),
  ('4811', 'Ana Lúcia Tavares'),
  ('4812', 'Ana Lúcia Tavares'),
  ('4813', 'Ana Lúcia Tavares'),
  ('4814', 'Ana Lúcia Tavares'),
  ('4815', 'Ana Lúcia Tavares'),
  ('4816', 'Ana Lúcia Tavares'),
  ('4817', 'Ana Lúcia Tavares'),
  ('4818', 'Ana Lúcia Tavares'),
  ('4821', 'Ana Lúcia Tavares'),
  ('4822', 'Ana Lúcia Tavares'),
  ('4823', 'Raquel dos Santos Avelino'),
  ('4824', 'Ana Lúcia Tavares'),
  ('4825', 'Rívia Freire Araujo Barretos Borba'),
  ('4826', 'Rívia Freire Araujo Barretos Borba'),
  ('4827', 'Rívia Freire Araujo Barretos Borba'),
  ('4828', 'Rívia Freire Araujo Barretos Borba'),
  ('4829', 'Rívia Freire Araujo Barretos Borba'),
  ('4830', 'Rívia Freire Araujo Barretos Borba'),
  ('4831', 'Rívia Freire Araujo Barretos Borba'),
  ('4832', 'Rívia Freire Araujo Barretos Borba'),
  ('4833', 'Rívia Freire Araujo Barretos Borba'),
  ('4837', 'Ana Lúcia Tavares'),
  ('4838', 'Ana Lúcia Tavares'),
  ('4840', 'Rívia Freire Araujo Barretos Borba'),
  ('4841', 'Raquel dos Santos Avelino'),
  ('4843', 'Raquel dos Santos Avelino'),
  ('4844', 'Maria Eduarda Fonseca Bomfim'),
  ('4845', 'Raquel dos Santos Avelino'),
  ('4846', 'Renata Queiroz Bento'),
  ('4848', 'Raquel dos Santos Avelino'),
  ('4849', 'Raquel dos Santos Avelino'),
  ('4850', 'Raquel dos Santos Avelino'),
  ('4851', 'Rívia Freire Araujo Barretos Borba'),
  ('4852', 'Rívia Freire Araujo Barretos Borba'),
  ('4853', 'Rívia Freire Araujo Barretos Borba'),
  ('4854', 'Raquel dos Santos Avelino'),
  ('4855', 'Rívia Freire Araujo Barretos Borba'),
  ('4856', 'Rívia Freire Araujo Barretos Borba'),
  ('4857', 'Raquel dos Santos Avelino'),
  ('4859', 'Raquel dos Santos Avelino'),
  ('4860', 'Raquel dos Santos Avelino'),
  ('4861', 'Raquel dos Santos Avelino'),
  ('4862', 'Raquel dos Santos Avelino'),
  ('4863', 'Raquel dos Santos Avelino'),
  ('4864', 'Raquel dos Santos Avelino'),
  ('4865', 'Raquel dos Santos Avelino'),
  ('4866', 'Rívia Freire Araujo Barretos Borba'),
  ('4867', 'Raquel dos Santos Avelino'),
  ('4868', 'Raquel dos Santos Avelino'),
  ('4869', 'Raquel dos Santos Avelino'),
  ('4870', 'Raquel dos Santos Avelino'),
  ('4871', 'Raquel dos Santos Avelino'),
  ('4872', 'Renata Queiroz Bento'),
  ('4874', 'Rívia Freire Araujo Barretos Borba'),
  ('4875', 'Rívia Freire Araujo Barretos Borba'),
  ('4876', 'Raquel dos Santos Avelino'),
  ('4877', 'Raquel dos Santos Avelino'),
  ('4878', 'Raquel dos Santos Avelino'),
  ('4879', 'Raquel dos Santos Avelino'),
  ('4880', 'Raquel dos Santos Avelino'),
  ('4881', 'Raquel dos Santos Avelino'),
  ('4882', 'Raquel dos Santos Avelino'),
  ('4883', 'Rívia Freire Araujo Barretos Borba'),
  ('4884', 'Raquel dos Santos Avelino'),
  ('4885', 'Raquel dos Santos Avelino'),
  ('4894', 'Raquel dos Santos Avelino'),
  ('4895', 'Raquel dos Santos Avelino'),
  ('4896', 'Raquel dos Santos Avelino'),
  ('4897', 'Raquel dos Santos Avelino'),
  ('4898', 'Rívia Freire Araujo Barretos Borba'),
  ('4899', 'Rívia Freire Araujo Barretos Borba'),
  ('4901', 'Raquel dos Santos Avelino'),
  ('4902', 'Renata Queiroz Bento'),
  ('4903', 'Rívia Freire Araujo Barretos Borba'),
  ('4904', 'Rívia Freire Araujo Barretos Borba'),
  ('4905', 'Rívia Freire Araujo Barretos Borba'),
  ('4908', 'Raquel dos Santos Avelino'),
  ('4909', 'Raquel dos Santos Avelino'),
  ('4910', 'Rívia Freire Araujo Barretos Borba'),
  ('4911', 'Raquel dos Santos Avelino'),
  ('4913', 'Raquel dos Santos Avelino'),
  ('4914', 'Rívia Freire Araujo Barretos Borba'),
  ('4915', 'Rívia Freire Araujo Barretos Borba'),
  ('4916', 'Raquel dos Santos Avelino'),
  ('4917', 'Raquel dos Santos Avelino'),
  ('4919', 'Rívia Freire Araujo Barretos Borba'),
  ('4920', 'Raquel dos Santos Avelino'),
  ('4922', 'Raquel dos Santos Avelino'),
  ('4923', 'Rívia Freire Araujo Barretos Borba'),
  ('4924', 'Raquel dos Santos Avelino'),
  ('4925', 'Renata Queiroz Bento'),
  ('4926', 'Raquel dos Santos Avelino'),
  ('4927', 'Rívia Freire Araujo Barretos Borba'),
  ('4928', 'Raquel dos Santos Avelino'),
  ('4929', 'Rívia Freire Araujo Barretos Borba'),
  ('4930', 'Raquel dos Santos Avelino'),
  ('4931', 'Raquel dos Santos Avelino'),
  ('4932', 'Rívia Freire Araujo Barretos Borba'),
  ('4933', 'Raquel dos Santos Avelino'),
  ('4934', 'Raquel dos Santos Avelino'),
  ('4935', 'Ana Lúcia Tavares'),
  ('4936', 'Raquel dos Santos Avelino'),
  ('4937', 'Raquel dos Santos Avelino'),
  ('4938', 'Raquel dos Santos Avelino'),
  ('4939', 'Raquel dos Santos Avelino'),
  ('4940', 'Rívia Freire Araujo Barretos Borba'),
  ('4941', 'Raquel dos Santos Avelino'),
  ('4942', 'Raquel dos Santos Avelino'),
  ('4943', 'Raquel dos Santos Avelino'),
  ('4947', 'Raquel dos Santos Avelino'),
  ('4950', 'Rívia Freire Araujo Barretos Borba'),
  ('4951', 'Renata Queiroz Bento'),
  ('4954', 'Renata Queiroz Bento'),
  ('4955', 'Raquel dos Santos Avelino'),
  ('4956', 'Rívia Freire Araujo Barretos Borba'),
  ('4957', 'Rívia Freire Araujo Barretos Borba'),
  ('4958', 'Rívia Freire Araujo Barretos Borba'),
  ('4959', 'Rívia Freire Araujo Barretos Borba'),
  ('4960', 'Rívia Freire Araujo Barretos Borba'),
  ('4961', 'Raquel dos Santos Avelino'),
  ('4962', 'Raquel dos Santos Avelino'),
  ('4963', 'Raquel dos Santos Avelino'),
  ('4964', 'Raquel dos Santos Avelino'),
  ('4965', 'Raquel dos Santos Avelino'),
  ('4966', 'Rívia Freire Araujo Barretos Borba'),
  ('4968', 'Raquel dos Santos Avelino'),
  ('4969', 'Rívia Freire Araujo Barretos Borba'),
  ('4970', 'Raquel dos Santos Avelino'),
  ('4971', 'Raquel dos Santos Avelino'),
  ('4972', 'Raquel dos Santos Avelino'),
  ('4973', 'Raquel dos Santos Avelino'),
  ('4974', 'Raquel dos Santos Avelino'),
  ('4975', 'Renata Queiroz Bento'),
  ('4976', 'Raquel dos Santos Avelino'),
  ('4977', 'Raquel dos Santos Avelino'),
  ('4978', 'Raquel dos Santos Avelino'),
  ('4986', 'Raquel dos Santos Avelino'),
  ('4987', 'Raquel dos Santos Avelino'),
  ('4988', 'Raquel dos Santos Avelino'),
  ('4989', 'Rívia Freire Araujo Barretos Borba'),
  ('4990', 'Rívia Freire Araujo Barretos Borba'),
  ('4991', 'Renata Queiroz Bento'),
  ('4992', 'Rívia Freire Araujo Barretos Borba'),
  ('4993', 'Rívia Freire Araujo Barretos Borba'),
  ('4994', 'Raquel dos Santos Avelino'),
  ('4995', 'Rívia Freire Araujo Barretos Borba'),
  ('4996', 'Rívia Freire Araujo Barretos Borba'),
  ('4997', 'Raquel dos Santos Avelino'),
  ('4998', 'Raquel dos Santos Avelino'),
  ('4999', 'Rívia Freire Araujo Barretos Borba'),
  ('5000', 'Lucas Dourado Soares Mendes'),
  ('5001', 'Rívia Freire Araujo Barretos Borba'),
  ('5002', 'Raquel dos Santos Avelino'),
  ('5003', 'Raquel dos Santos Avelino'),
  ('5004', 'Raquel dos Santos Avelino'),
  ('5007', 'Raquel dos Santos Avelino'),
  ('5008', 'Raquel dos Santos Avelino'),
  ('5009', 'Raquel dos Santos Avelino'),
  ('5010', 'Raquel dos Santos Avelino'),
  ('5011', 'Rívia Freire Araujo Barretos Borba'),
  ('5012', 'Renata Queiroz Bento'),
  ('5013', 'Raquel dos Santos Avelino'),
  ('5014', 'Raquel dos Santos Avelino'),
  ('5017', 'Rívia Freire Araujo Barretos Borba'),
  ('5018', 'Rívia Freire Araujo Barretos Borba'),
  ('5022', 'Rívia Freire Araujo Barretos Borba'),
  ('5023', 'Raquel dos Santos Avelino'),
  ('5024', 'Rívia Freire Araujo Barretos Borba'),
  ('5025', 'Renata Queiroz Bento'),
  ('5026', 'Raquel dos Santos Avelino'),
  ('5027', 'Rívia Freire Araujo Barretos Borba'),
  ('5028', 'Rívia Freire Araujo Barretos Borba'),
  ('5029', 'Rívia Freire Araujo Barretos Borba'),
  ('5030', 'Raquel dos Santos Avelino'),
  ('5031', 'Rívia Freire Araujo Barretos Borba'),
  ('5032', 'Raquel dos Santos Avelino'),
  ('5033', 'Raquel dos Santos Avelino'),
  ('5035', 'Rívia Freire Araujo Barretos Borba'),
  ('5036', 'Raquel dos Santos Avelino'),
  ('5037', 'Raquel dos Santos Avelino'),
  ('5038', 'Raquel dos Santos Avelino'),
  ('5039', 'Raquel dos Santos Avelino'),
  ('5040', 'Raquel dos Santos Avelino'),
  ('5041', 'Raquel dos Santos Avelino'),
  ('5042', 'Raquel dos Santos Avelino'),
  ('5045', 'Raquel dos Santos Avelino'),
  ('5049', 'Raquel dos Santos Avelino'),
  ('5050', 'Raquel dos Santos Avelino'),
  ('5051', 'Raquel dos Santos Avelino'),
  ('5052', 'Raquel dos Santos Avelino'),
  ('5053', 'Raquel dos Santos Avelino'),
  ('5054', 'Raquel dos Santos Avelino'),
  ('5055', 'Raquel dos Santos Avelino'),
  ('5056', 'Raquel dos Santos Avelino'),
  ('5057', 'Raquel dos Santos Avelino'),
  ('5060', 'Rívia Freire Araujo Barretos Borba'),
  ('5063', 'Raquel dos Santos Avelino'),
  ('5064', 'Raquel dos Santos Avelino'),
  ('5065', 'Raquel dos Santos Avelino'),
  ('5066', 'Raquel dos Santos Avelino'),
  ('5068', 'Renata Queiroz Bento'),
  ('5069', 'Rívia Freire Araujo Barretos Borba'),
  ('5070', 'Rívia Freire Araujo Barretos Borba'),
  ('5074', 'Raquel dos Santos Avelino'),
  ('5075', 'Raquel dos Santos Avelino'),
  ('5076', 'Ana Lúcia Tavares'),
  ('5077', 'Raquel dos Santos Avelino'),
  ('5079', 'Raquel dos Santos Avelino'),
  ('5080', 'Raquel dos Santos Avelino'),
  ('5081', 'Rívia Freire Araujo Barretos Borba'),
  ('5082', 'Rívia Freire Araujo Barretos Borba'),
  ('5083', 'Rívia Freire Araujo Barretos Borba'),
  ('5084', 'Rívia Freire Araujo Barretos Borba'),
  ('5087', 'Raquel dos Santos Avelino'),
  ('5088', 'Raquel dos Santos Avelino'),
  ('5089', 'Raquel dos Santos Avelino'),
  ('5090', 'Raquel dos Santos Avelino'),
  ('5091', 'Renata Queiroz Bento'),
  ('5092', 'Raquel dos Santos Avelino'),
  ('5093', 'Rívia Freire Araujo Barretos Borba'),
  ('5094', 'Rívia Freire Araujo Barretos Borba'),
  ('5095', 'Rívia Freire Araujo Barretos Borba'),
  ('5097', 'Raquel dos Santos Avelino'),
  ('5098', 'Raquel dos Santos Avelino'),
  ('5099', 'Raquel dos Santos Avelino'),
  ('5101', 'Raquel dos Santos Avelino'),
  ('5114', 'Raquel dos Santos Avelino'),
  ('5115', 'Raquel dos Santos Avelino'),
  ('5116', 'Raquel dos Santos Avelino'),
  ('5117', 'Raquel dos Santos Avelino'),
  ('5118', 'Raquel dos Santos Avelino'),
  ('5119', 'Raquel dos Santos Avelino'),
  ('5120', 'Raquel dos Santos Avelino'),
  ('5123', 'Raquel dos Santos Avelino'),
  ('5124', 'Maria Eduarda Fonseca Bomfim'),
  ('5125', 'Raquel dos Santos Avelino'),
  ('5126', 'Raquel dos Santos Avelino'),
  ('5127', 'Rívia Freire Araujo Barretos Borba'),
  ('5131', 'Rívia Freire Araujo Barretos Borba'),
  ('5132', 'Rívia Freire Araujo Barretos Borba'),
  ('5133', 'Rívia Freire Araujo Barretos Borba'),
  ('5135', 'Rívia Freire Araujo Barretos Borba'),
  ('5136', 'Raquel dos Santos Avelino'),
  ('5137', 'Raquel dos Santos Avelino'),
  ('5139', 'Rívia Freire Araujo Barretos Borba'),
  ('5140', 'Rívia Freire Araujo Barretos Borba'),
  ('5141', 'Raquel dos Santos Avelino'),
  ('5142', 'Raquel dos Santos Avelino'),
  ('5143', 'Rívia Freire Araujo Barretos Borba'),
  ('5147', 'Raquel dos Santos Avelino'),
  ('5148', 'Raquel dos Santos Avelino'),
  ('5150', 'Rívia Freire Araujo Barretos Borba'),
  ('5151', 'Raquel dos Santos Avelino'),
  ('5154', 'Rívia Freire Araujo Barretos Borba'),
  ('5155', 'Raquel dos Santos Avelino'),
  ('5156', 'Rívia Freire Araujo Barretos Borba'),
  ('5157', 'Raquel dos Santos Avelino'),
  ('5158', 'Raquel dos Santos Avelino'),
  ('5159', 'Raquel dos Santos Avelino'),
  ('5161', 'Rívia Freire Araujo Barretos Borba'),
  ('5162', 'Rívia Freire Araujo Barretos Borba'),
  ('5163', 'Rívia Freire Araujo Barretos Borba'),
  ('5165', 'Rívia Freire Araujo Barretos Borba'),
  ('5166', 'Rívia Freire Araujo Barretos Borba'),
  ('5167', 'Raquel dos Santos Avelino'),
  ('5168', 'Raquel dos Santos Avelino'),
  ('5169', 'Rívia Freire Araujo Barretos Borba'),
  ('5171', 'Rívia Freire Araujo Barretos Borba'),
  ('5172', 'Raquel dos Santos Avelino'),
  ('5176', 'Raquel dos Santos Avelino'),
  ('5177', 'Raquel dos Santos Avelino'),
  ('5178', 'Raquel dos Santos Avelino'),
  ('5179', 'Raquel dos Santos Avelino'),
  ('5180', 'Rívia Freire Araujo Barretos Borba'),
  ('5181', 'Raquel dos Santos Avelino'),
  ('5184', 'Rívia Freire Araujo Barretos Borba'),
  ('5185', 'Rívia Freire Araujo Barretos Borba'),
  ('5186', 'Raquel dos Santos Avelino'),
  ('5188', 'Renata Queiroz Bento'),
  ('5189', 'Raquel dos Santos Avelino'),
  ('5190', 'Rívia Freire Araujo Barretos Borba'),
  ('5191', 'Raquel dos Santos Avelino'),
  ('5192', 'Rívia Freire Araujo Barretos Borba'),
  ('5193', 'Rívia Freire Araujo Barretos Borba'),
  ('5194', 'Raquel dos Santos Avelino'),
  ('5195', 'Rívia Freire Araujo Barretos Borba'),
  ('5196', 'Rívia Freire Araujo Barretos Borba'),
  ('5197', 'Raquel dos Santos Avelino'),
  ('5198', 'Rívia Freire Araujo Barretos Borba'),
  ('5199', 'Rívia Freire Araujo Barretos Borba'),
  ('5200', 'Rívia Freire Araujo Barretos Borba'),
  ('5201', 'Raquel dos Santos Avelino'),
  ('5202', 'Rívia Freire Araujo Barretos Borba'),
  ('5204', 'Raquel dos Santos Avelino'),
  ('5205', 'Rívia Freire Araujo Barretos Borba'),
  ('5206', 'Rívia Freire Araujo Barretos Borba'),
  ('5207', 'Rívia Freire Araujo Barretos Borba'),
  ('5208', 'Rívia Freire Araujo Barretos Borba'),
  ('5209', 'Rívia Freire Araujo Barretos Borba'),
  ('5210', 'Rívia Freire Araujo Barretos Borba'),
  ('5211', 'Rívia Freire Araujo Barretos Borba'),
  ('5212', 'Raquel dos Santos Avelino'),
  ('5214', 'Rívia Freire Araujo Barretos Borba'),
  ('5215', 'Rívia Freire Araujo Barretos Borba'),
  ('5216', 'Rívia Freire Araujo Barretos Borba'),
  ('5217', 'Rívia Freire Araujo Barretos Borba'),
  ('5221', 'Rívia Freire Araujo Barretos Borba'),
  ('5222', 'Rívia Freire Araujo Barretos Borba'),
  ('5223', 'Raquel dos Santos Avelino'),
  ('5224', 'Renata Queiroz Bento'),
  ('5225', 'Maria Eduarda Fonseca Bomfim'),
  ('5226', 'Renata Queiroz Bento'),
  ('5227', 'Rívia Freire Araujo Barretos Borba'),
  ('5228', 'Rívia Freire Araujo Barretos Borba'),
  ('5229', 'Rívia Freire Araujo Barretos Borba'),
  ('5230', 'Rívia Freire Araujo Barretos Borba'),
  ('5231', 'Rívia Freire Araujo Barretos Borba'),
  ('5232', 'Renata Queiroz Bento'),
  ('5233', 'Rívia Freire Araujo Barretos Borba'),
  ('5234', 'Renata Queiroz Bento'),
  ('5235', 'Rívia Freire Araujo Barretos Borba'),
  ('5236', 'Rívia Freire Araujo Barretos Borba'),
  ('5237', 'Renata Queiroz Bento'),
  ('5238', 'Rívia Freire Araujo Barretos Borba'),
  ('5239', 'Rívia Freire Araujo Barretos Borba'),
  ('5240', 'Rívia Freire Araujo Barretos Borba'),
  ('5241', 'Rívia Freire Araujo Barretos Borba'),
  ('5242', 'Renata Queiroz Bento'),
  ('5243', 'Raquel dos Santos Avelino'),
  ('5244', 'Raquel dos Santos Avelino'),
  ('5245', 'Raquel dos Santos Avelino'),
  ('5246', 'Renata Queiroz Bento'),
  ('5247', 'Renata Queiroz Bento'),
  ('5248', 'Renata Queiroz Bento'),
  ('5249', 'Renata Queiroz Bento'),
  ('5250', 'Renata Queiroz Bento'),
  ('5251', 'Renata Queiroz Bento'),
  ('5252', 'Renata Queiroz Bento'),
  ('5253', 'Marcos da Costa Avelar Junior'),
  ('5254', 'Renata Queiroz Bento'),
  ('5255', 'Renata Queiroz Bento'),
  ('5258', 'Renata Queiroz Bento'),
  ('5259', 'Renata Queiroz Bento'),
  ('5260', 'Raquel dos Santos Avelino'),
  ('5261', 'Renata Queiroz Bento'),
  ('5263', 'Renata Queiroz Bento'),
  ('5264', 'Renata Queiroz Bento'),
  ('5270', 'Renata Queiroz Bento'),
  ('5271', 'Renata Queiroz Bento'),
  ('5272', 'Renata Queiroz Bento'),
  ('5273', 'Renata Queiroz Bento'),
  ('5274', 'Renata Queiroz Bento'),
  ('5275', 'Renata Queiroz Bento'),
  ('5276', 'Rívia Freire Araujo Barretos Borba'),
  ('5277', 'Renata Queiroz Bento'),
  ('5278', 'Renata Queiroz Bento'),
  ('5279', 'Renata Queiroz Bento'),
  ('5280', 'Rívia Freire Araujo Barretos Borba'),
  ('5281', 'Rívia Freire Araujo Barretos Borba'),
  ('5282', 'Rívia Freire Araujo Barretos Borba'),
  ('5283', 'Raquel dos Santos Avelino'),
  ('5284', 'Renata Queiroz Bento'),
  ('5285', 'Renata Queiroz Bento'),
  ('5286', 'Renata Queiroz Bento'),
  ('5287', 'Renata Queiroz Bento'),
  ('5288', 'Renata Queiroz Bento'),
  ('5289', 'Raquel dos Santos Avelino'),
  ('5290', 'Maria Eduarda Fonseca Bomfim'),
  ('5291', 'Renata Queiroz Bento'),
  ('5292', 'Renata Queiroz Bento'),
  ('5293', 'Maria Eduarda Fonseca Bomfim'),
  ('5294', 'Ana Lúcia Tavares'),
  ('5295', 'Raquel dos Santos Avelino'),
  ('5296', 'Raquel dos Santos Avelino'),
  ('5297', 'Raquel dos Santos Avelino'),
  ('5298', 'Ana Lúcia Tavares'),
  ('5299', 'Raquel dos Santos Avelino'),
  ('5300', 'Raquel dos Santos Avelino'),
  ('5301', 'Renata Queiroz Bento'),
  ('5302', 'Raquel dos Santos Avelino'),
  ('5303', 'Raquel dos Santos Avelino'),
  ('5304', 'Renata Queiroz Bento'),
  ('5305', 'Renata Queiroz Bento'),
  ('5306', 'Rívia Freire Araujo Barretos Borba'),
  ('5307', 'Renata Queiroz Bento'),
  ('5308', 'Renata Queiroz Bento'),
  ('5309', 'Renata Queiroz Bento'),
  ('5310', 'Rívia Freire Araujo Barretos Borba'),
  ('5311', 'Rívia Freire Araujo Barretos Borba'),
  ('5312', 'Raquel dos Santos Avelino'),
  ('5314', 'Renata Queiroz Bento'),
  ('5315', 'Renata Queiroz Bento'),
  ('5316', 'Renata Queiroz Bento'),
  ('5317', 'Renata Queiroz Bento'),
  ('5318', 'Renata Queiroz Bento'),
  ('5319', 'Renata Queiroz Bento'),
  ('5320', 'Rívia Freire Araujo Barretos Borba'),
  ('5321', 'Renata Queiroz Bento'),
  ('5322', 'Renata Queiroz Bento'),
  ('5324', 'Renata Queiroz Bento'),
  ('5325', 'Renata Queiroz Bento'),
  ('5327', 'Rívia Freire Araujo Barretos Borba'),
  ('5328', 'Rívia Freire Araujo Barretos Borba'),
  ('5329', 'Renata Queiroz Bento'),
  ('5330', 'Renata Queiroz Bento'),
  ('5335', 'Rívia Freire Araujo Barretos Borba'),
  ('5337', 'Renata Queiroz Bento'),
  ('5338', 'Renata Queiroz Bento'),
  ('5339', 'Renata Queiroz Bento'),
  ('5340', 'Renata Queiroz Bento'),
  ('5341', 'Renata Queiroz Bento'),
  ('5342', 'Renata Queiroz Bento'),
  ('5343', 'Renata Queiroz Bento'),
  ('5344', 'Renata Queiroz Bento'),
  ('5345', 'Renata Queiroz Bento'),
  ('5346', 'Renata Queiroz Bento'),
  ('5347', 'Maria Eduarda Fonseca Bomfim'),
  ('5348', 'Renata Queiroz Bento'),
  ('5349', 'Renata Queiroz Bento'),
  ('5350', 'Renata Queiroz Bento'),
  ('5351', 'Renata Queiroz Bento'),
  ('5352', 'Renata Queiroz Bento'),
  ('5354', 'Rívia Freire Araujo Barretos Borba'),
  ('5355', 'Rívia Freire Araujo Barretos Borba'),
  ('5356', 'Rívia Freire Araujo Barretos Borba'),
  ('5357', 'Raquel dos Santos Avelino'),
  ('5358', 'Raquel dos Santos Avelino'),
  ('5360', 'Rívia Freire Araujo Barretos Borba'),
  ('5362', 'Renata Queiroz Bento'),
  ('5363', 'Rívia Freire Araujo Barretos Borba'),
  ('5364', 'Renata Queiroz Bento'),
  ('5365', 'Renata Queiroz Bento'),
  ('5366', 'Rívia Freire Araujo Barretos Borba'),
  ('5367', 'Raquel dos Santos Avelino'),
  ('5368', 'Renata Queiroz Bento'),
  ('5369', 'Renata Queiroz Bento'),
  ('5370', 'Renata Queiroz Bento'),
  ('5371', 'Renata Queiroz Bento'),
  ('5372', 'Renata Queiroz Bento'),
  ('5373', 'Renata Queiroz Bento'),
  ('5375', 'Renata Queiroz Bento'),
  ('5377', 'Renata Queiroz Bento'),
  ('5378', 'Renata Queiroz Bento'),
  ('5379', 'Renata Queiroz Bento'),
  ('5380', 'Renata Queiroz Bento'),
  ('5381', 'Renata Queiroz Bento'),
  ('5382', 'Raquel dos Santos Avelino'),
  ('5383', 'Raquel dos Santos Avelino'),
  ('5384', 'Raquel dos Santos Avelino'),
  ('5385', 'Rívia Freire Araujo Barretos Borba'),
  ('5387', 'Renata Queiroz Bento'),
  ('5388', 'Renata Queiroz Bento'),
  ('5389', 'Renata Queiroz Bento'),
  ('5390', 'Renata Queiroz Bento'),
  ('5391', 'Renata Queiroz Bento'),
  ('5392', 'Renata Queiroz Bento'),
  ('5393', 'Renata Queiroz Bento'),
  ('5396', 'Renata Queiroz Bento'),
  ('5397', 'Renata Queiroz Bento'),
  ('5398', 'Renata Queiroz Bento'),
  ('5399', 'Rívia Freire Araujo Barretos Borba'),
  ('5400', 'Renata Queiroz Bento'),
  ('5401', 'Renata Queiroz Bento'),
  ('5402', 'Rívia Freire Araujo Barretos Borba'),
  ('5405', 'Rívia Freire Araujo Barretos Borba'),
  ('5406', 'Rívia Freire Araujo Barretos Borba'),
  ('5408', 'Renata Queiroz Bento'),
  ('5409', 'Renata Queiroz Bento'),
  ('5410', 'Renata Queiroz Bento'),
  ('5411', 'Renata Queiroz Bento'),
  ('5412', 'Renata Queiroz Bento'),
  ('5413', 'Rívia Freire Araujo Barretos Borba'),
  ('5414', 'Renata Queiroz Bento'),
  ('5416', 'Raquel dos Santos Avelino'),
  ('5417', 'Renata Queiroz Bento'),
  ('5418', 'Renata Queiroz Bento'),
  ('5419', 'Rívia Freire Araujo Barretos Borba'),
  ('5420', 'Renata Queiroz Bento'),
  ('5421', 'Renata Queiroz Bento'),
  ('5422', 'Renata Queiroz Bento'),
  ('5423', 'Renata Queiroz Bento'),
  ('5424', 'Renata Queiroz Bento'),
  ('5425', 'Renata Queiroz Bento'),
  ('5426', 'Renata Queiroz Bento'),
  ('5427', 'Renata Queiroz Bento'),
  ('5428', 'Renata Queiroz Bento'),
  ('5429', 'Renata Queiroz Bento'),
  ('5431', 'Renata Queiroz Bento'),
  ('5432', 'Raquel dos Santos Avelino'),
  ('5433', 'Raquel dos Santos Avelino'),
  ('5434', 'Raquel dos Santos Avelino'),
  ('5436', 'Renata Queiroz Bento'),
  ('5438', 'Renata Queiroz Bento'),
  ('5439', 'Renata Queiroz Bento'),
  ('5440', 'Renata Queiroz Bento'),
  ('5441', 'Renata Queiroz Bento'),
  ('5442', 'Renata Queiroz Bento'),
  ('5443', 'Renata Queiroz Bento'),
  ('5444', 'Renata Queiroz Bento'),
  ('5445', 'Renata Queiroz Bento'),
  ('5448', 'Raquel dos Santos Avelino'),
  ('5456', 'Rívia Freire Araujo Barretos Borba'),
  ('5461', 'Renata Queiroz Bento'),
  ('5462', 'Rívia Freire Araujo Barretos Borba'),
  ('5463', 'Raquel dos Santos Avelino'),
  ('5464', 'Raquel dos Santos Avelino'),
  ('5465', 'Raquel dos Santos Avelino'),
  ('5466', 'Raquel dos Santos Avelino'),
  ('5467', 'Renata Queiroz Bento'),
  ('5468', 'Renata Queiroz Bento'),
  ('5470', 'Renata Queiroz Bento'),
  ('5472', 'Rívia Freire Araujo Barretos Borba'),
  ('5473', 'Rívia Freire Araujo Barretos Borba'),
  ('5474', 'Renata Queiroz Bento'),
  ('5475', 'Renata Queiroz Bento'),
  ('5476', 'Renata Queiroz Bento'),
  ('5477', 'Renata Queiroz Bento'),
  ('5478', 'Rívia Freire Araujo Barretos Borba'),
  ('5479', 'Renata Queiroz Bento'),
  ('5480', 'Renata Queiroz Bento'),
  ('5481', 'Rívia Freire Araujo Barretos Borba'),
  ('5483', 'Rívia Freire Araujo Barretos Borba'),
  ('5484', 'Renata Queiroz Bento'),
  ('5485', 'Renata Queiroz Bento'),
  ('5488', 'Renata Queiroz Bento'),
  ('5489', 'Renata Queiroz Bento'),
  ('5490', 'Renata Queiroz Bento'),
  ('5491', 'Renata Queiroz Bento'),
  ('5492', 'Renata Queiroz Bento'),
  ('5493', 'Renata Queiroz Bento'),
  ('5494', 'Raquel dos Santos Avelino'),
  ('5495', 'Raquel dos Santos Avelino'),
  ('5496', 'Raquel dos Santos Avelino'),
  ('5500', 'Raquel dos Santos Avelino'),
  ('5501', 'Renata Queiroz Bento'),
  ('5502', 'Raquel dos Santos Avelino'),
  ('5503', 'Renata Queiroz Bento'),
  ('5504', 'Renata Queiroz Bento'),
  ('5505', 'Renata Queiroz Bento'),
  ('5506', 'Renata Queiroz Bento'),
  ('5507', 'Renata Queiroz Bento'),
  ('5508', 'Renata Queiroz Bento'),
  ('5509', 'Renata Queiroz Bento'),
  ('5510', 'Renata Queiroz Bento'),
  ('5511', 'Renata Queiroz Bento'),
  ('5512', 'Renata Queiroz Bento'),
  ('5515', 'Raquel dos Santos Avelino'),
  ('5517', 'Raquel dos Santos Avelino'),
  ('5518', 'Renata Queiroz Bento'),
  ('5519', 'Raquel dos Santos Avelino'),
  ('5520', 'Raquel dos Santos Avelino'),
  ('5521', 'Raquel dos Santos Avelino'),
  ('5524', 'Renata Queiroz Bento'),
  ('5525', 'Renata Queiroz Bento'),
  ('5526', 'Rívia Freire Araujo Barretos Borba'),
  ('5527', 'Renata Queiroz Bento'),
  ('5528', 'Renata Queiroz Bento'),
  ('5529', 'Renata Queiroz Bento'),
  ('5539', 'Renata Queiroz Bento'),
  ('5540', 'Rívia Freire Araujo Barretos Borba'),
  ('5541', 'Rívia Freire Araujo Barretos Borba'),
  ('5542', 'Rívia Freire Araujo Barretos Borba'),
  ('5543', 'Raquel dos Santos Avelino'),
  ('5546', 'Renata Queiroz Bento'),
  ('5548', 'Raquel dos Santos Avelino'),
  ('5549', 'Raquel dos Santos Avelino'),
  ('5550', 'Raquel dos Santos Avelino'),
  ('5551', 'Renata Queiroz Bento'),
  ('5552', 'Rívia Freire Araujo Barretos Borba'),
  ('5560', 'Renata Queiroz Bento'),
  ('5561', 'Rívia Freire Araujo Barretos Borba'),
  ('5562', 'Rívia Freire Araujo Barretos Borba'),
  ('5563', 'Rívia Freire Araujo Barretos Borba'),
  ('5564', 'Raquel dos Santos Avelino'),
  ('5565', 'Raquel dos Santos Avelino'),
  ('5568', 'Renata Queiroz Bento'),
  ('5569', 'Renata Queiroz Bento'),
  ('5570', 'Rívia Freire Araujo Barretos Borba'),
  ('5572', 'Rívia Freire Araujo Barretos Borba'),
  ('5573', 'Raquel dos Santos Avelino'),
  ('5574', 'Rívia Freire Araujo Barretos Borba'),
  ('5576', 'Renata Queiroz Bento'),
  ('5577', 'Renata Queiroz Bento'),
  ('5578', 'Renata Queiroz Bento'),
  ('5579', 'Renata Queiroz Bento'),
  ('5581', 'Renata Queiroz Bento'),
  ('5582', 'Raquel dos Santos Avelino'),
  ('5583', 'Raquel dos Santos Avelino'),
  ('5585', 'Renata Queiroz Bento'),
  ('5586', 'Renata Queiroz Bento'),
  ('5587', 'Renata Queiroz Bento'),
  ('5588', 'Renata Queiroz Bento'),
  ('5589', 'Renata Queiroz Bento'),
  ('5590', 'Renata Queiroz Bento'),
  ('5591', 'Renata Queiroz Bento'),
  ('5594', 'Renata Queiroz Bento'),
  ('5595', 'Rívia Freire Araujo Barretos Borba'),
  ('5596', 'Rívia Freire Araujo Barretos Borba'),
  ('5597', 'Rívia Freire Araujo Barretos Borba'),
  ('5602', 'Rívia Freire Araujo Barretos Borba'),
  ('5603', 'Rívia Freire Araujo Barretos Borba'),
  ('5604', 'Rívia Freire Araujo Barretos Borba'),
  ('5605', 'Renata Queiroz Bento'),
  ('5606', 'Renata Queiroz Bento'),
  ('5607', 'Renata Queiroz Bento'),
  ('5608', 'Renata Queiroz Bento'),
  ('5609', 'Rívia Freire Araujo Barretos Borba'),
  ('5610', 'Rívia Freire Araujo Barretos Borba'),
  ('5611', 'Rívia Freire Araujo Barretos Borba'),
  ('5612', 'Renata Queiroz Bento'),
  ('5613', 'Renata Queiroz Bento'),
  ('5614', 'Rívia Freire Araujo Barretos Borba'),
  ('5615', 'Rívia Freire Araujo Barretos Borba'),
  ('5616', 'Rívia Freire Araujo Barretos Borba'),
  ('5617', 'Rívia Freire Araujo Barretos Borba'),
  ('5619', 'Rívia Freire Araujo Barretos Borba'),
  ('5620', 'Renata Queiroz Bento'),
  ('5621', 'Renata Queiroz Bento'),
  ('5622', 'Renata Queiroz Bento'),
  ('5623', 'Renata Queiroz Bento'),
  ('5624', 'Renata Queiroz Bento'),
  ('5625', 'Renata Queiroz Bento'),
  ('5629', 'Rívia Freire Araujo Barretos Borba'),
  ('5630', 'Rívia Freire Araujo Barretos Borba'),
  ('5631', 'Renata Queiroz Bento'),
  ('5632', 'Renata Queiroz Bento'),
  ('5633', 'Renata Queiroz Bento'),
  ('5635', 'Rívia Freire Araujo Barretos Borba'),
  ('5636', 'Renata Queiroz Bento'),
  ('5637', 'Rívia Freire Araujo Barretos Borba'),
  ('5640', 'Renata Queiroz Bento'),
  ('5641', 'Renata Queiroz Bento'),
  ('5642', 'Raquel dos Santos Avelino'),
  ('5643', 'Renata Queiroz Bento'),
  ('5644', 'Renata Queiroz Bento'),
  ('5646', 'Renata Queiroz Bento'),
  ('5647', 'Rívia Freire Araujo Barretos Borba'),
  ('5648', 'Renata Queiroz Bento'),
  ('5649', 'Rívia Freire Araujo Barretos Borba'),
  ('5653', 'Raquel dos Santos Avelino'),
  ('5654', 'Renata Queiroz Bento'),
  ('5655', 'Rívia Freire Araujo Barretos Borba'),
  ('5656', 'Renata Queiroz Bento'),
  ('5657', 'Renata Queiroz Bento'),
  ('5658', 'Renata Queiroz Bento'),
  ('5659', 'Renata Queiroz Bento'),
  ('5660', 'Renata Queiroz Bento'),
  ('5661', 'Renata Queiroz Bento'),
  ('5662', 'Rívia Freire Araujo Barretos Borba'),
  ('5663', 'Renata Queiroz Bento'),
  ('5664', 'Renata Queiroz Bento'),
  ('5665', 'Raquel dos Santos Avelino'),
  ('5666', 'Rívia Freire Araujo Barretos Borba'),
  ('5667', 'Raquel dos Santos Avelino'),
  ('5671', 'Rívia Freire Araujo Barretos Borba'),
  ('5672', 'Renata Queiroz Bento'),
  ('5674', 'Renata Queiroz Bento'),
  ('5675', 'Renata Queiroz Bento'),
  ('5676', 'Rívia Freire Araujo Barretos Borba'),
  ('5678', 'Renata Queiroz Bento'),
  ('5679', 'Renata Queiroz Bento'),
  ('5681', 'Renata Queiroz Bento'),
  ('5682', 'Rívia Freire Araujo Barretos Borba'),
  ('5683', 'Rívia Freire Araujo Barretos Borba'),
  ('5684', 'Rívia Freire Araujo Barretos Borba'),
  ('5685', 'Rívia Freire Araujo Barretos Borba'),
  ('5686', 'Rívia Freire Araujo Barretos Borba'),
  ('5687', 'Rívia Freire Araujo Barretos Borba'),
  ('5688', 'Rívia Freire Araujo Barretos Borba'),
  ('5692', 'Renata Queiroz Bento'),
  ('5693', 'Renata Queiroz Bento'),
  ('5696', 'Renata Queiroz Bento'),
  ('5697', 'Renata Queiroz Bento'),
  ('5698', 'Rívia Freire Araujo Barretos Borba'),
  ('5699', 'Rívia Freire Araujo Barretos Borba'),
  ('5700', 'Renata Queiroz Bento'),
  ('5701', 'Renata Queiroz Bento'),
  ('5702', 'Rívia Freire Araujo Barretos Borba'),
  ('5703', 'Rívia Freire Araujo Barretos Borba'),
  ('5704', 'Renata Queiroz Bento'),
  ('5705', 'Renata Queiroz Bento'),
  ('5706', 'Renata Queiroz Bento'),
  ('5707', 'Rívia Freire Araujo Barretos Borba'),
  ('5708', 'Raquel dos Santos Avelino'),
  ('5709', 'Rívia Freire Araujo Barretos Borba'),
  ('5710', 'Rívia Freire Araujo Barretos Borba'),
  ('5712', 'Renata Queiroz Bento'),
  ('5713', 'Rívia Freire Araujo Barretos Borba'),
  ('5716', 'Rívia Freire Araujo Barretos Borba'),
  ('5718', 'Rívia Freire Araujo Barretos Borba'),
  ('5720', 'Raquel dos Santos Avelino'),
  ('5721', 'Renata Queiroz Bento'),
  ('5722', 'Renata Queiroz Bento'),
  ('5724', 'Renata Queiroz Bento'),
  ('5726', 'Renata Queiroz Bento'),
  ('5728', 'Renata Queiroz Bento'),
  ('5729', 'Rívia Freire Araujo Barretos Borba'),
  ('5730', 'Rívia Freire Araujo Barretos Borba'),
  ('5731', 'Rívia Freire Araujo Barretos Borba'),
  ('5732', 'Renata Queiroz Bento'),
  ('5733', 'Renata Queiroz Bento'),
  ('5734', 'Rívia Freire Araujo Barretos Borba'),
  ('5735', 'Rívia Freire Araujo Barretos Borba'),
  ('5736', 'Renata Queiroz Bento'),
  ('5737', 'Rívia Freire Araujo Barretos Borba'),
  ('5739', 'Rívia Freire Araujo Barretos Borba'),
  ('5740', 'Renata Queiroz Bento'),
  ('5741', 'Renata Queiroz Bento'),
  ('5742', 'Renata Queiroz Bento'),
  ('5743', 'Renata Queiroz Bento'),
  ('5746', 'Rívia Freire Araujo Barretos Borba'),
  ('5747', 'Renata Queiroz Bento'),
  ('5748', 'Rívia Freire Araujo Barretos Borba'),
  ('5750', 'Renata Queiroz Bento'),
  ('5751', 'Renata Queiroz Bento'),
  ('5753', 'Renata Queiroz Bento'),
  ('5754', 'Renata Queiroz Bento'),
  ('5755', 'Renata Queiroz Bento'),
  ('5756', 'Renata Queiroz Bento'),
  ('5757', 'Renata Queiroz Bento'),
  ('5758', 'Renata Queiroz Bento'),
  ('5759', 'Renata Queiroz Bento'),
  ('5760', 'Renata Queiroz Bento'),
  ('5761', 'Renata Queiroz Bento'),
  ('5762', 'Rívia Freire Araujo Barretos Borba'),
  ('5763', 'Renata Queiroz Bento'),
  ('5764', 'Renata Queiroz Bento'),
  ('5765', 'Renata Queiroz Bento'),
  ('5766', 'Rívia Freire Araujo Barretos Borba'),
  ('5767', 'Rívia Freire Araujo Barretos Borba'),
  ('5768', 'Renata Queiroz Bento'),
  ('5769', 'Renata Queiroz Bento'),
  ('5771', 'Renata Queiroz Bento'),
  ('5772', 'Renata Queiroz Bento'),
  ('5773', 'Raquel dos Santos Avelino'),
  ('5774', 'Renata Queiroz Bento'),
  ('5776', 'Raquel dos Santos Avelino'),
  ('5777', 'Rívia Freire Araujo Barretos Borba'),
  ('5778', 'Rívia Freire Araujo Barretos Borba'),
  ('5779', 'Renata Queiroz Bento'),
  ('5780', 'Renata Queiroz Bento'),
  ('5782', 'Renata Queiroz Bento'),
  ('5783', 'Renata Queiroz Bento'),
  ('5785', 'Rívia Freire Araujo Barretos Borba'),
  ('5786', 'Rívia Freire Araujo Barretos Borba'),
  ('5788', 'Renata Queiroz Bento'),
  ('5789', 'Rívia Freire Araujo Barretos Borba'),
  ('5790', 'Rívia Freire Araujo Barretos Borba'),
  ('5791', 'Rívia Freire Araujo Barretos Borba'),
  ('5792', 'Rívia Freire Araujo Barretos Borba'),
  ('5793', 'Rívia Freire Araujo Barretos Borba'),
  ('5794', 'Renata Queiroz Bento'),
  ('5795', 'Rívia Freire Araujo Barretos Borba'),
  ('5796', 'Rívia Freire Araujo Barretos Borba'),
  ('5797', 'Renata Queiroz Bento'),
  ('5798', 'Renata Queiroz Bento'),
  ('5799', 'Renata Queiroz Bento'),
  ('5800', 'Renata Queiroz Bento'),
  ('5801', 'Renata Queiroz Bento'),
  ('5802', 'Renata Queiroz Bento'),
  ('5803', 'Raquel dos Santos Avelino'),
  ('5804', 'Rívia Freire Araujo Barretos Borba'),
  ('5805', 'Rívia Freire Araujo Barretos Borba'),
  ('5806', 'Renata Queiroz Bento'),
  ('5807', 'Renata Queiroz Bento'),
  ('5808', 'Renata Queiroz Bento'),
  ('5809', 'Renata Queiroz Bento'),
  ('5811', 'Raquel dos Santos Avelino'),
  ('5812', 'Renata Queiroz Bento'),
  ('5813', 'Renata Queiroz Bento'),
  ('5814', 'Raquel dos Santos Avelino'),
  ('5816', 'Raquel dos Santos Avelino'),
  ('5821', 'Raquel dos Santos Avelino'),
  ('5822', 'Rívia Freire Araujo Barretos Borba'),
  ('5827', 'Renata Queiroz Bento'),
  ('5828', 'Renata Queiroz Bento'),
  ('5829', 'Renata Queiroz Bento'),
  ('5830', 'Renata Queiroz Bento'),
  ('5831', 'Renata Queiroz Bento'),
  ('5833', 'Renata Queiroz Bento'),
  ('5834', 'Renata Queiroz Bento'),
  ('5835', 'Rívia Freire Araujo Barretos Borba'),
  ('5836', 'Rívia Freire Araujo Barretos Borba'),
  ('5837', 'Renata Queiroz Bento'),
  ('5839', 'Raquel dos Santos Avelino'),
  ('5840', 'Raquel dos Santos Avelino'),
  ('5841', 'Renata Queiroz Bento'),
  ('5842', 'Renata Queiroz Bento'),
  ('5843', 'Rívia Freire Araujo Barretos Borba'),
  ('5844', 'Renata Queiroz Bento'),
  ('5845', 'Renata Queiroz Bento'),
  ('5846', 'Renata Queiroz Bento'),
  ('5847', 'Renata Queiroz Bento'),
  ('5848', 'Rívia Freire Araujo Barretos Borba'),
  ('5849', 'Renata Queiroz Bento'),
  ('5850', 'Renata Queiroz Bento'),
  ('5854', 'Renata Queiroz Bento'),
  ('5855', 'Renata Queiroz Bento'),
  ('5856', 'Renata Queiroz Bento'),
  ('5857', 'Renata Queiroz Bento'),
  ('5858', 'Rívia Freire Araujo Barretos Borba'),
  ('5859', 'Rívia Freire Araujo Barretos Borba'),
  ('5860', 'Renata Queiroz Bento'),
  ('5863', 'Renata Queiroz Bento'),
  ('5864', 'Renata Queiroz Bento'),
  ('5865', 'Renata Queiroz Bento'),
  ('5866', 'Renata Queiroz Bento'),
  ('5867', 'Renata Queiroz Bento'),
  ('5868', 'Renata Queiroz Bento'),
  ('5869', 'Renata Queiroz Bento'),
  ('5870', 'Renata Queiroz Bento'),
  ('5871', 'Renata Queiroz Bento'),
  ('5872', 'Renata Queiroz Bento'),
  ('5873', 'Renata Queiroz Bento'),
  ('5876', 'Renata Queiroz Bento'),
  ('5879', 'Renata Queiroz Bento'),
  ('5881', 'Rívia Freire Araujo Barretos Borba'),
  ('5882', 'Renata Queiroz Bento'),
  ('5883', 'Renata Queiroz Bento'),
  ('5884', 'Renata Queiroz Bento'),
  ('5885', 'Rívia Freire Araujo Barretos Borba'),
  ('5886', 'Renata Queiroz Bento'),
  ('5887', 'Renata Queiroz Bento'),
  ('5888', 'Renata Queiroz Bento'),
  ('5889', 'Renata Queiroz Bento'),
  ('5890', 'Raquel dos Santos Avelino'),
  ('5891', 'Renata Queiroz Bento'),
  ('5893', 'Rívia Freire Araujo Barretos Borba'),
  ('5894', 'Rívia Freire Araujo Barretos Borba'),
  ('5896', 'Renata Queiroz Bento'),
  ('5897', 'Renata Queiroz Bento'),
  ('5899', 'Renata Queiroz Bento'),
  ('5900', 'Renata Queiroz Bento'),
  ('5901', 'Renata Queiroz Bento'),
  ('5902', 'Rívia Freire Araujo Barretos Borba'),
  ('5903', 'Renata Queiroz Bento'),
  ('5904', 'Renata Queiroz Bento'),
  ('5905', 'Raquel dos Santos Avelino'),
  ('5906', 'Renata Queiroz Bento'),
  ('5907', 'Rívia Freire Araujo Barretos Borba'),
  ('5908', 'Renata Queiroz Bento'),
  ('5909', 'Renata Queiroz Bento'),
  ('5910', 'Rívia Freire Araujo Barretos Borba'),
  ('5911', 'Rívia Freire Araujo Barretos Borba'),
  ('5913', 'Renata Queiroz Bento'),
  ('5914', 'Renata Queiroz Bento'),
  ('5915', 'Renata Queiroz Bento'),
  ('5916', 'Renata Queiroz Bento'),
  ('5919', 'Rívia Freire Araujo Barretos Borba'),
  ('5923', 'Rívia Freire Araujo Barretos Borba'),
  ('5927', 'Renata Queiroz Bento'),
  ('5929', 'Renata Queiroz Bento'),
  ('5930', 'Renata Queiroz Bento'),
  ('5931', 'Renata Queiroz Bento'),
  ('5932', 'Renata Queiroz Bento'),
  ('5933', 'Renata Queiroz Bento'),
  ('5934', 'Renata Queiroz Bento'),
  ('5935', 'Renata Queiroz Bento'),
  ('5936', 'Renata Queiroz Bento'),
  ('5937', 'Renata Queiroz Bento'),
  ('5938', 'Renata Queiroz Bento'),
  ('5939', 'Renata Queiroz Bento'),
  ('5940', 'Renata Queiroz Bento'),
  ('5941', 'Rívia Freire Araujo Barretos Borba'),
  ('5942', 'Renata Queiroz Bento'),
  ('5944', 'Renata Queiroz Bento'),
  ('5946', 'Renata Queiroz Bento'),
  ('5947', 'Rívia Freire Araujo Barretos Borba'),
  ('5949', 'Renata Queiroz Bento'),
  ('5950', 'Renata Queiroz Bento'),
  ('5951', 'Renata Queiroz Bento'),
  ('5952', 'Rívia Freire Araujo Barretos Borba'),
  ('5953', 'Renata Queiroz Bento'),
  ('5954', 'Renata Queiroz Bento'),
  ('5955', 'Raquel dos Santos Avelino'),
  ('5956', 'Renata Queiroz Bento'),
  ('5957', 'Renata Queiroz Bento'),
  ('5958', 'Renata Queiroz Bento'),
  ('5959', 'Renata Queiroz Bento'),
  ('5960', 'Renata Queiroz Bento'),
  ('5961', 'Raquel dos Santos Avelino'),
  ('5962', 'Raquel dos Santos Avelino'),
  ('5964', 'Rívia Freire Araujo Barretos Borba'),
  ('5965', 'Rívia Freire Araujo Barretos Borba'),
  ('5966', 'Raquel dos Santos Avelino'),
  ('5969', 'Renata Queiroz Bento'),
  ('5970', 'Renata Queiroz Bento'),
  ('5971', 'Rívia Freire Araujo Barretos Borba'),
  ('5973', 'Renata Queiroz Bento'),
  ('5974', 'Renata Queiroz Bento'),
  ('5978', 'Renata Queiroz Bento'),
  ('5979', 'Renata Queiroz Bento'),
  ('5982', 'Rívia Freire Araujo Barretos Borba'),
  ('5983', 'Rívia Freire Araujo Barretos Borba'),
  ('5984', 'Renata Queiroz Bento'),
  ('5985', 'Renata Queiroz Bento'),
  ('5986', 'Rívia Freire Araujo Barretos Borba'),
  ('5987', 'Renata Queiroz Bento'),
  ('5988', 'Rívia Freire Araujo Barretos Borba'),
  ('5989', 'Rívia Freire Araujo Barretos Borba'),
  ('5991', 'Renata Queiroz Bento'),
  ('5992', 'Renata Queiroz Bento'),
  ('5993', 'Renata Queiroz Bento'),
  ('5994', 'Renata Queiroz Bento'),
  ('5996', 'Renata Queiroz Bento'),
  ('5997', 'Renata Queiroz Bento'),
  ('5998', 'Renata Queiroz Bento'),
  ('6001', 'Renata Queiroz Bento'),
  ('6002', 'Renata Queiroz Bento'),
  ('6003', 'Renata Queiroz Bento'),
  ('6005', 'Renata Queiroz Bento'),
  ('6006', 'Renata Queiroz Bento'),
  ('6008', 'Renata Queiroz Bento'),
  ('6009', 'Renata Queiroz Bento'),
  ('6010', 'Renata Queiroz Bento'),
  ('6011', 'Renata Queiroz Bento'),
  ('6013', 'Renata Queiroz Bento'),
  ('6014', 'Renata Queiroz Bento'),
  ('6015', 'Renata Queiroz Bento'),
  ('6016', 'Renata Queiroz Bento'),
  ('6017', 'Renata Queiroz Bento'),
  ('6018', 'Renata Queiroz Bento'),
  ('6019', 'Rívia Freire Araujo Barretos Borba'),
  ('6021', 'Renata Queiroz Bento'),
  ('6024', 'Renata Queiroz Bento'),
  ('6025', 'Renata Queiroz Bento'),
  ('6026', 'Renata Queiroz Bento'),
  ('6027', 'Renata Queiroz Bento'),
  ('6028', 'Renata Queiroz Bento'),
  ('6029', 'Renata Queiroz Bento'),
  ('6030', 'Rívia Freire Araujo Barretos Borba'),
  ('6031', 'Rívia Freire Araujo Barretos Borba'),
  ('6032', 'Rívia Freire Araujo Barretos Borba'),
  ('6033', 'Renata Queiroz Bento'),
  ('6034', 'Rívia Freire Araujo Barretos Borba'),
  ('6035', 'Rívia Freire Araujo Barretos Borba'),
  ('6036', 'Rívia Freire Araujo Barretos Borba'),
  ('6037', 'Renata Queiroz Bento'),
  ('6038', 'Renata Queiroz Bento'),
  ('6039', 'Renata Queiroz Bento'),
  ('6041', 'Renata Queiroz Bento'),
  ('6046', 'Renata Queiroz Bento'),
  ('6047', 'Renata Queiroz Bento'),
  ('6048', 'Renata Queiroz Bento'),
  ('6050', 'Raquel dos Santos Avelino'),
  ('6053', 'Renata Queiroz Bento'),
  ('6055', 'Renata Queiroz Bento'),
  ('6056', 'Rívia Freire Araujo Barretos Borba'),
  ('6057', 'Rívia Freire Araujo Barretos Borba'),
  ('6058', 'Renata Queiroz Bento'),
  ('6059', 'Renata Queiroz Bento'),
  ('6060', 'Renata Queiroz Bento'),
  ('6061', 'Renata Queiroz Bento'),
  ('6062', 'Rívia Freire Araujo Barretos Borba'),
  ('6063', 'Renata Queiroz Bento'),
  ('6064', 'Renata Queiroz Bento'),
  ('6065', 'Renata Queiroz Bento'),
  ('6066', 'Renata Queiroz Bento'),
  ('6067', 'Rívia Freire Araujo Barretos Borba'),
  ('6068', 'Rívia Freire Araujo Barretos Borba'),
  ('6069', 'Renata Queiroz Bento'),
  ('6070', 'Renata Queiroz Bento'),
  ('6071', 'Rívia Freire Araujo Barretos Borba'),
  ('6072', 'Rívia Freire Araujo Barretos Borba'),
  ('6073', 'Rívia Freire Araujo Barretos Borba'),
  ('6074', 'Renata Queiroz Bento'),
  ('6075', 'Raquel dos Santos Avelino'),
  ('6076', 'Renata Queiroz Bento'),
  ('6078', 'Rívia Freire Araujo Barretos Borba'),
  ('6079', 'Rívia Freire Araujo Barretos Borba'),
  ('6080', 'Renata Queiroz Bento'),
  ('6081', 'Rívia Freire Araujo Barretos Borba'),
  ('6083', 'Renata Queiroz Bento'),
  ('6084', 'Renata Queiroz Bento'),
  ('6087', 'Rívia Freire Araujo Barretos Borba'),
  ('6088', 'Renata Queiroz Bento'),
  ('6089', 'Renata Queiroz Bento'),
  ('6090', 'Rívia Freire Araujo Barretos Borba'),
  ('6091', 'Renata Queiroz Bento'),
  ('6092', 'Rívia Freire Araujo Barretos Borba'),
  ('6094', 'Raquel dos Santos Avelino'),
  ('6095', 'Renata Queiroz Bento'),
  ('6096', 'Renata Queiroz Bento'),
  ('6097', 'Raquel dos Santos Avelino'),
  ('6099', 'Rívia Freire Araujo Barretos Borba'),
  ('6100', 'Rívia Freire Araujo Barretos Borba'),
  ('6101', 'Renata Queiroz Bento'),
  ('6102', 'Rívia Freire Araujo Barretos Borba'),
  ('6103', 'Rívia Freire Araujo Barretos Borba'),
  ('6104', 'Rívia Freire Araujo Barretos Borba'),
  ('6106', 'Rívia Freire Araujo Barretos Borba'),
  ('6107', 'Renata Queiroz Bento'),
  ('6108', 'Renata Queiroz Bento'),
  ('6109', 'Renata Queiroz Bento'),
  ('6111', 'Rívia Freire Araujo Barretos Borba'),
  ('6112', 'Rívia Freire Araujo Barretos Borba'),
  ('6113', 'Rívia Freire Araujo Barretos Borba'),
  ('6114', 'Rívia Freire Araujo Barretos Borba'),
  ('6116', 'Rívia Freire Araujo Barretos Borba'),
  ('6117', 'Renata Queiroz Bento'),
  ('6118', 'Renata Queiroz Bento'),
  ('6119', 'Rívia Freire Araujo Barretos Borba'),
  ('6120', 'Rívia Freire Araujo Barretos Borba'),
  ('6121', 'Rívia Freire Araujo Barretos Borba'),
  ('6122', 'Renata Queiroz Bento'),
  ('6123', 'Rívia Freire Araujo Barretos Borba'),
  ('6124', 'Rívia Freire Araujo Barretos Borba'),
  ('6127', 'Rívia Freire Araujo Barretos Borba'),
  ('6128', 'Rívia Freire Araujo Barretos Borba'),
  ('6131', 'Renata Queiroz Bento'),
  ('6132', 'Renata Queiroz Bento'),
  ('6133', 'Rívia Freire Araujo Barretos Borba'),
  ('6134', 'Rívia Freire Araujo Barretos Borba'),
  ('6135', 'Rívia Freire Araujo Barretos Borba'),
  ('6136', 'Renata Queiroz Bento'),
  ('6137', 'Renata Queiroz Bento'),
  ('6138', 'Rívia Freire Araujo Barretos Borba'),
  ('6139', 'Rívia Freire Araujo Barretos Borba'),
  ('6140', 'Renata Queiroz Bento'),
  ('6141', 'Renata Queiroz Bento'),
  ('6142', 'Renata Queiroz Bento'),
  ('6143', 'Renata Queiroz Bento'),
  ('6144', 'Renata Queiroz Bento'),
  ('6145', 'Renata Queiroz Bento'),
  ('6146', 'Renata Queiroz Bento'),
  ('6147', 'Renata Queiroz Bento'),
  ('6148', 'Renata Queiroz Bento'),
  ('6149', 'Renata Queiroz Bento'),
  ('6151', 'Renata Queiroz Bento'),
  ('6152', 'Rívia Freire Araujo Barretos Borba'),
  ('6153', 'Rívia Freire Araujo Barretos Borba'),
  ('6154', 'Renata Queiroz Bento'),
  ('6155', 'Renata Queiroz Bento'),
  ('6156', 'Rívia Freire Araujo Barretos Borba'),
  ('6157', 'Renata Queiroz Bento'),
  ('6158', 'Renata Queiroz Bento'),
  ('6159', 'Renata Queiroz Bento'),
  ('6160', 'Rívia Freire Araujo Barretos Borba'),
  ('6161', 'Renata Queiroz Bento'),
  ('6162', 'Rívia Freire Araujo Barretos Borba'),
  ('6163', 'Rívia Freire Araujo Barretos Borba'),
  ('6164', 'Renata Queiroz Bento'),
  ('6165', 'Rívia Freire Araujo Barretos Borba'),
  ('6166', 'Renata Queiroz Bento'),
  ('6171', 'Rívia Freire Araujo Barretos Borba'),
  ('6172', 'Renata Queiroz Bento'),
  ('6173', 'Renata Queiroz Bento'),
  ('6174', 'Rívia Freire Araujo Barretos Borba'),
  ('6175', 'Renata Queiroz Bento'),
  ('6177', 'Renata Queiroz Bento'),
  ('6178', 'Renata Queiroz Bento'),
  ('6179', 'Raquel dos Santos Avelino'),
  ('6180', 'Raquel dos Santos Avelino'),
  ('6181', 'Raquel dos Santos Avelino'),
  ('6182', 'Rívia Freire Araujo Barretos Borba'),
  ('6183', 'Rívia Freire Araujo Barretos Borba'),
  ('6184', 'Renata Queiroz Bento'),
  ('6185', 'Renata Queiroz Bento'),
  ('6186', 'Renata Queiroz Bento'),
  ('6187', 'Rívia Freire Araujo Barretos Borba'),
  ('6188', 'Renata Queiroz Bento'),
  ('6189', 'Renata Queiroz Bento'),
  ('6190', 'Renata Queiroz Bento'),
  ('6194', 'Renata Queiroz Bento'),
  ('6196', 'Rívia Freire Araujo Barretos Borba'),
  ('6197', 'Renata Queiroz Bento'),
  ('6198', 'Renata Queiroz Bento'),
  ('6199', 'Renata Queiroz Bento'),
  ('6200', 'Rívia Freire Araujo Barretos Borba'),
  ('6201', 'Renata Queiroz Bento'),
  ('6202', 'Renata Queiroz Bento'),
  ('6204', 'Renata Queiroz Bento'),
  ('6205', 'Renata Queiroz Bento'),
  ('6206', 'Renata Queiroz Bento'),
  ('6207', 'Renata Queiroz Bento'),
  ('6208', 'Renata Queiroz Bento'),
  ('6209', 'Renata Queiroz Bento'),
  ('6210', 'Renata Queiroz Bento'),
  ('6211', 'Renata Queiroz Bento'),
  ('6212', 'Renata Queiroz Bento'),
  ('6215', 'Renata Queiroz Bento'),
  ('6216', 'Renata Queiroz Bento'),
  ('6217', 'Renata Queiroz Bento'),
  ('6219', 'Renata Queiroz Bento'),
  ('6220', 'Rívia Freire Araujo Barretos Borba'),
  ('6221', 'Renata Queiroz Bento'),
  ('6222', 'Rívia Freire Araujo Barretos Borba'),
  ('6223', 'Renata Queiroz Bento'),
  ('6224', 'Rívia Freire Araujo Barretos Borba'),
  ('6227', 'Renata Queiroz Bento'),
  ('6228', 'Renata Queiroz Bento'),
  ('6230', 'Renata Queiroz Bento'),
  ('6231', 'Rívia Freire Araujo Barretos Borba'),
  ('6235', 'Renata Queiroz Bento'),
  ('6236', 'Renata Queiroz Bento'),
  ('6237', 'Renata Queiroz Bento'),
  ('6238', 'Rívia Freire Araujo Barretos Borba'),
  ('6239', 'Renata Queiroz Bento'),
  ('6240', 'Renata Queiroz Bento'),
  ('6241', 'Renata Queiroz Bento'),
  ('6242', 'Renata Queiroz Bento'),
  ('6243', 'Rívia Freire Araujo Barretos Borba'),
  ('6244', 'Renata Queiroz Bento'),
  ('6246', 'Renata Queiroz Bento'),
  ('6247', 'Rívia Freire Araujo Barretos Borba'),
  ('6250', 'Renata Queiroz Bento'),
  ('6252', 'Renata Queiroz Bento'),
  ('6254', 'Raquel dos Santos Avelino'),
  ('6255', 'Renata Queiroz Bento'),
  ('6256', 'Renata Queiroz Bento'),
  ('6257', 'Rívia Freire Araujo Barretos Borba'),
  ('6258', 'Rívia Freire Araujo Barretos Borba'),
  ('6259', 'Renata Queiroz Bento'),
  ('6260', 'Rívia Freire Araujo Barretos Borba'),
  ('6262', 'Rívia Freire Araujo Barretos Borba'),
  ('6263', 'Rívia Freire Araujo Barretos Borba'),
  ('6264', 'Renata Queiroz Bento'),
  ('6266', 'Renata Queiroz Bento'),
  ('6267', 'Renata Queiroz Bento'),
  ('6271', 'Renata Queiroz Bento'),
  ('6272', 'Renata Queiroz Bento'),
  ('6274', 'Renata Queiroz Bento'),
  ('6276', 'Renata Queiroz Bento'),
  ('6277', 'Renata Queiroz Bento'),
  ('6279', 'Rívia Freire Araujo Barretos Borba'),
  ('6280', 'Renata Queiroz Bento'),
  ('6281', 'Renata Queiroz Bento'),
  ('6283', 'Rívia Freire Araujo Barretos Borba'),
  ('6284', 'Renata Queiroz Bento'),
  ('6285', 'Renata Queiroz Bento'),
  ('6286', 'Renata Queiroz Bento'),
  ('6287', 'Renata Queiroz Bento'),
  ('6288', 'Renata Queiroz Bento'),
  ('6289', 'Rívia Freire Araujo Barretos Borba'),
  ('6291', 'Renata Queiroz Bento'),
  ('6292', 'Renata Queiroz Bento'),
  ('6293', 'Renata Queiroz Bento'),
  ('6294', 'Renata Queiroz Bento'),
  ('6295', 'Renata Queiroz Bento'),
  ('6296', 'Renata Queiroz Bento'),
  ('6297', 'Renata Queiroz Bento'),
  ('6298', 'Renata Queiroz Bento'),
  ('6299', 'Renata Queiroz Bento'),
  ('6300', 'Renata Queiroz Bento'),
  ('6301', 'Rívia Freire Araujo Barretos Borba'),
  ('6302', 'Rívia Freire Araujo Barretos Borba'),
  ('6303', 'Rívia Freire Araujo Barretos Borba'),
  ('6304', 'Rívia Freire Araujo Barretos Borba'),
  ('6306', 'Renata Queiroz Bento'),
  ('6307', 'Rívia Freire Araujo Barretos Borba'),
  ('6308', 'Rívia Freire Araujo Barretos Borba'),
  ('6309', 'Rívia Freire Araujo Barretos Borba'),
  ('6310', 'Rívia Freire Araujo Barretos Borba'),
  ('6312', 'Rívia Freire Araujo Barretos Borba'),
  ('6313', 'Rívia Freire Araujo Barretos Borba'),
  ('6314', 'Renata Queiroz Bento'),
  ('6315', 'Rívia Freire Araujo Barretos Borba'),
  ('6316', 'Renata Queiroz Bento'),
  ('6317', 'Renata Queiroz Bento'),
  ('6318', 'Rívia Freire Araujo Barretos Borba'),
  ('6319', 'Rívia Freire Araujo Barretos Borba'),
  ('6320', 'Rívia Freire Araujo Barretos Borba'),
  ('6321', 'Renata Queiroz Bento'),
  ('6322', 'Rívia Freire Araujo Barretos Borba'),
  ('6323', 'Rívia Freire Araujo Barretos Borba'),
  ('6324', 'Renata Queiroz Bento'),
  ('6325', 'Rívia Freire Araujo Barretos Borba'),
  ('6327', 'Renata Queiroz Bento'),
  ('6328', 'Raquel dos Santos Avelino'),
  ('6329', 'Rívia Freire Araujo Barretos Borba'),
  ('6332', 'Raquel dos Santos Avelino'),
  ('6335', 'Renata Queiroz Bento'),
  ('6338', 'Renata Queiroz Bento'),
  ('6339', 'Renata Queiroz Bento'),
  ('6341', 'Rívia Freire Araujo Barretos Borba'),
  ('6342', 'Renata Queiroz Bento'),
  ('6343', 'Rívia Freire Araujo Barretos Borba'),
  ('6349', 'Renata Queiroz Bento'),
  ('6350', 'Renata Queiroz Bento'),
  ('6351', 'Renata Queiroz Bento'),
  ('6352', 'Renata Queiroz Bento'),
  ('6353', 'Rívia Freire Araujo Barretos Borba'),
  ('6354', 'Rívia Freire Araujo Barretos Borba'),
  ('6356', 'Renata Queiroz Bento'),
  ('6358', 'Renata Queiroz Bento'),
  ('6359', 'Renata Queiroz Bento'),
  ('6363', 'Rívia Freire Araujo Barretos Borba'),
  ('6364', 'Renata Queiroz Bento'),
  ('6365', 'Rívia Freire Araujo Barretos Borba'),
  ('6366', 'Renata Queiroz Bento'),
  ('6367', 'Rívia Freire Araujo Barretos Borba'),
  ('6369', 'Rívia Freire Araujo Barretos Borba'),
  ('6374', 'Renata Queiroz Bento'),
  ('6375', 'Rívia Freire Araujo Barretos Borba'),
  ('6377', 'Renata Queiroz Bento'),
  ('6378', 'Renata Queiroz Bento'),
  ('6380', 'Renata Queiroz Bento'),
  ('6381', 'Renata Queiroz Bento'),
  ('6382', 'Renata Queiroz Bento'),
  ('6383', 'Renata Queiroz Bento'),
  ('6384', 'Renata Queiroz Bento'),
  ('6385', 'Renata Queiroz Bento'),
  ('6387', 'Rívia Freire Araujo Barretos Borba'),
  ('6388', 'Raquel dos Santos Avelino'),
  ('6389', 'Rívia Freire Araujo Barretos Borba'),
  ('6390', 'Rívia Freire Araujo Barretos Borba'),
  ('6391', 'Raquel dos Santos Avelino'),
  ('6392', 'Renata Queiroz Bento'),
  ('6393', 'Renata Queiroz Bento'),
  ('6395', 'Rívia Freire Araujo Barretos Borba'),
  ('6397', 'Renata Queiroz Bento'),
  ('6398', 'Renata Queiroz Bento'),
  ('6399', 'Renata Queiroz Bento'),
  ('6400', 'Rívia Freire Araujo Barretos Borba'),
  ('6401', 'Rívia Freire Araujo Barretos Borba'),
  ('6402', 'Renata Queiroz Bento'),
  ('6403', 'Renata Queiroz Bento'),
  ('6404', 'Renata Queiroz Bento'),
  ('6405', 'Rívia Freire Araujo Barretos Borba'),
  ('6406', 'Renata Queiroz Bento'),
  ('6407', 'Renata Queiroz Bento'),
  ('6410', 'Rívia Freire Araujo Barretos Borba'),
  ('6411', 'Rívia Freire Araujo Barretos Borba'),
  ('6413', 'Renata Queiroz Bento'),
  ('6414', 'Renata Queiroz Bento'),
  ('6415', 'Rívia Freire Araujo Barretos Borba'),
  ('6416', 'Rívia Freire Araujo Barretos Borba'),
  ('6417', 'Rívia Freire Araujo Barretos Borba'),
  ('6418', 'Rívia Freire Araujo Barretos Borba'),
  ('6419', 'Renata Queiroz Bento'),
  ('6420', 'Rívia Freire Araujo Barretos Borba'),
  ('6422', 'Rívia Freire Araujo Barretos Borba'),
  ('6423', 'Rívia Freire Araujo Barretos Borba'),
  ('6426', 'Rívia Freire Araujo Barretos Borba'),
  ('6427', 'Renata Queiroz Bento'),
  ('6429', 'Renata Queiroz Bento'),
  ('6430', 'Renata Queiroz Bento'),
  ('6431', 'Renata Queiroz Bento'),
  ('6432', 'Renata Queiroz Bento'),
  ('6434', 'Renata Queiroz Bento'),
  ('6435', 'Rívia Freire Araujo Barretos Borba'),
  ('6436', 'Rívia Freire Araujo Barretos Borba'),
  ('6437', 'Rívia Freire Araujo Barretos Borba'),
  ('6441', 'Renata Queiroz Bento'),
  ('6442', 'Rívia Freire Araujo Barretos Borba'),
  ('6443', 'Renata Queiroz Bento'),
  ('6444', 'Rívia Freire Araujo Barretos Borba'),
  ('6445', 'Rívia Freire Araujo Barretos Borba'),
  ('6446', 'Rívia Freire Araujo Barretos Borba'),
  ('6447', 'Renata Queiroz Bento'),
  ('6450', 'Renata Queiroz Bento'),
  ('6453', 'Rívia Freire Araujo Barretos Borba'),
  ('6454', 'Rívia Freire Araujo Barretos Borba'),
  ('6458', 'Renata Queiroz Bento'),
  ('6459', 'Renata Queiroz Bento'),
  ('6460', 'Renata Queiroz Bento'),
  ('6461', 'Rívia Freire Araujo Barretos Borba'),
  ('6463', 'Rívia Freire Araujo Barretos Borba'),
  ('6464', 'Renata Queiroz Bento'),
  ('6465', 'Renata Queiroz Bento'),
  ('6466', 'Rívia Freire Araujo Barretos Borba'),
  ('6474', 'Renata Queiroz Bento'),
  ('6475', 'Renata Queiroz Bento'),
  ('6476', 'Rívia Freire Araujo Barretos Borba'),
  ('6478', 'Rívia Freire Araujo Barretos Borba'),
  ('6479', 'Renata Queiroz Bento'),
  ('6480', 'Renata Queiroz Bento'),
  ('6481', 'Renata Queiroz Bento'),
  ('6482', 'Rívia Freire Araujo Barretos Borba'),
  ('6483', 'Rívia Freire Araujo Barretos Borba'),
  ('6484', 'Rívia Freire Araujo Barretos Borba'),
  ('6485', 'Rívia Freire Araujo Barretos Borba'),
  ('6486', 'Renata Queiroz Bento'),
  ('6488', 'Renata Queiroz Bento'),
  ('6489', 'Renata Queiroz Bento'),
  ('6490', 'Renata Queiroz Bento'),
  ('6491', 'Renata Queiroz Bento'),
  ('6492', 'Renata Queiroz Bento'),
  ('6493', 'Rívia Freire Araujo Barretos Borba'),
  ('6494', 'Renata Queiroz Bento'),
  ('6495', 'Renata Queiroz Bento'),
  ('6496', 'Renata Queiroz Bento'),
  ('6497', 'Rívia Freire Araujo Barretos Borba'),
  ('6500', 'Rívia Freire Araujo Barretos Borba'),
  ('6501', 'Rívia Freire Araujo Barretos Borba'),
  ('6503', 'Rívia Freire Araujo Barretos Borba'),
  ('6504', 'Renata Queiroz Bento'),
  ('6505', 'Renata Queiroz Bento'),
  ('6506', 'Renata Queiroz Bento'),
  ('6507', 'Renata Queiroz Bento'),
  ('6509', 'Renata Queiroz Bento'),
  ('6511', 'Rívia Freire Araujo Barretos Borba'),
  ('6512', 'Renata Queiroz Bento'),
  ('6513', 'Rívia Freire Araujo Barretos Borba'),
  ('6514', 'Rívia Freire Araujo Barretos Borba'),
  ('6515', 'Renata Queiroz Bento'),
  ('6516', 'Rívia Freire Araujo Barretos Borba'),
  ('6517', 'Renata Queiroz Bento'),
  ('6518', 'Rívia Freire Araujo Barretos Borba'),
  ('6519', 'Rívia Freire Araujo Barretos Borba'),
  ('6520', 'Rívia Freire Araujo Barretos Borba'),
  ('6521', 'Rívia Freire Araujo Barretos Borba'),
  ('6522', 'Rívia Freire Araujo Barretos Borba'),
  ('6523', 'Rívia Freire Araujo Barretos Borba'),
  ('6524', 'Renata Queiroz Bento'),
  ('6525', 'Rívia Freire Araujo Barretos Borba'),
  ('6526', 'Rívia Freire Araujo Barretos Borba'),
  ('6529', 'Renata Queiroz Bento'),
  ('6530', 'Renata Queiroz Bento'),
  ('6531', 'Renata Queiroz Bento'),
  ('6532', 'Renata Queiroz Bento'),
  ('6533', 'Raquel dos Santos Avelino'),
  ('6534', 'Rívia Freire Araujo Barretos Borba'),
  ('6535', 'Renata Queiroz Bento'),
  ('6537', 'Renata Queiroz Bento'),
  ('6538', 'Renata Queiroz Bento'),
  ('6539', 'Renata Queiroz Bento'),
  ('6540', 'Renata Queiroz Bento'),
  ('6542', 'Renata Queiroz Bento'),
  ('6543', 'Renata Queiroz Bento'),
  ('6545', 'Renata Queiroz Bento'),
  ('6546', 'Rívia Freire Araujo Barretos Borba'),
  ('6547', 'Renata Queiroz Bento'),
  ('6548', 'Renata Queiroz Bento'),
  ('6553', 'Renata Queiroz Bento'),
  ('6554', 'Renata Queiroz Bento'),
  ('6556', 'Renata Queiroz Bento'),
  ('6557', 'Renata Queiroz Bento'),
  ('6558', 'Rívia Freire Araujo Barretos Borba'),
  ('6562', 'Raquel dos Santos Avelino'),
  ('6563', 'Rívia Freire Araujo Barretos Borba'),
  ('6565', 'Renata Queiroz Bento'),
  ('6566', 'Rívia Freire Araujo Barretos Borba'),
  ('6567', 'Rívia Freire Araujo Barretos Borba'),
  ('6568', 'Rívia Freire Araujo Barretos Borba'),
  ('6569', 'Renata Queiroz Bento'),
  ('6570', 'Renata Queiroz Bento'),
  ('6571', 'Renata Queiroz Bento'),
  ('6572', 'Renata Queiroz Bento'),
  ('6573', 'Rívia Freire Araujo Barretos Borba'),
  ('6574', 'Raquel dos Santos Avelino'),
  ('6575', 'Renata Queiroz Bento'),
  ('6576', 'Rívia Freire Araujo Barretos Borba'),
  ('6577', 'Renata Queiroz Bento'),
  ('6579', 'Rívia Freire Araujo Barretos Borba'),
  ('6580', 'Rívia Freire Araujo Barretos Borba'),
  ('6581', 'Renata Queiroz Bento'),
  ('6582', 'Rívia Freire Araujo Barretos Borba'),
  ('6583', 'Rívia Freire Araujo Barretos Borba'),
  ('6586', 'Rívia Freire Araujo Barretos Borba'),
  ('6588', 'Renata Queiroz Bento'),
  ('6589', 'Rívia Freire Araujo Barretos Borba'),
  ('6590', 'Renata Queiroz Bento'),
  ('6591', 'Rívia Freire Araujo Barretos Borba'),
  ('6592', 'Renata Queiroz Bento'),
  ('6593', 'Rívia Freire Araujo Barretos Borba'),
  ('6594', 'Rívia Freire Araujo Barretos Borba'),
  ('6595', 'Renata Queiroz Bento'),
  ('6596', 'Rívia Freire Araujo Barretos Borba'),
  ('6597', 'Renata Queiroz Bento'),
  ('6600', 'Rívia Freire Araujo Barretos Borba'),
  ('6601', 'Renata Queiroz Bento'),
  ('6603', 'Renata Queiroz Bento'),
  ('6605', 'Renata Queiroz Bento'),
  ('6606', 'Renata Queiroz Bento'),
  ('6607', 'Renata Queiroz Bento'),
  ('6608', 'Renata Queiroz Bento'),
  ('6609', 'Renata Queiroz Bento'),
  ('6612', 'Renata Queiroz Bento'),
  ('6616', 'Renata Queiroz Bento'),
  ('6617', 'Rívia Freire Araujo Barretos Borba'),
  ('6618', 'Rívia Freire Araujo Barretos Borba'),
  ('6623', 'Rívia Freire Araujo Barretos Borba'),
  ('6624', 'Renata Queiroz Bento'),
  ('6625', 'Rívia Freire Araujo Barretos Borba'),
  ('6626', 'Renata Queiroz Bento'),
  ('6627', 'Rívia Freire Araujo Barretos Borba'),
  ('6628', 'Renata Queiroz Bento'),
  ('6629', 'Renata Queiroz Bento'),
  ('6630', 'Renata Queiroz Bento'),
  ('6631', 'Rívia Freire Araujo Barretos Borba'),
  ('6633', 'Renata Queiroz Bento'),
  ('6634', 'Renata Queiroz Bento'),
  ('6635', 'Renata Queiroz Bento'),
  ('6636', 'Renata Queiroz Bento'),
  ('6638', 'Renata Queiroz Bento'),
  ('6639', 'Rívia Freire Araujo Barretos Borba'),
  ('6640', 'Rívia Freire Araujo Barretos Borba'),
  ('6641', 'Rívia Freire Araujo Barretos Borba'),
  ('6642', 'Rívia Freire Araujo Barretos Borba'),
  ('6643', 'Rívia Freire Araujo Barretos Borba'),
  ('6644', 'Renata Queiroz Bento'),
  ('6645', 'Rívia Freire Araujo Barretos Borba'),
  ('6646', 'Rívia Freire Araujo Barretos Borba'),
  ('6648', 'Rívia Freire Araujo Barretos Borba'),
  ('6649', 'Rívia Freire Araujo Barretos Borba'),
  ('6650', 'Rívia Freire Araujo Barretos Borba'),
  ('6651', 'Rívia Freire Araujo Barretos Borba'),
  ('6652', 'Rívia Freire Araujo Barretos Borba'),
  ('6653', 'Renata Queiroz Bento'),
  ('6656', 'Rívia Freire Araujo Barretos Borba'),
  ('6658', 'Rívia Freire Araujo Barretos Borba'),
  ('6659', 'Rívia Freire Araujo Barretos Borba'),
  ('6660', 'Rívia Freire Araujo Barretos Borba'),
  ('6661', 'Renata Queiroz Bento'),
  ('6662', 'Rívia Freire Araujo Barretos Borba'),
  ('6663', 'Rívia Freire Araujo Barretos Borba'),
  ('6664', 'Rívia Freire Araujo Barretos Borba'),
  ('6665', 'Rívia Freire Araujo Barretos Borba'),
  ('6668', 'Rívia Freire Araujo Barretos Borba'),
  ('6669', 'Rívia Freire Araujo Barretos Borba'),
  ('6670', 'Renata Queiroz Bento'),
  ('6671', 'Renata Queiroz Bento'),
  ('6673', 'Renata Queiroz Bento'),
  ('6674', 'Rívia Freire Araujo Barretos Borba'),
  ('6676', 'Rívia Freire Araujo Barretos Borba'),
  ('6681', 'Rívia Freire Araujo Barretos Borba'),
  ('6682', 'Renata Queiroz Bento'),
  ('6683', 'Renata Queiroz Bento'),
  ('6684', 'Renata Queiroz Bento'),
  ('6685', 'Rívia Freire Araujo Barretos Borba'),
  ('6687', 'Renata Queiroz Bento'),
  ('6688', 'Renata Queiroz Bento'),
  ('6690', 'Renata Queiroz Bento'),
  ('6691', 'Renata Queiroz Bento'),
  ('6692', 'Rívia Freire Araujo Barretos Borba'),
  ('6693', 'Renata Queiroz Bento'),
  ('6696', 'Renata Queiroz Bento'),
  ('6697', 'Renata Queiroz Bento'),
  ('6698', 'Renata Queiroz Bento'),
  ('6700', 'Rívia Freire Araujo Barretos Borba'),
  ('6701', 'Renata Queiroz Bento'),
  ('6702', 'Rívia Freire Araujo Barretos Borba'),
  ('6704', 'Rívia Freire Araujo Barretos Borba'),
  ('6707', 'Renata Queiroz Bento'),
  ('6710', 'Renata Queiroz Bento'),
  ('6711', 'Rívia Freire Araujo Barretos Borba'),
  ('6712', 'Renata Queiroz Bento'),
  ('6713', 'Rívia Freire Araujo Barretos Borba'),
  ('6715', 'Rívia Freire Araujo Barretos Borba'),
  ('6716', 'Renata Queiroz Bento'),
  ('6717', 'Rívia Freire Araujo Barretos Borba'),
  ('6718', 'Renata Queiroz Bento'),
  ('6719', 'Renata Queiroz Bento'),
  ('6720', 'Rívia Freire Araujo Barretos Borba'),
  ('6721', 'Renata Queiroz Bento'),
  ('6722', 'Renata Queiroz Bento'),
  ('6723', 'Rívia Freire Araujo Barretos Borba'),
  ('6724', 'Renata Queiroz Bento'),
  ('6725', 'Rívia Freire Araujo Barretos Borba'),
  ('6726', 'Renata Queiroz Bento'),
  ('6727', 'Rívia Freire Araujo Barretos Borba'),
  ('6728', 'Renata Queiroz Bento'),
  ('6729', 'Rívia Freire Araujo Barretos Borba'),
  ('6731', 'Rívia Freire Araujo Barretos Borba'),
  ('6732', 'Renata Queiroz Bento'),
  ('6735', 'Renata Queiroz Bento'),
  ('6736', 'Rívia Freire Araujo Barretos Borba'),
  ('6737', 'Rívia Freire Araujo Barretos Borba'),
  ('6738', 'Renata Queiroz Bento'),
  ('6740', 'Rívia Freire Araujo Barretos Borba'),
  ('6742', 'Renata Queiroz Bento'),
  ('6745', 'Renata Queiroz Bento'),
  ('6752', 'Renata Queiroz Bento'),
  ('6753', 'Renata Queiroz Bento'),
  ('6754', 'Renata Queiroz Bento'),
  ('6755', 'Renata Queiroz Bento'),
  ('6756', 'Renata Queiroz Bento'),
  ('6757', 'Renata Queiroz Bento'),
  ('6758', 'Renata Queiroz Bento'),
  ('6759', 'Renata Queiroz Bento'),
  ('6760', 'Renata Queiroz Bento'),
  ('6761', 'Renata Queiroz Bento'),
  ('6762', 'Renata Queiroz Bento'),
  ('6763', 'Renata Queiroz Bento'),
  ('6764', 'Renata Queiroz Bento'),
  ('6765', 'Renata Queiroz Bento'),
  ('6766', 'Renata Queiroz Bento'),
  ('6767', 'Renata Queiroz Bento')
  ) AS v(aplis_id, nome)
 WHERE l.aplis_id = v.aplis_id
   AND l.responsavel_fechamento IS NULL;

COMMIT;
