-- ============================================================================
-- Seed de qa_parametros (módulo cancer) e qa_cido_catalogo — módulo Registro
-- de Câncer com CNES e "candidatos" sempre vazios em produção (relatado pelo
-- usuário). Causa raiz: 20260820120000_qualidade_piloto.sql criou as duas
-- tabelas mas nunca as semeou — nenhuma migration deste repositório tem
-- INSERT INTO qa_parametros nem qa_cido_catalogo (confirmado por busca em
-- todo supabase/migrations/).
--
-- ── qa_parametros (módulo cancer) ──────────────────────────────────────────
-- cancer.cnes = '3744221', achado no MySQL de backup do laboratório:
-- fatinstituicao.IdInstituicao = 1 é o próprio laboratório (CNPJ
-- 00.421.800/0001-86, NomFantasia 'LAB - LABORATORIO DE PATOLOGIA E CITOLOGIA
-- APLICADA LTDA', Local = 1, Inativo = 0) — confirmado com o usuário. Os
-- outros 15 campos fixos (Fonte, Município etc.) entram como placeholder vazio
-- só pra existirem (sem a linha, atualizarParametroFixoCancer recusa editar —
-- 'não é possível editar o que não foi criado por migration'); alguém do
-- laboratório preenche o valor real pela tela de Registro de Câncer.
-- ============================================================================

INSERT INTO qa_parametros (chave, modulo, valor) VALUES
  ('cancer.cnes', 'cancer', '"3744221"'::jsonb),
  ('cancer.fonte', 'cancer', '""'::jsonb),
  ('cancer.regiao_administrativa', 'cancer', '""'::jsonb),
  ('cancer.municipio', 'cancer', '""'::jsonb),
  ('cancer.estado', 'cancer', '""'::jsonb),
  ('cancer.naturalidade_fixa', 'cancer', '""'::jsonb),
  ('cancer.nacionalidade_fixa', 'cancer', '""'::jsonb),
  ('cancer.cor_ignorado', 'cancer', '""'::jsonb),
  ('cancer.endereco_codigo', 'cancer', '""'::jsonb),
  ('cancer.profissao_codigo', 'cancer', '""'::jsonb),
  ('cancer.meio_diagnostico', 'cancer', '""'::jsonb),
  ('cancer.extensao', 'cancer', '""'::jsonb),
  ('cancer.caso_raro', 'cancer', '""'::jsonb),
  ('cancer.estado_civil_ignorado', 'cancer', '""'::jsonb),
  ('cancer.escolaridade_ignorado', 'cancer', '""'::jsonb),
  ('cancer.registrador', 'cancer', '""'::jsonb)
ON CONFLICT (chave) DO NOTHING;

-- ── qa_cido_catalogo ────────────────────────────────────────────────────────
-- Fonte: MySQL de backup do laboratório, tabelas diagnostico e topografia —
-- já usadas pelo próprio módulo (bdLabQualidade.ts) pra mapear peça/laudo.
--
-- Morfologia (167 códigos): diagnostico WHERE Positivo = 1 AND
-- CodInternacional LIKE 'M-%' — o prefixo 'M-' + 4 dígitos + comportamento é
-- exatamente CID-O-3 morfologia sem a barra (ex.: M-81403 = CID-O 8140/3),
-- batendo com o que avaliarCandidaturaCancer/extrairCodigoMorfologia
-- (cancerRegras.ts) já esperam. Quando o mesmo código repete em várias
-- linhas (sinônimos de descrição), fica a de menor CodDiagnostico
-- (determinístico, não 'a que o MySQL devolver por último').
--
-- Topografia (1125 códigos): topografia WHERE Inativo = 0 AND
-- CodInternacional casando ^T-[0-9X]{5}$ (370 linhas descartadas por não
-- seguir esse padrão — texto livre/digitação legada, não código). ⚠️ Esse
-- 'T-XXXXX' é o eixo de Topografia do SNOMED (convenção interna do LIS), NÃO
-- o código CID-O-3 de topografia oficial ('CXX.X') que o RHC costuma exigir —
-- decisão explícita do usuário (25/08) de importar assim mesmo pra destravar
-- a função agora; confirmar com quem faz a submissão ao RHC se esse formato
-- é aceito ou se precisa de conversão SNOMED→CID-O antes de exportar. Mesmo
-- dedup por código de menor CodTopografia quando o código repete (a mesma
-- limitação de sinônimo do parágrafo de morfologia se aplica aqui).
-- ============================================================================

INSERT INTO qa_cido_catalogo (codigo, tipo, descricao) VALUES
  ('09450', 'morfologia', 'NEGATIVO PARA INFILTRAÇÃO LINFOMATOSA'),
  ('72210', 'morfologia', 'PSEUDOLINFOMA'),
  ('80006', 'morfologia', 'METÁSTASE'),
  ('80102', 'morfologia', 'CARCINOMA INTRA-EPITELIAL'),
  ('80103', 'morfologia', 'CARCINOMA'),
  ('80106', 'morfologia', 'CARCINOMA FOLICULAR METASTÁTICO'),
  ('80123', 'morfologia', 'CARCINOMA DE GRANDES CÉLULAS'),
  ('80133', 'morfologia', 'CARCINOMA NEUROENDÓCRINO DE GRANDES CÉLULAS'),
  ('80153', 'morfologia', 'CARCINOMA ADENOESCAMOSO, VARIANTE DE CÉLULAS VÍTREAS'),
  ('80203', 'morfologia', 'CARCINOMA INDIFERENCIADO'),
  ('80206', 'morfologia', 'CARCINOMA INDIFERENCIADO METASTÁTICO'),
  ('80213', 'morfologia', 'CARCINOMA ANAPLÁSICO'),
  ('80413', 'morfologia', 'CARCINOMA DE PEQUENAS CÉLULAS'),
  ('80416', 'morfologia', 'CARCINOMA DE PEQUENAS CÉLULAS METASTÁTICO'),
  ('80423', 'morfologia', 'CARCINOMA DE PEQUENAS CÉLULAS COM DIFERENCIAÇÃO NEUROENDÓCRINA'),
  ('80502', 'morfologia', 'MICROCARCINOMA PAPILAR'),
  ('80503', 'morfologia', 'CARCINOMA PAPILÍFERO'),
  ('80506', 'morfologia', 'CARCINOMA PAPILÍFERO METASTÁTICO'),
  ('80513', 'morfologia', 'CARCINOMA VERRUCOSO'),
  ('80702', 'morfologia', 'CARCINOMA DE CÉLULAS ESCAMOSAS IN SITU'),
  ('80703', 'morfologia', 'CARCINOMA DE CÉLULAS ESCAMOSAS'),
  ('80706', 'morfologia', 'CARCINOMA DE CÉLULAS ESCAMOSAS METASTÁTICO'),
  ('80713', 'morfologia', 'CARCINOMA DE CÉLULAS ESCAMOSAS, GRANDES CÉLULAS, TIPO CERATINIZANTE'),
  ('80723', 'morfologia', 'CARCINOMA DE CÉLULAS ESCAMOSAS NÃO QUERATINIZANTE'),
  ('80753', 'morfologia', 'CARCINOMA DE CÉLULAS ESCAMOSAS ACANTOLÍTICO'),
  ('80763', 'morfologia', 'CARCINOMA EPIDERMÓIDE MICROINVASOR.'),
  ('80812', 'morfologia', 'CARCINOMA IN SITU DE PELE (DOENÇA DE BOWEN)'),
  ('80823', 'morfologia', 'CARCINOMA LINFOEPITELIAL'),
  ('80843', 'morfologia', 'CARCINOMA EPIDERMÓIDE DE CÉLULAS CLARAS'),
  ('80903', 'morfologia', 'CARCINOMA BASOCELULAR.'),
  ('80913', 'morfologia', 'CARCINOMA BASOCELULAR, RESIDUAL.'),
  ('80943', 'morfologia', 'TUMOR DE COLISÃO - CARCINOMA EPIDERMOIDE E CARCINOMA BASOCELULAR'),
  ('80953', 'morfologia', 'CARCINOMA METATÍPICO'),
  ('81103', 'morfologia', 'CARCINOMA PILOMATRICAL'),
  ('81203', 'morfologia', 'CARCINOMA DE CÉLULAS TRANSICIONAIS'),
  ('81233', 'morfologia', 'CARCINOMA BASALÓIDE'),
  ('81303', 'morfologia', 'CARCINOMA UROTELIAL IN SITU'),
  ('81402', 'morfologia', 'ADENOCARCINOMA IN SITU (AIS)'),
  ('81403', 'morfologia', 'ADENOCARCINOMA'),
  ('81406', 'morfologia', 'ADENOCARCINOMA METASTÁTICO'),
  ('81443', 'morfologia', 'ADENOCARCINOMA DE PADRÃO INTESTINAL'),
  ('81453', 'morfologia', 'ADENOCARCINOMA DE PADRÃO GÁSTRICO DIFUSO'),
  ('81473', 'morfologia', 'ADENOCARCINOMA DE CÉLULAS BASAIS'),
  ('81603', 'morfologia', 'COLANGIOCARCINOMA'),
  ('81613', 'morfologia', 'CISTADENOCARCINOMA DE DUCTOS BILIARES INTRA-HEPÁTICOS'),
  ('81703', 'morfologia', 'CARCINOMA HEPATOCELULAR'),
  ('82003', 'morfologia', 'CARCINOMA ADENOIDE CÍSTICO'),
  ('82103', 'morfologia', 'ADENOCARCINOMA EM ADENOMA'),
  ('82113', 'morfologia', 'ADENOCARCINOMA TUBULAR'),
  ('82123', 'morfologia', 'CARCINOMA DE CÉLULAS RENAIS (MORFOLOGIA SUGESTIVA DE ASSOCIAÇÃO COM TRANSLOCAÇÃO XP11.2)'),
  ('82401', 'morfologia', 'CARCINOMA NEUROENDÓCRINO BEM DIFERENCIADO'),
  ('82403', 'morfologia', 'CARCINOMA NEUROENDÓCRINO'),
  ('82473', 'morfologia', 'CARCINOMA DE CÉLULAS DE MERKEL'),
  ('82523', 'morfologia', 'CARCINOMA BRONQUÍOLO-ALVEOLAR NÃO-MUCINOSO'),
  ('82603', 'morfologia', 'ADENOCARCINOMA PAPILÍFERO'),
  ('82606', 'morfologia', 'ADENOCARCINOMA PAPILÍFERO METASTÁTICO'),
  ('82613', 'morfologia', 'ADENOCARCINOMA EM ADENOMA VILOSO'),
  ('82623', 'morfologia', 'ADENOCARCINOMA ENDOMETRIÓIDE, VARIANTE VILOGLANDULAR'),
  ('82703', 'morfologia', 'CARCINOMA CROMÓFOBO'),
  ('82903', 'morfologia', 'CARCINOMA ONCOCÍTICO'),
  ('83103', 'morfologia', 'ADENOCARCINOMA DE CÉLULAS CLARAS'),
  ('83106', 'morfologia', 'CARCINOMA DE CÉLULAS CLARAS METASTÁTICO'),
  ('83123', 'morfologia', 'CARCINOMA DE CÉLULAS RENAIS'),
  ('83193', 'morfologia', 'CARCINOMA DOS DUCTOS COLETORES DE BELLINI'),
  ('83233', 'morfologia', 'ADENOCARCINOMA DE TIPO MISTO'),
  ('83303', 'morfologia', 'CARCINOMA FOLICULAR'),
  ('83453', 'morfologia', 'CARCINOMA MEDULAR DA TIREÓIDE'),
  ('83703', 'morfologia', 'CARCINOMA CORTICAL ADRENAL'),
  ('83803', 'morfologia', 'ADENOCARCINOMA ENDOMETRIOIDE'),
  ('83823', 'morfologia', 'ADENOCARCINOMA ENDOMETRIÓIDE, VARIANTE SECRETÓRIA'),
  ('83903', 'morfologia', 'CARCINOMA TRIQUILEMAL'),
  ('84003', 'morfologia', 'HIDRADENOCARCINOMA'),
  ('84093', 'morfologia', 'POROCARCINOMA'),
  ('84103', 'morfologia', 'CARCINOMA SEBÁCEO'),
  ('84303', 'morfologia', 'CARCINOMA MUCOEPIDERMÓIDE'),
  ('84413', 'morfologia', 'ADENOCARCINOMA SEROSO'),
  ('84603', 'morfologia', 'ADENOCARCINOMA SEROSO PAPILÍFERO'),
  ('84613', 'morfologia', 'CARCINOMA SEROSO DE ALTO GRAU'),
  ('84703', 'morfologia', 'CISTADENOCARCINOMA MUCINOSO'),
  ('84803', 'morfologia', 'ADENOCARCINOMA COLÓIDE'),
  ('84903', 'morfologia', 'ADENOCARCINOMA DE CÉLULAS EM ANEL DE SINETE'),
  ('85002', 'morfologia', 'CARCINOMA DUCTAL IN SITU'),
  ('85003', 'morfologia', 'CARCINOMA DE DUCTOS SALIVARES'),
  ('85006', 'morfologia', 'CARCINOMA DUCTAL METASTÁTICO'),
  ('85042', 'morfologia', 'CARCINOMA PAPILÍFERO ENCAPSULADO'),
  ('85073', 'morfologia', 'CARCINOMA MICROPAPILAR INVASIVO'),
  ('85103', 'morfologia', 'CARCINOMA MEDULAR'),
  ('85202', 'morfologia', 'CARCINOMA LOBULAR IN SITU'),
  ('85203', 'morfologia', 'CARCINOMA INVASIVO COM CARACTERÍSTICAS LOBULARES'),
  ('85253', 'morfologia', 'ADENOCARCINOMA POLIMORFO DE BAIXO GRAU'),
  ('85503', 'morfologia', 'CARCINOMA DE CÉLULAS ACINARES'),
  ('85603', 'morfologia', 'CARCINOMA ADENOESCAMOSO'),
  ('85610', 'morfologia', 'CISTADENOMA PAPILAR LINFOMATOSO (TUMOR DE WHARTIN)'),
  ('85623', 'morfologia', 'CARCINOMA EPITELIAL-MIOEPITELIAL'),
  ('87203', 'morfologia', 'MELANOMA IN SITU'),
  ('87206', 'morfologia', 'MELANOMA METASTÁTICO'),
  ('87423', 'morfologia', 'LENTIGO MALIGNO MELANOMA'),
  ('87453', 'morfologia', 'MELANOMA DESMOPLÁSICO'),
  ('88003', 'morfologia', 'SARCOMA'),
  ('88023', 'morfologia', 'SARCOMA FUSOCELULAR E PLEOMÓRFICO DE ALTO GRAU'),
  ('88043', 'morfologia', 'SARCOMA EPITELIÓIDE'),
  ('88053', 'morfologia', 'SARCOMA POUCO DIFERENCIADO'),
  ('88103', 'morfologia', 'FIBROSSARCOMA'),
  ('88113', 'morfologia', 'SARCOMA FIBROBLÁSTICO MIXO-INFLAMATÓRIO'),
  ('88323', 'morfologia', 'DERMATOFIBROSSARCOMA PROTUBERANS'),
  ('88403', 'morfologia', 'MIXOFIBROSSARCOMA'),
  ('88503', 'morfologia', 'LIPOSSARCOMA'),
  ('88513', 'morfologia', 'LIPOSSARCOMA BEM DIFERENCIADO'),
  ('88523', 'morfologia', 'LIPOSSARCOMA MIXÓIDE'),
  ('88903', 'morfologia', 'LEIOMIOSSARCOMA'),
  ('88906', 'morfologia', 'LEIOMIOSSARCOMA METASTÁTICO'),
  ('88913', 'morfologia', 'LEIOMIOSSARCOMA EPITELIÓIDE'),
  ('89003', 'morfologia', 'RABDOMIOSSARCOMA'),
  ('89103', 'morfologia', 'RABDOMIOSSARCOMA EMBRIONÁRIO'),
  ('89123', 'morfologia', 'RABDOMIOSSARCOMA EMBRIONÁRIO, VARIANTE FUSOCELULAR'),
  ('89203', 'morfologia', 'RABDOMIOSSARCOMA ALVEOLAR'),
  ('89303', 'morfologia', 'SARCOMA DO ESTROMA ENDOMETRIAL'),
  ('89313', 'morfologia', 'SARCOMA DO ESTROMA ENDOMETRIAL, DE BAIXO GRAU'),
  ('89333', 'morfologia', 'ADENOSSARCOMA DE BAIXO GRAU'),
  ('89403', 'morfologia', 'CARCINOMA EX ADENOMA PLEOMÓRFICO'),
  ('89603', 'morfologia', 'ADENOSSARCOMA'),
  ('89803', 'morfologia', 'CARCINOMA SARCOMATÓIDE'),
  ('90403', 'morfologia', 'SARCOMA SINOVIAL'),
  ('90433', 'morfologia', 'SARCOMA SINOVIAL, TIPO BIFÁSICO'),
  ('91003', 'morfologia', 'CORIOCARCINOMA'),
  ('91203', 'morfologia', 'ANGIOSSARCOMA'),
  ('91403', 'morfologia', 'PROLIFERAÇÃO VASCULAR ATÍPICA, SUGESTIVA DE SARCOMA DE KAPOSI'),
  ('91803', 'morfologia', 'OSTEOSSARCOMA'),
  ('91813', 'morfologia', 'OSTEOSSARCOMA CONDROBLÁSTICO'),
  ('91823', 'morfologia', 'OSTEOSSARCOMA FIBROBLÁSTICO'),
  ('91833', 'morfologia', 'OSTEOSSARCOMA TELEANGIECTÁSICO'),
  ('91853', 'morfologia', 'OSTEOSSARCOMA DE PEQUENAS CÉLULAS'),
  ('92203', 'morfologia', 'CONDROSSARCOMA'),
  ('92430', 'morfologia', 'CONDROSSARCOMA DESDIFERENCIADO'),
  ('92603', 'morfologia', 'SARCOMA DE EWING'),
  ('93323', 'morfologia', 'LINFOMA DE GRANDES CÉLULAS B, SUBTIPO RICO EM CÉLULAS T E HISTIÓCITOS'),
  ('93803', 'morfologia', 'GLIOSSARCOMA'),
  ('95903', 'morfologia', 'INFILTRAÇÃO MEDULAR POR LINFOMA NÃO HODGKIN'),
  ('95963', 'morfologia', 'LINFOMA DE CÉLULAS B, INCLASSIFICÁVEL, COM CARACTERÍSTICAS INTERMEDIÁRIAS ENTRE LINFOMA DIFUSO DE GRANDES CÉLULAS E LINFOMA DE HODGKIN CLÁSSICO (OMS)'),
  ('96203', 'morfologia', 'LINFOMA NÃO HODGKIN DE BAIXO GRAU, LINFOPLASMOCITÓIDE, TIPO MALT'),
  ('96323', 'morfologia', 'LINFOMA NÃO HODGKIN DIFUSO DE GRANDES CÉLULAS'),
  ('96503', 'morfologia', 'LINFOMA DE HODGKIN'),
  ('96513', 'morfologia', 'LINFOMA DE HODGKIN CLÁSSICO, RICO EM LINFÓCITOS'),
  ('96523', 'morfologia', 'LINFOMA DE HODGKIN CLÁSSICO, CELULARIDADE MISTA'),
  ('96533', 'morfologia', 'LINFOMA DE HODGKIN CLÁSSICO, DEPLEÇÃO LINFOCITÁRIA'),
  ('96593', 'morfologia', 'LINFOMA DE HODGKIN PREDOMINÂNCIA LINFOCÍTICA NODULAR'),
  ('96633', 'morfologia', 'LINFOMA DE HODGKIN CLÁSSICO, ESCLEROSE NODULAR'),
  ('96703', 'morfologia', 'LINFOMA LINFOCÍTICO/LEUCEMIA LINFÓIDE CRÔNICA'),
  ('96733', 'morfologia', 'LINFOMA DE CÉLULAS DO MANTO'),
  ('96803', 'morfologia', 'LINFOMA DE CÉLULAS B, INCLASSIFICÁVEL, COM CARACTERÍSTICAS INTERMEDIÁRIAS ENTRE LINFOMA DIFUSO DE GRANDES CÉLULAS E LINFOMA DE BURKITT (OMS)'),
  ('96873', 'morfologia', 'LINFOMA DE BURKITT'),
  ('96893', 'morfologia', 'LINFOMA DA ZONA MARGINAL ESPLÊNICO'),
  ('96903', 'morfologia', 'LINFOMA FOLICULAR'),
  ('96993', 'morfologia', 'LINFOMA DA ZONA MARGINAL'),
  ('97023', 'morfologia', 'LINFOMA DE CÉLULAS T'),
  ('97053', 'morfologia', 'LINFOMA DE CÉLULAS T ANGIOIMUNOBLÁSTICO'),
  ('97143', 'morfologia', 'LINFOMA ANAPLÁSICO'),
  ('97193', 'morfologia', 'LINFOMA DE CÉLULAS NK/T NASAL'),
  ('97283', 'morfologia', 'LINFOMA/LEUCEMIA LINFOBLÁSTICA DE CÉLULAS B'),
  ('97293', 'morfologia', 'LINFOMA/LEUCEMIA LINFOBLÁSTICA DE CÉLULAS T'),
  ('97793', 'morfologia', 'LINFOMA DE GRANDES CÉLULAS B DO MEDIASTINO'),
  ('98213', 'morfologia', 'LEUCEMIA LINFOBLÁSTICA'),
  ('98233', 'morfologia', 'LEUCEMIA LINFOCÍTICA CRÔNICA'),
  ('98603', 'morfologia', 'LEUCEMIA MIELÓIDE'),
  ('98613', 'morfologia', 'LEUCEMIA MIELÓIDE AGUDA'),
  ('99303', 'morfologia', 'SARCOMA GRANULOCÍTICO'),
  ('99403', 'morfologia', 'TRICOLEUCEMIA'),
  ('T-00000', 'topografia', 'Esvaziamento axilar'),
  ('T-00001', 'topografia', 'Topografia não referida.'),
  ('T-00002', 'topografia', 'Lobo direito da tireóide, (n1)'),
  ('T-00003', 'topografia', 'Topografia designada ilegível'),
  ('T-00008', 'topografia', 'Epiderme + lesão + margens'),
  ('T-00010', 'topografia', 'Corpo como um todo'),
  ('T-00020', 'topografia', 'Topografia múltipla'),
  ('T-00040', 'topografia', 'Material citológico'),
  ('T-00049', 'topografia', 'Material citológico de punção biópsia aspirativa'),
  ('T-00100', 'topografia', 'Margem brônquica'),
  ('T-00101', 'topografia', 'Margem cirúrgica proximal'),
  ('T-00102', 'topografia', 'Margem cirúrgica distal'),
  ('T-00300', 'topografia', 'Margem vasos hilares'),
  ('T-00600', 'topografia', 'Neoplasia de sítio primário desconhecido'),
  ('T-01000', 'topografia', 'Pele (soe)'),
  ('T-01030', 'topografia', 'Pele e tecido subcutâneo (SOE)'),
  ('T-01050', 'topografia', 'Capilar sanguíneo da pele'),
  ('T-01140', 'topografia', 'Mucosa escamosa'),
  ('T-01200', 'topografia', 'Derme'),
  ('T-01211', 'topografia', 'Junção dos quadrantes laterais da mama direita'),
  ('T-01300', 'topografia', 'Anexo cutâneo'),
  ('T-01332', 'topografia', 'Ducto ejaculatório'),
  ('T-01400', 'topografia', 'Cabelo'),
  ('T-01412', 'topografia', 'Cabelo, córtex'),
  ('T-01422', 'topografia', 'Folículo piloso telógeno'),
  ('T-01520', 'topografia', 'Sobrancelha'),
  ('T-01570', 'topografia', 'Pelos do tronco'),
  ('T-01600', 'topografia', 'Unha'),
  ('T-01607', 'topografia', 'Raíz da unha'),
  ('T-01609', 'topografia', 'Leito ungueal'),
  ('T-01614', 'topografia', 'Unha do pé'),
  ('T-01618', 'topografia', 'Unha do quarto dedo da mão'),
  ('T-02102', 'topografia', 'Pele (couro cabeludo)'),
  ('T-02104', 'topografia', 'Pele da região frontal'),
  ('T-02105', 'topografia', 'Pele da região supraorbital'),
  ('T-02106', 'topografia', 'Pele da região frontal à direita'),
  ('T-02108', 'topografia', 'Pele (parietal, SOE)'),
  ('T-02109', 'topografia', 'Pele da região occipital'),
  ('T-02111', 'topografia', 'Pele da região temporal'),
  ('T-02113', 'topografia', 'Pele da região retroauricular'),
  ('T-02114', 'topografia', 'Pele da região pré-auricular'),
  ('T-02115', 'topografia', 'Pele da face do couro cabeludo'),
  ('T-02120', 'topografia', 'Pele (face)'),
  ('T-02123', 'topografia', 'Pele da região zigomática'),
  ('T-02130', 'topografia', 'Pele da pálpebra'),
  ('T-02131', 'topografia', 'Pele da pálpebra superior'),
  ('T-02132', 'topografia', 'Pele da pálpebra inferior'),
  ('T-02133', 'topografia', 'Pele da região orbitária'),
  ('T-02140', 'topografia', 'Pele do nariz'),
  ('T-02141', 'topografia', 'Pele da região nasogeniana'),
  ('T-02142', 'topografia', 'Pele do nariz, asa nasal direita'),
  ('T-02143', 'topografia', 'Pele da ponta nasal'),
  ('T-02145', 'topografia', 'Pele do septo nasal'),
  ('T-02150', 'topografia', 'Pele do lábio'),
  ('T-02151', 'topografia', 'Pele do lábio superior'),
  ('T-02155', 'topografia', 'Pele da região mentoniana'),
  ('T-02156', 'topografia', 'Pele da região submentoniana'),
  ('T-02158', 'topografia', 'Pele da região mandibular'),
  ('T-02202', 'topografia', 'Pele da orelha'),
  ('T-02206', 'topografia', 'Pele da hélix auricular'),
  ('T-02211', 'topografia', 'Pele do tragus'),
  ('T-02214', 'topografia', 'Pele da orelha direita'),
  ('T-02217', 'topografia', 'Pele da concha auricular'),
  ('T-02219', 'topografia', 'Pele do conduto auditivo externo'),
  ('T-02300', 'topografia', 'Pele da região cervical'),
  ('T-02302', 'topografia', 'Pele (região cervical anterior, soe)'),
  ('T-02303', 'topografia', 'Pele da região submandibular'),
  ('T-02305', 'topografia', 'Pele da região cervical posterior'),
  ('T-02306', 'topografia', 'Pele da região supraclavicular direita'),
  ('T-02330', 'topografia', 'Perna, anterior'),
  ('T-02390', 'topografia', 'Pele da cabeça e pescoço'),
  ('T-02400', 'topografia', 'Pele da região esternal'),
  ('T-02402', 'topografia', 'Pele da região torácica inferior'),
  ('T-02410', 'topografia', 'Pele da região infra-escapular direita'),
  ('T-02411', 'topografia', 'Pele da região escapular'),
  ('T-02413', 'topografia', 'Pele da região clavicular'),
  ('T-02414', 'topografia', 'Pele da região infra-escapular'),
  ('T-02420', 'topografia', 'Pele da axila'),
  ('T-02424', 'topografia', 'Pele da região peitoral'),
  ('T-02430', 'topografia', 'Pele da mama'),
  ('T-02431', 'topografia', 'Pele do mamilo'),
  ('T-02450', 'topografia', 'Pele da região dorsal'),
  ('T-02451', 'topografia', 'Pele da região dorsal superior'),
  ('T-02452', 'topografia', 'Pele da região dorsal inferior'),
  ('T-02453', 'topografia', 'Pele da região paravertebral'),
  ('T-02460', 'topografia', 'Pele do flanco'),
  ('T-02461', 'topografia', 'Pele da região lombar'),
  ('T-02462', 'topografia', 'Pele da região sacrococcígea'),
  ('T-02463', 'topografia', 'Pele da região sacral'),
  ('T-02470', 'topografia', 'Pele do quadril'),
  ('T-02471', 'topografia', 'Pele da região glútea'),
  ('T-02480', 'topografia', 'Pele (abdome)'),
  ('T-02481', 'topografia', 'Pele da região epigástrica'),
  ('T-02482', 'topografia', 'Pele do hipocôndrio direito'),
  ('T-02483', 'topografia', 'Pele do umbigo'),
  ('T-02484', 'topografia', 'Pele da região umbilical'),
  ('T-02486', 'topografia', 'Pele da região supra-púbica'),
  ('T-02487', 'topografia', 'Pele da região inguinal'),
  ('T-02500', 'topografia', 'Pele do períneo'),
  ('T-02502', 'topografia', 'Pele da região pélvica'),
  ('T-02503', 'topografia', 'Pele da região pubiana'),
  ('T-02504', 'topografia', 'Pele da região infra-púbica'),
  ('T-02505', 'topografia', 'Pele da prega coxo-escrotal'),
  ('T-02506', 'topografia', 'Pele da região glútea direita'),
  ('T-02507', 'topografia', 'Pele da região perianal'),
  ('T-02530', 'topografia', 'Pele (pênis)'),
  ('T-02545', 'topografia', 'Pele da bolsa escrotal'),
  ('T-02600', 'topografia', 'Pele do membro superior'),
  ('T-02611', 'topografia', 'Pele da região deltóide'),
  ('T-02616', 'topografia', 'Pele do braço'),
  ('T-02621', 'topografia', 'Pele da fossa antecubital'),
  ('T-02630', 'topografia', 'Pele do antebraço'),
  ('T-02640', 'topografia', 'Pele do punho'),
  ('T-02641', 'topografia', 'Pele do punho direito'),
  ('T-02642', 'topografia', 'Pele do punho esquerdo'),
  ('T-02650', 'topografia', 'Pele da mão'),
  ('T-02652', 'topografia', 'Pele da palma da mão direita'),
  ('T-02660', 'topografia', 'Pele da mão do dedo'),
  ('T-02670', 'topografia', 'Pele do dedo da mão'),
  ('T-02690', 'topografia', 'Pele do segundo quirodáctilo direito'),
  ('T-02700', 'topografia', 'Pele do terceiro quirodáctilo'),
  ('T-02710', 'topografia', 'Pele do quarto quirodáctilo'),
  ('T-02810', 'topografia', 'Pele (coxa, soe)'),
  ('T-02820', 'topografia', 'Pele do joelho'),
  ('T-02821', 'topografia', 'Pele da fossa poplitea'),
  ('T-02823', 'topografia', 'Pele do membro inferior'),
  ('T-02830', 'topografia', 'Pele da perna'),
  ('T-02836', 'topografia', 'Panturrilha'),
  ('T-02840', 'topografia', 'Pele do tornozelo'),
  ('T-02850', 'topografia', 'Pele do calcanhar'),
  ('T-02851', 'topografia', 'Pele do dorso do pé esquerdo'),
  ('T-02852', 'topografia', 'Pele da planta do pé'),
  ('T-02862', 'topografia', 'Pele da região plantar'),
  ('T-02870', 'topografia', 'Pele do dedo do pé'),
  ('T-02880', 'topografia', 'Pele do hálux'),
  ('T-02890', 'topografia', 'Pele do segundo pododáctilo'),
  ('T-02900', 'topografia', 'Pele do terceiro pododáctilo'),
  ('T-02901', 'topografia', 'Pele do terceiro pododáctilo direito, superfície dorsal'),
  ('T-02902', 'topografia', 'Pele do terceiro pododáctilo direito, superfície plantar'),
  ('T-02910', 'topografia', 'Pele do quarto pododáctilo'),
  ('T-02920', 'topografia', 'Pele do quinto pdodáctilo'),
  ('T-02921', 'topografia', 'Pele do quinto pododáctilo direito, superfície dorsal'),
  ('T-03000', 'topografia', 'Tecido subcutâneo'),
  ('T-03100', 'topografia', 'Tecido subcutâneo da cabeça'),
  ('T-03106', 'topografia', 'Tecido subcutâneo da região frontal'),
  ('T-03109', 'topografia', 'Tecido subcutâneo da região occipital'),
  ('T-03111', 'topografia', 'Tecido subcutâneo da região temporal'),
  ('T-03120', 'topografia', 'Tecido subcutâneo da face'),
  ('T-03140', 'topografia', 'Tecido subcutâneo do nariz'),
  ('T-03142', 'topografia', 'Tecido subcutâneo da asa nasal'),
  ('T-03300', 'topografia', 'Tecido subcutâneo da região cervical'),
  ('T-03303', 'topografia', 'Tecido subcutâneo de região submandibular'),
  ('T-03400', 'topografia', 'Tecido subcutâneo do tórax'),
  ('T-03410', 'topografia', 'Tecido subcutâneo da região supra-escapular direita'),
  ('T-03413', 'topografia', 'Tecido subcutâneo da região clavicular'),
  ('T-03414', 'topografia', 'Tecido subcutâneo da região subclavicular'),
  ('T-03420', 'topografia', 'Tecido subcutâneo de axila'),
  ('T-03421', 'topografia', 'Tecido adiposo da fossa axilar'),
  ('T-03424', 'topografia', 'Tecido subcutâneo do tórax anterior'),
  ('T-03450', 'topografia', 'Região interescapular'),
  ('T-03452', 'topografia', 'Tecido subcutâneo da região lombar'),
  ('T-03460', 'topografia', 'Tecido subcutâneo do flanco direito'),
  ('T-03463', 'topografia', 'Tecido subcutâneo da região sacral'),
  ('T-03471', 'topografia', 'Tecido subcutâneo da região glútea'),
  ('T-03480', 'topografia', 'Tecido subcutâneo abdominal'),
  ('T-03487', 'topografia', 'Tecido subcutâneo da região inguinal'),
  ('T-03502', 'topografia', 'Tecido subcutâneo da pelve'),
  ('T-03520', 'topografia', 'Lábio, tecido subcutâneo'),
  ('T-03530', 'topografia', 'Tecido subcutâneo do pênis'),
  ('T-03616', 'topografia', 'Tecido subcutâneo do braço'),
  ('T-03621', 'topografia', 'Tecido subcutâneo da fossa antecubital'),
  ('T-03630', 'topografia', 'Tecido subcutâneo do antebraço'),
  ('T-03650', 'topografia', 'Tecido subcutâneo da mão'),
  ('T-03652', 'topografia', 'Tecido subcutâneo da região palmar da mão'),
  ('T-03790', 'topografia', 'Tecido subcutâneo do dedo da mão'),
  ('T-03810', 'topografia', 'Tecido subcutâneo da coxa'),
  ('T-03830', 'topografia', 'Tecido subcutâneo da perna, soe'),
  ('T-03860', 'topografia', 'Tecido subcutâneo do pé'),
  ('T-04000', 'topografia', 'Mama (soe)'),
  ('T-04001', 'topografia', 'Margem central da mama'),
  ('T-04003', 'topografia', 'Quadrante ínfero-medial da mama'),
  ('T-04004', 'topografia', 'Quadrante súpero-lateral da mama '),
  ('T-04005', 'topografia', 'Quadrante ínfero-lateral da mama'),
  ('T-04010', 'topografia', 'Intersecção dos quadrantes inferiores da mama direita'),
  ('T-04012', 'topografia', 'Quadrante súpero-medial da mama feminina'),
  ('T-04013', 'topografia', 'Quadrante ínfero-medial da mama '),
  ('T-04014', 'topografia', 'Quadrante súpero-lateral da mama feminina'),
  ('T-04015', 'topografia', 'Quadrante ínfero-lateral da mama'),
  ('T-04020', 'topografia', 'Mama direita (soe)'),
  ('T-04022', 'topografia', 'Quadrante súpero-medial da mama direita'),
  ('T-04023', 'topografia', 'Quadrante ínfero-medial da mama direita'),
  ('T-04025', 'topografia', 'Quadrante ínfero-lateral da mama direita'),
  ('T-04030', 'topografia', 'Mama esquerda (soe)'),
  ('T-04032', 'topografia', 'Quadrante súpero-medial da mama esquerda'),
  ('T-04033', 'topografia', 'Quadrante ínfero-medial da mama esquerda'),
  ('T-04034', 'topografia', 'Quadrante súpero-lateral da mama esquerda'),
  ('T-04035', 'topografia', 'Quadrante ínfero-lateral da mama esquerda'),
  ('T-04040', 'topografia', 'Mama masculina'),
  ('T-04050', 'topografia', 'Mama masculina direita'),
  ('T-04060', 'topografia', 'Mama masculina esquerda'),
  ('T-04100', 'topografia', 'Ductos intrapapilares de mama direita'),
  ('T-04200', 'topografia', 'Aréola'),
  ('T-04280', 'topografia', 'Prolongamento axilar da mama direita'),
  ('T-04410', 'topografia', 'Ácino mamário'),
  ('T-04800', 'topografia', 'Mamas, ambas'),
  ('T-04810', 'topografia', 'Mama, ambas'),
  ('T-04925', 'topografia', 'Mama direita com tecido axilar'),
  ('T-04935', 'topografia', 'Mama esquerda com tecido axilar'),
  ('T-05220', 'topografia', 'Prolinfócito'),
  ('T-06000', 'topografia', 'Material citológico de medula óssea'),
  ('T-06002', 'topografia', 'Medula óssea, crista ilíaca'),
  ('T-06120', 'topografia', 'Próeritroblasto'),
  ('T-06218', 'topografia', 'Promielócito'),
  ('T-06520', 'topografia', 'Promegacariócito'),
  ('T-06720', 'topografia', 'Promonócito'),
  ('T-06820', 'topografia', 'Promielomonócito'),
  ('T-07000', 'topografia', 'Baço'),
  ('T-07001', 'topografia', 'Baço, face diafragmática'),
  ('T-07002', 'topografia', 'Superfície visceral do baço'),
  ('T-07010', 'topografia', 'Cápsula esplênica'),
  ('T-07012', 'topografia', 'Cápsula esplênica'),
  ('T-07030', 'topografia', 'Corpúsculo malpiguiano'),
  ('T-08000', 'topografia', 'Linfonodo'),
  ('T-08010', 'topografia', 'Cápsula linfonodal'),
  ('T-08100', 'topografia', 'Linfonodo da cabeça'),
  ('t-08130', 'topografia', 'Antro e corpo gástrico'),
  ('T-08160', 'topografia', 'Linfonodo submandibular'),
  ('T-08190', 'topografia', 'Linfonodo sub-maxilar'),
  ('T-08200', 'topografia', 'Linfonodos cervicais à direita,nível i'),
  ('T-08220', 'topografia', 'Linfonodos  supraclaviculares'),
  ('T-08230', 'topografia', 'Linfonodo jugular'),
  ('T-08270', 'topografia', 'Linfonodo pré-traqueal'),
  ('T-08280', 'topografia', 'Linfonodo supraclavicular'),
  ('T-08300', 'topografia', 'Linfonodo do tórax'),
  ('T-08310', 'topografia', 'Linfonodo pulmonar'),
  ('T-08320', 'topografia', 'Linfonodo bronco-pulmonar'),
  ('T-08330', 'topografia', 'Linfonodo bronquinal'),
  ('T-08340', 'topografia', 'Linfonodo paratraqueal'),
  ('T-08350', 'topografia', 'Cadeia mamária interna'),
  ('T-08360', 'topografia', 'Linfonodo do mediastino'),
  ('T-08365', 'topografia', 'Linfonodos peri-esofágicos'),
  ('T-08400', 'topografia', 'Linfonodo abdominal'),
  ('T-08410', 'topografia', 'Linfonodo celíaco'),
  ('T-08430', 'topografia', 'Linfonodo da mesentérica inferior'),
  ('T-08440', 'topografia', 'Linfonodo da artéria hepática'),
  ('T-08450', 'topografia', 'Linfonodos peri-cárdicos à direita (cadeia 1)'),
  ('T-08454', 'topografia', 'Linfonodos da pequena curvatura do estômago'),
  ('T-08456', 'topografia', 'Linfonodos da grande curvatura do estômago'),
  ('T-08458', 'topografia', 'Linfonodos do tecido pericólico'),
  ('T-08460', 'topografia', 'Linfonodos infra-pilóricos'),
  ('T-08472', 'topografia', 'Linfonodo esplênico'),
  ('T-08474', 'topografia', 'Linfonodos peri-pancreáticos'),
  ('T-08480', 'topografia', 'Linfonodo para-aórtico'),
  ('T-08500', 'topografia', 'Linfonodo intestinal'),
  ('T-08510', 'topografia', 'Linfonodo mesentérico'),
  ('T-08580', 'topografia', 'Linfonodo retroperitoneal'),
  ('T-08600', 'topografia', 'Linfonodo da pelve'),
  ('T-08610', 'topografia', 'Linfonodo ilíaco'),
  ('T-08640', 'topografia', 'Linfonodo obturador'),
  ('T-08650', 'topografia', 'Linfonodo sacral'),
  ('T-08710', 'topografia', 'Linfonodo sentinela'),
  ('T-08750', 'topografia', 'Cadeia de rotter'),
  ('T-08760', 'topografia', 'Linfonodo sub-escapular'),
  ('T-08810', 'topografia', 'Linfonodo inguinal'),
  ('T-08820', 'topografia', 'Linfonodo inguinal profundo'),
  ('T-08860', 'topografia', 'Linfonodo tibial anterior'),
  ('T-08900', 'topografia', 'Linfonodos, locais múltiplos'),
  ('T-09160', 'topografia', 'Vaso linfático da cavidade nasal'),
  ('T-09900', 'topografia', 'Tecido peri-linfático'),
  ('T-0X002', 'topografia', 'Capilar sanguíneo'),
  ('T-0X003', 'topografia', 'Sangue venoso'),
  ('T-0X400', 'topografia', 'Plasma'),
  ('T-10101', 'topografia', 'Clivus'),
  ('T-10106', 'topografia', 'Forame magno'),
  ('T-10110', 'topografia', 'Osso (frontal)'),
  ('T-10113', 'topografia', 'Glabela'),
  ('T-10118', 'topografia', 'Processo zigomático'),
  ('T-10122', 'topografia', 'Região mastóide'),
  ('T-10137', 'topografia', 'Processo estilóide'),
  ('T-10166', 'topografia', 'Osso da órbita'),
  ('T-10170', 'topografia', 'Maxila'),
  ('T-10172', 'topografia', 'Maxila, margem infra-orbitária'),
  ('T-10177', 'topografia', 'Maxila, processo alveolar'),
  ('T-10178', 'topografia', 'Maxila, arco alveolar'),
  ('T-10179', 'topografia', 'Alvéolo dentário maxilar'),
  ('T-10180', 'topografia', 'Mandíbula'),
  ('T-10182', 'topografia', 'Mandíbula, arco alveolar'),
  ('T-10183', 'topografia', 'Alvéolo dentário mandibular'),
  ('T-10185', 'topografia', 'Côndilo mandibular'),
  ('T-10310', 'topografia', 'Esterno'),
  ('T-10319', 'topografia', 'Linfonodo infraclavicular'),
  ('T-10327', 'topografia', 'Apêndice xifóide do esterno'),
  ('T-10350', 'topografia', 'Costela'),
  ('T-10500', 'topografia', 'Coluna vertebral'),
  ('T-10510', 'topografia', 'Vértebra'),
  ('T-10517', 'topografia', 'Corpo vertebral'),
  ('T-10518', 'topografia', 'Foramen intervertebral'),
  ('T-10595', 'topografia', 'Vértebra cervical'),
  ('T-10600', 'topografia', 'Vértebra torácica'),
  ('T-10609', 'topografia', 'Vértebra tóracica, foramen inter-vertebral'),
  ('T-10610', 'topografia', 'Primeira vértebra torácica'),
  ('T-10620', 'topografia', 'Segunda vértebra torácica'),
  ('T-10640', 'topografia', 'Quarta vértebra torácica'),
  ('T-10650', 'topografia', 'Quinta vértebra torácica'),
  ('T-10660', 'topografia', 'Sexta vértebra torácica'),
  ('T-10670', 'topografia', 'Sétima vértebra torácica'),
  ('T-10680', 'topografia', 'Oitava vértebra torácica'),
  ('T-10690', 'topografia', 'Nona vértebra torácica'),
  ('T-10710', 'topografia', 'Décima-primeira vértebra torácica'),
  ('T-10730', 'topografia', 'Vértebras torácicas, todas'),
  ('T-10740', 'topografia', 'Vértebra lombar'),
  ('T-10745', 'topografia', 'Pedículo da vertebra lombar'),
  ('T-10749', 'topografia', 'Foramen intervertebral de vértebra lombar'),
  ('T-10801', 'topografia', 'Primeira vértebra sacral'),
  ('T-10802', 'topografia', 'Segunda vértebra sacral'),
  ('T-10803', 'topografia', 'Terceira vértebra sacral'),
  ('T-10804', 'topografia', 'Quarta vértebra sacral'),
  ('T-10805', 'topografia', 'Quinta vértebra sacral'),
  ('T-10806', 'topografia', 'Vértebra sacral'),
  ('T-10808', 'topografia', 'Promontório sacral'),
  ('T-10830', 'topografia', 'Cóccix'),
  ('T-10940', 'topografia', 'Medula espinhal sacro-coccígea'),
  ('T-11280', 'topografia', 'Escápula'),
  ('T-11281', 'topografia', 'Acrômio'),
  ('T-11290', 'topografia', 'Glenóide'),
  ('T-11310', 'topografia', 'Clavícula'),
  ('T-11339', 'topografia', 'Crista ilíaca'),
  ('T-11340', 'topografia', 'Osso ilíaco'),
  ('T-11350', 'topografia', 'Ísquio'),
  ('T-11363', 'topografia', 'Osso pubiano'),
  ('T-11380', 'topografia', 'Ossos da pelve'),
  ('T-11390', 'topografia', 'Acetábulo'),
  ('T-11394', 'topografia', 'Superfície articular do acetábulo'),
  ('T-11410', 'topografia', 'Úmero'),
  ('T-11420', 'topografia', 'Rádio'),
  ('T-11430', 'topografia', 'Radio e ulna'),
  ('T-11431', 'topografia', 'Olécrano'),
  ('T-11500', 'topografia', 'Osso da mão'),
  ('T-11570', 'topografia', 'Terceiro metacarpo'),
  ('T-11590', 'topografia', 'Quinto metacarpo esquerdo'),
  ('T-11610', 'topografia', 'Falange da mão'),
  ('T-11620', 'topografia', 'Falange do primeiro pododáctilo'),
  ('T-11640', 'topografia', 'Falange do terceiro dedo da mão'),
  ('T-11701', 'topografia', 'Osso do tornozelo'),
  ('T-11710', 'topografia', 'Fêmur'),
  ('T-11711', 'topografia', 'Cabeça do fêmur'),
  ('T-11712', 'topografia', 'Colo do fêmur'),
  ('T-11720', 'topografia', 'Patela'),
  ('T-11730', 'topografia', 'Tíbia'),
  ('T-11740', 'topografia', 'Fíbula'),
  ('T-11755', 'topografia', 'Osso do pé'),
  ('T-11760', 'topografia', 'Calcâneo'),
  ('T-11770', 'topografia', 'Osso, talus'),
  ('T-11779', 'topografia', 'Osso, talus, tubérculo posterior'),
  ('T-11860', 'topografia', 'Segundo metatarso'),
  ('T-11870', 'topografia', 'Terceiro metatarso'),
  ('T-11940', 'topografia', 'Falange do terceiro dedo do pé'),
  ('T-12000', 'topografia', 'Articulação'),
  ('T-12013', 'topografia', 'Menisco'),
  ('T-12020', 'topografia', 'Cápsula articular'),
  ('T-12040', 'topografia', 'Sinóvia'),
  ('T-12070', 'topografia', 'Vilo sinovial'),
  ('T-12081', 'topografia', 'Sindesmose'),
  ('T-12082', 'topografia', 'Sutura do crânio'),
  ('T-12092', 'topografia', 'Sínfise'),
  ('T-12103', 'topografia', 'Disco intervertebral'),
  ('T-12104', 'topografia', 'Disco intervertebral, anel fibroso'),
  ('T-12105', 'topografia', 'Disco intervetebral, núcleo pulposo'),
  ('T-12292', 'topografia', 'Articulação têmporo-mandibular'),
  ('T-12333', 'topografia', 'Disco intervertebral de vértebra torácica, núcleo pulposo'),
  ('T-12343', 'topografia', 'Disco intervertebral de vértebra lombar, núcleo pulposo'),
  ('T-12350', 'topografia', 'Articulação lombo-sacra'),
  ('T-12420', 'topografia', 'Articulação acrômiio-clavicular'),
  ('T-12421', 'topografia', 'Cápsula de articulação acrômio-clavicular'),
  ('T-12430', 'topografia', 'Articulação do cotovelo'),
  ('T-12472', 'topografia', 'Menisco da articulação rádio-ulnar distal'),
  ('T-12515', 'topografia', 'Articulação da mão'),
  ('T-12520', 'topografia', 'Articulação carpo-metacarpo'),
  ('T-12530', 'topografia', 'Articulação metacarpo-falangeana'),
  ('T-12531', 'topografia', 'Cápsula da articulação metacarpo-falangeana'),
  ('T-12540', 'topografia', 'Articulação metacarpo-falangeana do polegar'),
  ('T-12612', 'topografia', 'Menisco da articulação esterno-clavicular'),
  ('T-12620', 'topografia', 'Sincrondose esternal'),
  ('T-12710', 'topografia', 'Articulação coxo-femural direita'),
  ('T-12711', 'topografia', 'Cápsula articular dio quadril'),
  ('T-12720', 'topografia', 'Articulação do joelho'),
  ('T-12721', 'topografia', 'Cápsula articular do joelho'),
  ('T-12722', 'topografia', 'Menisco do joelho'),
  ('T-12723', 'topografia', 'Menisco do joelho, lateral'),
  ('T-12724', 'topografia', 'Menisco do joelho, medial'),
  ('T-12725', 'topografia', 'Prega sinovial infra-patelar'),
  ('T-12750', 'topografia', 'Articulação do tornozelo'),
  ('T-12751', 'topografia', 'Cápsula articular do tornozelo'),
  ('T-12810', 'topografia', 'Articulação do metatarso'),
  ('T-13001', 'topografia', 'Músculo'),
  ('T-13100', 'topografia', 'Músculo da cabeça'),
  ('T-13153', 'topografia', 'Músculo zigomático maior'),
  ('T-13154', 'topografia', 'Múculo zigomático menor'),
  ('T-13159', 'topografia', 'Músculo bucinador direito'),
  ('T-13170', 'topografia', 'Músculo ocular extrínseco'),
  ('T-13270', 'topografia', 'Músculo temporal'),
  ('T-13300', 'topografia', 'Músculo do pescoço'),
  ('T-13310', 'topografia', 'Músculo esternocleidomastóideo'),
  ('T-13320', 'topografia', 'Músculo supra-hióide'),
  ('T-13330', 'topografia', 'Músculo digástrico'),
  ('T-13600', 'topografia', 'Músculo de extremidade superior'),
  ('T-13660', 'topografia', 'Músculo deltóide'),
  ('T-13670', 'topografia', 'Músculo bíceps branquial'),
  ('T-13690', 'topografia', 'Músculo tríceps braquial'),
  ('T-13750', 'topografia', 'Músculo flexor do carpo radial'),
  ('T-13830', 'topografia', 'Músculo extensor do carpo radial'),
  ('T-13850', 'topografia', 'Músculo extensor do carpo ulnar'),
  ('T-13980', 'topografia', 'Músculos inter-ósseos da mão'),
  ('T-14000', 'topografia', 'Serosa'),
  ('T-14110', 'topografia', 'Músculo peitoral maior'),
  ('T-14166', 'topografia', 'Músculo sub-costal'),
  ('T-14167', 'topografia', 'Músculo transverso torácico'),
  ('T-14171', 'topografia', 'Músculo trapézio'),
  ('T-14200', 'topografia', 'Músculo da parede abdominal'),
  ('T-14240', 'topografia', 'Cremáster'),
  ('T-14250', 'topografia', 'Músculo transverso abdominal'),
  ('T-14330', 'topografia', 'Esfíncter anal'),
  ('T-14331', 'topografia', 'Músculo do esfíncter anal interno'),
  ('T-14332', 'topografia', 'Músculo do esfíncter anal externo'),
  ('T-14430', 'topografia', 'Músculo glúteo maior'),
  ('T-14440', 'topografia', 'Músculo glúteo médio'),
  ('T-14450', 'topografia', 'Músculo glúteo menor'),
  ('T-14550', 'topografia', 'Músculo quadríceps femural'),
  ('T-14560', 'topografia', 'Músculo reto femural'),
  ('T-14570', 'topografia', 'Músculo vasto-lateral'),
  ('T-14580', 'topografia', 'Músculo vasto medial'),
  ('T-14620', 'topografia', 'Músculo vasto intermédio'),
  ('T-14700', 'topografia', 'Músculo da perna'),
  ('T-14720', 'topografia', 'Músculo tríceps sural'),
  ('T-14730', 'topografia', 'Músculo gastrocnêmio'),
  ('T-14770', 'topografia', 'Músculo tibial posterior'),
  ('T-16000', 'topografia', 'Bursa'),
  ('T-17010', 'topografia', 'Tendão'),
  ('T-17040', 'topografia', 'Inserção tendinosa'),
  ('T-17050', 'topografia', 'Bainha tendinosa'),
  ('T-17070', 'topografia', 'Bainha teno-sinovial'),
  ('T-17350', 'topografia', 'Tendão do músculo extensor do carpo radial'),
  ('T-17390', 'topografia', 'Tendão do músculo extensor do carpo ulnar'),
  ('T-17440', 'topografia', 'Tendão de músculo flexor'),
  ('T-17620', 'topografia', 'Tendão patelar'),
  ('T-17860', 'topografia', 'Tendão de aquiles'),
  ('T-18010', 'topografia', 'Ligamento'),
  ('T-18020', 'topografia', 'Ligamento amarelo'),
  ('T-18150', 'topografia', 'Ligamento da articulação sacro-ilíaca'),
  ('T-18220', 'topografia', 'Ligamento da articulação esterno-clavicular'),
  ('T-18230', 'topografia', 'Ligamento da articulação acrômio-clavicular'),
  ('T-18250', 'topografia', 'Ligamento inguinal'),
  ('T-18290', 'topografia', 'Ligamento da articulação sacro-ilíaca e sínfise púbica'),
  ('T-18310', 'topografia', 'Ligamento da articulação do ombro'),
  ('T-18330', 'topografia', 'Ligamento da articulação rádio-ulnar'),
  ('T-18340', 'topografia', 'Ligamento da articulação rádio-carpal'),
  ('T-18343', 'topografia', 'Ligamento ulno-carpal palmar'),
  ('T-18360', 'topografia', 'Ligamento da articulação carpo-metacarpo'),
  ('T-18380', 'topografia', 'Ligamento da articulação inter-falangeana da mão'),
  ('T-18427', 'topografia', 'Ligamento patelar'),
  ('T-18550', 'topografia', 'Ligamento da articulação tarso-metatarso'),
  ('T-18570', 'topografia', 'Ligamento lateral da articulação do tornozelo'),
  ('T-18600', 'topografia', 'Fáscia'),
  ('T-18610', 'topografia', 'Aponeurose'),
  ('T-18682', 'topografia', 'Região pré-traqueal'),
  ('T-18840', 'topografia', 'Aponeurose palmar'),
  ('T-18845', 'topografia', 'Fáscia palmar'),
  ('T-18950', 'topografia', 'Fascia e espaço facial do pé do dedo do pé, soe'),
  ('T-18951', 'topografia', 'Aponeurose plantar'),
  ('T-18960', 'topografia', 'Fascia diafragmática uro-genital'),
  ('T-18980', 'topografia', 'Fáscia do cremáster'),
  ('T-1X000', 'topografia', 'Partes moles'),
  ('T-1X005', 'topografia', 'Partes moles e outros tecidos conjuntivos'),
  ('T-1X010', 'topografia', 'Produto de linfadenectomia'),
  ('T-1X200', 'topografia', 'Tecido conjuntivo'),
  ('T-1X300', 'topografia', 'Músculo liso'),
  ('T-1X510', 'topografia', 'Periósteo'),
  ('T-1X520', 'topografia', 'Osso'),
  ('T-1X545', 'topografia', 'Tecido osteóide'),
  ('T-1X553', 'topografia', 'Cartilagem epifisária'),
  ('T-1X570', 'topografia', 'Diáfise'),
  ('T-1X591', 'topografia', 'Sinostose'),
  ('T-1X700', 'topografia', 'Cartilagem'),
  ('T-1X705', 'topografia', 'Pericôndrio'),
  ('T-20200', 'topografia', 'Laringe, traquéia, brônquios e pulmões'),
  ('T-20400', 'topografia', 'Via aérea'),
  ('T-21000', 'topografia', 'Nariz'),
  ('T-21010', 'topografia', 'Mucosa nasal'),
  ('T-21050', 'topografia', 'Glândulas olfatórias'),
  ('T-21200', 'topografia', 'Cartilagem nasal'),
  ('T-21230', 'topografia', 'Cartilagem do septo nasal'),
  ('T-21320', 'topografia', 'Nariz, vestíbulo '),
  ('T-21330', 'topografia', 'Cavidade nasal direita'),
  ('T-21360', 'topografia', 'Corneto nasal'),
  ('T-21370', 'topografia', 'Corneto nasal inferior'),
  ('T-21380', 'topografia', 'Corneto nasal médio'),
  ('T-21390', 'topografia', 'Corneto nasal superior'),
  ('T-22010', 'topografia', 'Mucosa do trato respiratório superior'),
  ('T-22100', 'topografia', 'Antro maxilar'),
  ('T-22110', 'topografia', 'Seio maxilar direito'),
  ('T-22120', 'topografia', 'Seio maxilar esquerdo'),
  ('T-22130', 'topografia', 'Mucosa do seio maxilar'),
  ('T-22200', 'topografia', 'Seio frontal'),
  ('T-22300', 'topografia', 'Esfenóide'),
  ('T-22400', 'topografia', 'Seio esfenoidal'),
  ('T-23000', 'topografia', 'Cavidades nasal e sinusal'),
  ('T-23010', 'topografia', 'Mucosa nasofaríngea'),
  ('T-24000', 'topografia', 'Epiglote e laringe'),
  ('T-24010', 'topografia', 'Epiglote'),
  ('T-24030', 'topografia', 'Cartilagem epiglótica'),
  ('T-24100', 'topografia', 'Laringe'),
  ('T-24110', 'topografia', 'Mucosa da laringe'),
  ('T-24150', 'topografia', 'Cartilagem laríngea'),
  ('T-24160', 'topografia', 'Cartilagem tireóide'),
  ('T-24162', 'topografia', 'Nódulo'),
  ('T-24170', 'topografia', 'Cartilagem cricóide'),
  ('T-24187', 'topografia', 'Cartilagem aritenóide, processo vocal'),
  ('T-24400', 'topografia', 'Material citológico de cordas vocais'),
  ('T-24410', 'topografia', 'Ampliação da margem da prega vocal direita'),
  ('T-24420', 'topografia', 'Margem da prega vocal esquerda'),
  ('T-24440', 'topografia', 'Glote'),
  ('T-24450', 'topografia', 'Subglote'),
  ('T-24470', 'topografia', 'Comissura anterior'),
  ('T-24920', 'topografia', 'Laringe e faringe'),
  ('T-25000', 'topografia', 'Traquéia'),
  ('T-25010', 'topografia', 'Mucosa traqueal'),
  ('T-25100', 'topografia', 'Cartilagem traqueal'),
  ('T-26000', 'topografia', 'Brônquio'),
  ('T-26010', 'topografia', 'Mucosa brônquica'),
  ('T-26020', 'topografia', 'Brônquio, submucosa'),
  ('T-26030', 'topografia', 'Brônquio, glândula mucosa'),
  ('T-26040', 'topografia', 'Cartilagem brônquica'),
  ('T-26970', 'topografia', 'Brônquio e alvéolo'),
  ('T-28000', 'topografia', 'Material citológico do pulmão'),
  ('T-28010', 'topografia', 'Alvéolo pulmonar'),
  ('T-28012', 'topografia', 'Saco alveolar'),
  ('T-28014', 'topografia', 'Ducto alveolar'),
  ('T-28030', 'topografia', 'Parede alveolar'),
  ('T-28100', 'topografia', 'Pulmão direito'),
  ('T-28110', 'topografia', 'Pulmão direito, ápice'),
  ('T-28120', 'topografia', 'Pulmão direito, base'),
  ('T-28130', 'topografia', 'Pulmão direito, hilo'),
  ('T-28140', 'topografia', 'Pulmão direito, fissura interlobar oblíqua'),
  ('T-28150', 'topografia', 'Pulmão direito, fissura interlobar horizontal'),
  ('T-28200', 'topografia', 'Pulmão (direito, lobo superior)'),
  ('T-28300', 'topografia', 'Pulmão (esquerdo, lobo inferior)'),
  ('T-28500', 'topografia', 'Lobo superior de pulmão esquerdo'),
  ('T-28510', 'topografia', 'Pulmão esquerdo, ápice'),
  ('T-28520', 'topografia', 'Pulmão esquerdo, base'),
  ('T-28530', 'topografia', 'Pulmão esquerdo, hilo'),
  ('T-28540', 'topografia', 'Pulmão esquerdo, fissura interlobar oblíqua'),
  ('T-28550', 'topografia', 'Pulmão esquerdo, área cardíaca'),
  ('T-28610', 'topografia', 'Pulmão esquerdo, língula'),
  ('T-28780', 'topografia', 'Tecido intersticial pulmonar'),
  ('T-28900', 'topografia', 'Pulmão e pleura'),
  ('T-29000', 'topografia', 'Pleura'),
  ('T-29030', 'topografia', 'Pleura visceral'),
  ('T-29040', 'topografia', 'Pleura parietal'),
  ('T-29900', 'topografia', 'Pleura parietal e visceral'),
  ('T-29910', 'topografia', 'Pleura e pericárdio'),
  ('T-29930', 'topografia', 'Pleura e diafragma'),
  ('T-29950', 'topografia', 'Pleura e parede torácica'),
  ('T-2X110', 'topografia', 'Material citológico de mucosa nasal'),
  ('T-2X120', 'topografia', 'Cavidade nasal'),
  ('T-2X320', 'topografia', 'Cavidade nasofaringea'),
  ('T-31010', 'topografia', 'Pericárdio visceral'),
  ('T-31020', 'topografia', 'Pericárdio parietal'),
  ('T-31040', 'topografia', 'Gordura pericárdica'),
  ('T-31300', 'topografia', 'Pericárdio, seio transverso'),
  ('T-31900', 'topografia', 'Pericárdio'),
  ('T-31910', 'topografia', 'Pericárdio mediastinal'),
  ('T-32000', 'topografia', 'Coração'),
  ('T-32100', 'topografia', 'Átrio'),
  ('T-32120', 'topografia', 'Septo inter-atrial'),
  ('T-32200', 'topografia', 'Átrio direito'),
  ('T-32300', 'topografia', 'Átrio esquerdo'),
  ('T-32455', 'topografia', 'Sulco inter-ventricular posterior'),
  ('T-33010', 'topografia', 'Miocárdio'),
  ('T-33310', 'topografia', 'Coração, músculos papilares do ventrículo direito'),
  ('T-33400', 'topografia', 'Miocárdio do ventrículo esquerdo'),
  ('T-33410', 'topografia', 'Coração, músculos papilares do ventrículo esquerdo'),
  ('T-34000', 'topografia', 'Endocárdio'),
  ('T-35000', 'topografia', 'Valva cardíaca'),
  ('T-35090', 'topografia', 'Valvas cardíacas, todas'),
  ('T-38000', 'topografia', 'Valva mitral'),
  ('T-38410', 'topografia', 'Valva mitral, comissura anterior'),
  ('T-39000', 'topografia', 'Valva aórtica'),
  ('T-3X000', 'topografia', 'Líquido pericárdico'),
  ('T-3X110', 'topografia', 'Material citológico pericárdico'),
  ('T-3X200', 'topografia', 'Cavidade pericárdica'),
  ('T-40000', 'topografia', 'Vaso sanguíneo'),
  ('T-40010', 'topografia', 'Arteríola'),
  ('T-41000', 'topografia', 'Artéria'),
  ('T-42000', 'topografia', 'Aorta'),
  ('T-42050', 'topografia', 'Tecido peri-aórtico'),
  ('T-42900', 'topografia', 'Aorta abdominal'),
  ('T-43000', 'topografia', 'Artéria coronária'),
  ('T-45000', 'topografia', 'Artéria temporal'),
  ('T-45010', 'topografia', 'Artéria carótida'),
  ('T-45170', 'topografia', 'Seio carotídeo'),
  ('T-45190', 'topografia', 'Seio carotídeo esquerdo'),
  ('T-45302', 'topografia', 'Artéria carótida interna esquerda'),
  ('T-46460', 'topografia', 'Artéria esplênica'),
  ('T-46500', 'topografia', 'Artéria mesentérica'),
  ('T-46600', 'topografia', 'Artéria renal'),
  ('T-46742', 'topografia', 'Artéria ilíaca interna esquerda'),
  ('T-47000', 'topografia', 'Artéria do membro inferior'),
  ('T-47300', 'topografia', 'Artéria radial'),
  ('T-47400', 'topografia', 'Artéria femural'),
  ('T-47500', 'topografia', 'Artéria poplítea'),
  ('T-47520', 'topografia', 'Artéria poplítea esquerda'),
  ('T-47600', 'topografia', 'Artéria tibial posterior'),
  ('T-47700', 'topografia', 'Artéria tibial anterior'),
  ('T-48000', 'topografia', 'Veia'),
  ('T-48126', 'topografia', 'Veias temporais profundas'),
  ('T-48150', 'topografia', 'Veia jugular'),
  ('T-48160', 'topografia', 'Veia jubular externa'),
  ('T-48170', 'topografia', 'Veia jugular interna'),
  ('T-48180', 'topografia', 'Veia vertebral'),
  ('T-48400', 'topografia', 'Túnica vaginal'),
  ('T-48620', 'topografia', 'Veia inominada'),
  ('T-48640', 'topografia', 'Veia pericárdica'),
  ('T-48641', 'topografia', 'Veias pericárdio-frênicas'),
  ('T-48700', 'topografia', 'Veia cava, porção abdominal'),
  ('T-48740', 'topografia', 'Veia renal'),
  ('T-48784', 'topografia', 'Plexo pampiniforme'),
  ('T-48860', 'topografia', 'Veia intestinal'),
  ('T-48942', 'topografia', 'Plexo hemorroidário'),
  ('T-48991', 'topografia', 'Veia peniana'),
  ('T-49080', 'topografia', 'Veia pélvica'),
  ('T-49240', 'topografia', 'Veia cefálica'),
  ('T-49530', 'topografia', 'Safena direita'),
  ('T-50000', 'topografia', 'Órgãos do aparelho digestivo'),
  ('T-50100', 'topografia', 'Trato gastrointestinal'),
  ('T-50130', 'topografia', 'Mucosa intestinal'),
  ('T-50140', 'topografia', 'Parede intestinal'),
  ('T-50500', 'topografia', 'Intestino'),
  ('T-51000', 'topografia', 'Boca'),
  ('T-51020', 'topografia', 'Assoalho da boca'),
  ('T-51030', 'topografia', 'Material citológico de mucosa oral'),
  ('T-51100', 'topografia', 'Palato'),
  ('T-51110', 'topografia', 'Palato duro'),
  ('T-51120', 'topografia', 'Palato mole'),
  ('T-51130', 'topografia', 'Úvula'),
  ('T-51140', 'topografia', 'Mucosa do palato'),
  ('T-51200', 'topografia', 'Soalho da boca'),
  ('T-51230', 'topografia', 'Carúncula sub-lingual'),
  ('T-52000', 'topografia', 'Lábio (soe)'),
  ('T-52001', 'topografia', 'Pele do sulco nasolabial direito'),
  ('T-52003', 'topografia', 'Comissura labial'),
  ('T-52100', 'topografia', 'Lábio superior'),
  ('T-52200', 'topografia', 'Lábio inferior'),
  ('T-52210', 'topografia', 'Mucosa do lábio inferior'),
  ('T-52240', 'topografia', 'Lábio inferior, junção cutâneo-mucosa'),
  ('T-52250', 'topografia', 'Mucosa do lábio'),
  ('T-52900', 'topografia', 'Lábio, cavidade oral e faringe'),
  ('T-53000', 'topografia', 'Língua'),
  ('T-53010', 'topografia', 'Mucosa lingual'),
  ('T-53130', 'topografia', 'Base da língua'),
  ('T-54010', 'topografia', 'Dente'),
  ('T-54040', 'topografia', 'Raiz do dente'),
  ('T-54530', 'topografia', 'Dente do ciso'),
  ('T-54570', 'topografia', 'Dente molar'),
  ('T-54910', 'topografia', 'Gengiva'),
  ('T-54970', 'topografia', 'Alvéolo dentário'),
  ('T-54990', 'topografia', 'Tecido peri-apical (dente)'),
  ('T-55000', 'topografia', 'Glândula salivar'),
  ('T-55050', 'topografia', 'Glândula salivar seromucosa'),
  ('T-55100', 'topografia', 'Glândula parótida'),
  ('T-55101', 'topografia', 'Parótida direita'),
  ('T-55107', 'topografia', 'Ácino da parótida'),
  ('T-55110', 'topografia', 'Glândula parótida direita'),
  ('T-55120', 'topografia', 'Glândula parótida esquerda'),
  ('T-55200', 'topografia', 'Glândula sublingual'),
  ('T-55300', 'topografia', 'Glândula submandibular direita'),
  ('T-56000', 'topografia', 'Fígado'),
  ('T-56010', 'topografia', 'Fígado (lobo direito)'),
  ('T-56020', 'topografia', 'Fígado (lobo esquerdo)'),
  ('T-56042', 'topografia', 'Fígado, lobo caudado'),
  ('T-56061', 'topografia', 'Cápsula do fígado'),
  ('T-56070', 'topografia', 'Espaço porta hepático'),
  ('T-56110', 'topografia', 'Ducto biliar intra-hepático'),
  ('T-56210', 'topografia', 'Região centrolobular do fígado'),
  ('t-56350', 'topografia', 'Linfonodos do ligamento hepatoduodenal'),
  ('T-56400', 'topografia', 'Região do hilo hepático'),
  ('T-56950', 'topografia', 'Fígado e vesícula biliar'),
  ('T-56960', 'topografia', 'Fígado e ducto biliar intra-hepático'),
  ('T-56980', 'topografia', 'Fígado e intestino'),
  ('T-57000', 'topografia', 'Vesícula biliar (soe)'),
  ('T-57010', 'topografia', 'Vesícula biliar, fundo'),
  ('T-57100', 'topografia', 'Vesícula biliar, mucosa'),
  ('T-57200', 'topografia', 'Vesícula biliar, camada muscular'),
  ('T-57300', 'topografia', 'Vesícula biliar, serosa'),
  ('T-57310', 'topografia', 'Vesícula biliar, subserosa'),
  ('T-57900', 'topografia', 'Vesícula biliar e intestino'),
  ('T-57910', 'topografia', 'Vesícula biliar e jejuno'),
  ('T-57920', 'topografia', 'Vesícula biliar e ducto biliar'),
  ('T-57930', 'topografia', 'Vesícula biliar e ducto biliar extra-hepático'),
  ('T-57940', 'topografia', 'Vesícula biliar e ducto biliar comum'),
  ('T-57960', 'topografia', 'Vesícula biliar, estômago e duodeno'),
  ('T-57970', 'topografia', 'Vesícula biliar e estômago'),
  ('T-58000', 'topografia', 'Ducto biliar extra-hepático'),
  ('T-58400', 'topografia', 'Ducto cístico'),
  ('T-58500', 'topografia', 'Ducto biliar comum'),
  ('T-58700', 'topografia', 'Ampola de vater'),
  ('T-58720', 'topografia', 'Colédoco'),
  ('t-59000', 'topografia', 'Corpo e cauda do pâncreas'),
  ('T-59090', 'topografia', 'Ácino pancreático'),
  ('T-59100', 'topografia', 'Cabeça do pâncreas'),
  ('T-59200', 'topografia', 'Corpo do pâncreas'),
  ('T-59300', 'topografia', 'Cauda do pâncreas'),
  ('T-59510', 'topografia', 'Tecido peri-pancreático'),
  ('T-59950', 'topografia', 'Ducto pancreático e ducto biliar'),
  ('T-5X100', 'topografia', 'Material citológico da boca'),
  ('T-60000', 'topografia', 'Faringe'),
  ('T-60110', 'topografia', 'Mucosa da faringe'),
  ('T-60240', 'topografia', 'Mucosa da orofaringe'),
  ('T-60300', 'topografia', 'Hipofaringe'),
  ('T-60320', 'topografia', 'Mucosa do seio piriforme'),
  ('T-61000', 'topografia', 'Tonsila palatina direita e tonsila faríngea'),
  ('T-61100', 'topografia', 'Tonsila palatina'),
  ('T-61110', 'topografia', 'Tonsila palatina direita'),
  ('T-61120', 'topografia', 'Tonsila palatina esquerda'),
  ('T-61130', 'topografia', 'Tonsilas palatinas'),
  ('T-61210', 'topografia', 'Mucosa amigdaliana'),
  ('T-61240', 'topografia', 'Fossa tonsilar'),
  ('T-61300', 'topografia', 'Tonsila faríngea'),
  ('T-62000', 'topografia', 'Esôfago (SOE)'),
  ('T-62010', 'topografia', 'Mucosa esofágica'),
  ('T-62050', 'topografia', 'Esôfago, muscular própria'),
  ('T-62110', 'topografia', 'Esôfago (terço proximal)'),
  ('T-62210', 'topografia', 'Esôfago (terço médio)'),
  ('T-62310', 'topografia', 'Esôfago (terço distal)'),
  ('T-62350', 'topografia', 'Junção esôfago-cárdia'),
  ('T-62910', 'topografia', 'Transição esôfago-gástrica'),
  ('T-62920', 'topografia', 'Anastomose esôfago-entérica'),
  ('T-63000', 'topografia', 'Estômago'),
  ('T-63010', 'topografia', 'Mucosa gástrica'),
  ('T-63120', 'topografia', 'Estômago, muscularis mucosae'),
  ('T-63210', 'topografia', 'Estômago, pequena curvatura'),
  ('T-63211', 'topografia', 'Incisura angular do estômago'),
  ('T-63220', 'topografia', 'Estômago, grande curvatura'),
  ('T-63230', 'topografia', 'Parede gástrica'),
  ('T-63240', 'topografia', 'Estômago, parede anterior'),
  ('T-63250', 'topografia', 'Estômago, parede posterior'),
  ('T-63500', 'topografia', 'Corpo gástrico'),
  ('T-63600', 'topografia', 'Antro gástrico'),
  ('T-63700', 'topografia', 'Piloro'),
  ('T-63850', 'topografia', 'Epíplon'),
  ('T-63860', 'topografia', 'Grande omento'),
  ('T-63870', 'topografia', 'Pequeno omento'),
  ('T-63910', 'topografia', 'Anastomose gastroentérica'),
  ('T-63930', 'topografia', 'Estômago e duodeno'),
  ('T-63940', 'topografia', 'Antro gástrico e duodeno'),
  ('T-63950', 'topografia', 'Estômago e cólon'),
  ('T-64000', 'topografia', 'Intestino delgado'),
  ('T-64010', 'topografia', 'Mucosa do intestino delgado'),
  ('T-64040', 'topografia', 'Vilo intestinal'),
  ('T-64190', 'topografia', 'Face contra-mesenterial do intestino delgado'),
  ('T-64200', 'topografia', 'Mesentério'),
  ('T-64210', 'topografia', 'Mesentério do intestino delgado'),
  ('T-64300', 'topografia', 'Duodeno (soe)'),
  ('T-64310', 'topografia', 'Mucosa duodenal'),
  ('T-64390', 'topografia', 'Papila duodenal'),
  ('T-64910', 'topografia', 'Intestino delgado e cólon'),
  ('T-64930', 'topografia', 'Duodeno e ducto biliar comum'),
  ('T-65100', 'topografia', 'Jejuno'),
  ('T-65110', 'topografia', 'Mucosa jejunal'),
  ('T-65116', 'topografia', 'Jejuno, lâmina própria'),
  ('T-65120', 'topografia', 'Jejuno, submucosa'),
  ('T-65190', 'topografia', 'Face contra-mesenterial do jejuno'),
  ('T-65200', 'topografia', 'Íleo'),
  ('T-65210', 'topografia', 'Mucosa ileal'),
  ('T-65290', 'topografia', 'Face contra-mesenterial do íleo'),
  ('T-65400', 'topografia', 'Jejuno, mesentério'),
  ('T-65520', 'topografia', 'Íleo (terminal)'),
  ('T-65600', 'topografia', 'Divertículo de meckel'),
  ('T-65900', 'topografia', 'Anastomose íleo-cólica'),
  ('T-65905', 'topografia', 'Jejuno-ileal'),
  ('T-65960', 'topografia', 'Íleo e ceco'),
  ('T-66000', 'topografia', 'Apêndice cecal'),
  ('T-67000', 'topografia', 'Cólon (soe)'),
  ('T-67010', 'topografia', 'Mucosa cecal'),
  ('T-67015', 'topografia', 'Cólon, epitélio'),
  ('T-67016', 'topografia', 'Lâmina própria cólica'),
  ('T-67040', 'topografia', 'Cólon, camada muscular própria'),
  ('T-67041', 'topografia', 'Cólon, camada muscular própria, camada longitudinal'),
  ('T-67060', 'topografia', 'Apêndice epiplóico'),
  ('T-67090', 'topografia', 'Cólon, serosa'),
  ('T-67100', 'topografia', 'Base do ceco'),
  ('T-67200', 'topografia', 'Cólon (ascendente)'),
  ('T-67300', 'topografia', 'Cólon ângulo hepático'),
  ('T-67400', 'topografia', 'Cólon (transverso)'),
  ('T-67500', 'topografia', 'Cólon ângulo esplênico'),
  ('T-67600', 'topografia', 'Cólon (descendente)'),
  ('T-67700', 'topografia', 'Cólon (sigmoide)'),
  ('T-67800', 'topografia', 'Mesoapêndice'),
  ('T-67860', 'topografia', 'Tecido peri-cólico'),
  ('T-67920', 'topografia', 'Anastomose colorretal (SOE)'),
  ('T-67965', 'topografia', 'Cólon (direito)'),
  ('T-67990', 'topografia', 'Cólon descendente e sigmóide'),
  ('T-67995', 'topografia', 'Cólon (esquerdo)'),
  ('T-68000', 'topografia', 'Reto (soe)'),
  ('T-68001', 'topografia', 'Flexura sacral do reto'),
  ('T-68010', 'topografia', 'Mucosa retal'),
  ('T-68100', 'topografia', 'Ampola retal'),
  ('T-68200', 'topografia', 'Junção retossigmoideana (SOE)'),
  ('T-68930', 'topografia', 'Reto-vesical'),
  ('T-68940', 'topografia', 'Região retro-retal'),
  ('T-68950', 'topografia', 'Reto e cólon sigmoide'),
  ('T-69000', 'topografia', 'Anastomose (SOE)'),
  ('T-69010', 'topografia', 'Canal anal (soe)'),
  ('T-69050', 'topografia', 'Transição ano-retal'),
  ('T-69110', 'topografia', 'Mucosa anal'),
  ('T-69120', 'topografia', 'Seio piriforme'),
  ('T-69121', 'topografia', 'Reto, linha alba'),
  ('T-69140', 'topografia', 'Muscular própria do canal anal'),
  ('T-69200', 'topografia', 'Tecido peri-anal'),
  ('T-69900', 'topografia', 'Reto e canal anal'),
  ('T-6X300', 'topografia', 'Material citológico de suco gástrico'),
  ('T-6X420', 'topografia', 'Luz intestinal'),
  ('T-6X620', 'topografia', 'Jejuno, luz'),
  ('T-6X800', 'topografia', 'Mucosa cólica'),
  ('T-6X810', 'topografia', 'Cólon, material, citológico'),
  ('T-6X930', 'topografia', 'Líquido peritoneal'),
  ('T-6X940', 'topografia', 'Líquido ascítico'),
  ('T-70000', 'topografia', 'Sistema uro-genital'),
  ('T-70100', 'topografia', 'Mucosa da bexiga urinária'),
  ('T-70210', 'topografia', 'Genitália externa'),
  ('T-70310', 'topografia', 'Genitália externa masculina'),
  ('T-71000', 'topografia', 'Rim'),
  ('T-71010', 'topografia', 'Rim (direito)'),
  ('T-71020', 'topografia', 'Rim esquerdo'),
  ('T-71030', 'topografia', 'Cápsula renal'),
  ('T-71050', 'topografia', 'Córtex renal'),
  ('T-71160', 'topografia', 'Tecido peri-renal'),
  ('T-71240', 'topografia', 'Endotélio do capilar glomerular'),
  ('T-71300', 'topografia', 'Túbulo renal'),
  ('T-71500', 'topografia', 'Rim transplantado'),
  ('T-72000', 'topografia', 'Cálice renal'),
  ('T-72010', 'topografia', 'Pelve renal direita'),
  ('T-72020', 'topografia', 'Pelve renal esquerda'),
  ('T-72050', 'topografia', 'Pelve renal, camada muscular'),
  ('T-72800', 'topografia', 'Pelves renais'),
  ('T-73000', 'topografia', 'Parede pielo-ureteral'),
  ('T-73002', 'topografia', 'Ureter, porção pélvica'),
  ('T-73003', 'topografia', 'Junção uretero-piélica'),
  ('T-73070', 'topografia', 'Tecido peri-ureteral'),
  ('T-73910', 'topografia', 'Ureter e pelve'),
  ('T-73930', 'topografia', 'Ureter e cólon sigmóide'),
  ('T-73970', 'topografia', 'Ureter e cólon'),
  ('T-74000', 'topografia', 'Bexiga'),
  ('T-74060', 'topografia', 'Parede da bexiga urinária'),
  ('T-74061', 'topografia', 'Bexiga, parede anterior'),
  ('T-74062', 'topografia', 'Bexiga, parede posterior'),
  ('T-74063', 'topografia', 'Bexiga, parede lateral'),
  ('T-74064', 'topografia', 'Bexiga, parede lateral direita'),
  ('T-74065', 'topografia', 'Bexiga, parede lateral esquerda'),
  ('T-74100', 'topografia', 'Bexiga, fundo'),
  ('T-74120', 'topografia', 'Úraco'),
  ('T-74321', 'topografia', 'Meato ureteral direito'),
  ('T-74322', 'topografia', 'Meato ureteral esquerdo'),
  ('T-74420', 'topografia', 'Bexiga, esfíncter muscular'),
  ('T-74950', 'topografia', 'Bexiga urinária e cólon'),
  ('T-74970', 'topografia', 'Bexiga urinária e cólon sigmóide'),
  ('T-75000', 'topografia', 'Uretra'),
  ('T-75020', 'topografia', 'Glândula uretral'),
  ('T-75110', 'topografia', 'Uretra, porção prostática'),
  ('T-75180', 'topografia', 'Meato uretral'),
  ('T-75210', 'topografia', 'Região peri-ureteral'),
  ('T-76000', 'topografia', 'Margem cirúrgica do corpo cavernoso'),
  ('T-76300', 'topografia', 'Glande peniana'),
  ('T-76330', 'topografia', 'Pele do prepúcio'),
  ('T-76331', 'topografia', 'Frênulo do pênis'),
  ('T-77100', 'topografia', 'Próstata (lobo direito)'),
  ('T-77110', 'topografia', 'Cápsula prostática'),
  ('T-77120', 'topografia', 'Região endo-prostática esquerda'),
  ('T-77130', 'topografia', 'Próstata, tecido glandular'),
  ('T-77200', 'topografia', 'Próstata, lobo mediano'),
  ('T-77300', 'topografia', 'Próstata, lobos e cápsula'),
  ('T-77500', 'topografia', 'Vesícula seminal (soe)'),
  ('T-77510', 'topografia', 'Vesícula seminal (direita)'),
  ('T-77520', 'topografia', 'Vesícula seminal (esquerda)'),
  ('T-77900', 'topografia', 'Próstata e bexiga urinária'),
  ('T-78000', 'topografia', 'Testículo'),
  ('T-78010', 'topografia', 'Testículo direito'),
  ('T-78020', 'topografia', 'Testículo esquerdo'),
  ('T-78300', 'topografia', 'Região para-cervical'),
  ('T-78800', 'topografia', 'Testículos direito e esquerdo'),
  ('T-78900', 'topografia', 'Testículo e escroto'),
  ('T-79000', 'topografia', 'Epidídimo, cordão espermático e escroto direitos'),
  ('T-79100', 'topografia', 'Epidídimo'),
  ('T-79170', 'topografia', 'Ducto deferente (soe)'),
  ('T-79300', 'topografia', 'Cordão espermático'),
  ('T-79400', 'topografia', 'Bolsa escrotal'),
  ('T-79820', 'topografia', 'Epidídimo direito'),
  ('T-7X100', 'topografia', 'Urina'),
  ('T-7X410', 'topografia', 'Material citológico de urina'),
  ('T-80100', 'topografia', 'Vulva (soe)'),
  ('T-80130', 'topografia', 'Mucosa da vulva'),
  ('T-80220', 'topografia', 'Vulva (grande lábio, soe)'),
  ('T-80240', 'topografia', 'Grande lábio, comissura posterior'),
  ('T-80250', 'topografia', 'Fúrcula esternal'),
  ('T-80300', 'topografia', 'Lábio menor'),
  ('T-80400', 'topografia', 'Clitóris'),
  ('T-80500', 'topografia', 'Glândula de bartholin'),
  ('T-81000', 'topografia', 'Vagina (soe)'),
  ('T-81010', 'topografia', 'Mucosa vaginal'),
  ('T-81150', 'topografia', 'Vagina, parede anterior'),
  ('T-81160', 'topografia', 'Vagina, parede posterior'),
  ('T-81400', 'topografia', 'Hímen'),
  ('T-81410', 'topografia', 'Carúncula himenal'),
  ('T-82000', 'topografia', 'Útero (corpo)'),
  ('T-82030', 'topografia', 'Útero, superfície intestinal'),
  ('T-82050', 'topografia', 'Útero gravídico'),
  ('T-82100', 'topografia', 'Corpo uterino (soe)'),
  ('T-82200', 'topografia', 'Útero, fundo'),
  ('T-82300', 'topografia', 'Istmo uterino'),
  ('T-82500', 'topografia', 'Serosa uterina'),
  ('T-82600', 'topografia', 'Ligamento uterino'),
  ('T-82610', 'topografia', 'Ligamento útero-sacral'),
  ('T-82619', 'topografia', 'Ligamento útero-sacral esquerdo e parede do reto'),
  ('T-82920', 'topografia', 'Útero e anexos bilaterais'),
  ('T-82921', 'topografia', 'Útero e anexos direitos'),
  ('T-82922', 'topografia', 'Útero e anexos esquerdos'),
  ('T-83000', 'topografia', 'Colo uterino (soe)'),
  ('T-83010', 'topografia', 'Mucosa cervical uterina'),
  ('T-83150', 'topografia', 'Junção escamo-colunar do colo uterino'),
  ('T-83210', 'topografia', 'Lábio anterior do colo uterino'),
  ('T-83220', 'topografia', 'Lábio posterior do colo uterino'),
  ('T-83300', 'topografia', 'Endocérvice'),
  ('t-83400', 'topografia', 'Esôfago distal e estômago'),
  ('T-84000', 'topografia', 'Endométrio (soe)'),
  ('T-85000', 'topografia', 'Miométrio'),
  ('T-85010', 'topografia', 'Miométrio, porção submucosa'),
  ('T-85020', 'topografia', 'Porção intramural do miométrio'),
  ('T-85030', 'topografia', 'Miométrio, porção subserosa'),
  ('T-86000', 'topografia', 'Linfonodos pélvicos à direita'),
  ('T-86100', 'topografia', 'Tuba uterina (soe)'),
  ('T-86110', 'topografia', 'Tuba uterina (direita)'),
  ('T-86120', 'topografia', 'Tuba uterina (esquerda)'),
  ('T-86130', 'topografia', 'Tubas uterinas'),
  ('T-86220', 'topografia', 'Fímbria de tuba uterina'),
  ('T-86300', 'topografia', 'Ligamento largo'),
  ('T-86400', 'topografia', 'Paramétrio'),
  ('T-86700', 'topografia', 'Ligamento redondo'),
  ('T-86920', 'topografia', 'Anexos uterinos (soe)'),
  ('T-86921', 'topografia', 'Anexos uterinos (direitos)'),
  ('T-86922', 'topografia', 'Anexos uterinos (esquerdos)'),
  ('T-86970', 'topografia', 'Tubas uterinas e ovários'),
  ('T-87000', 'topografia', 'Ovário'),
  ('T-87010', 'topografia', 'Ovário (direito)'),
  ('T-87020', 'topografia', 'Ovário esquerdo'),
  ('T-87200', 'topografia', 'Cápsula ovariana'),
  ('T-87300', 'topografia', 'Ovário, córtex'),
  ('T-87420', 'topografia', 'Mesovário'),
  ('T-87670', 'topografia', 'Corpo lúteo do ovário'),
  ('T-87800', 'topografia', 'Ovários, ambos'),
  ('T-88100', 'topografia', 'Placenta, cordão e membranas'),
  ('T-88110', 'topografia', 'Fundo de saco vaginal'),
  ('T-88120', 'topografia', 'Trofoblasto sincicial'),
  ('T-88220', 'topografia', 'Vilosidades coriônicas'),
  ('T-88230', 'topografia', 'Vilosidades coriônica imaturas'),
  ('T-88300', 'topografia', 'Membrana amniótica'),
  ('T-88400', 'topografia', 'Saco vitelínico'),
  ('T-88450', 'topografia', 'Ducto onfalo-mesentérico'),
  ('T-88800', 'topografia', 'Cordão umbilical'),
  ('T-88810', 'topografia', 'Artéria umbilical'),
  ('T-89000', 'topografia', 'Embrião'),
  ('T-89160', 'topografia', 'Diencéfalo fetal'),
  ('T-89310', 'topografia', 'Notocorda'),
  ('T-89430', 'topografia', 'Cloaca '),
  ('T-89440', 'topografia', 'Membrana cloacal'),
  ('T-89695', 'topografia', 'Veia umbilical'),
  ('T-8X110', 'topografia', 'Material citológico vulvar'),
  ('T-8X330', 'topografia', 'Cérvico-vaginal'),
  ('T-8X340', 'topografia', 'Canal cervical'),
  ('T-8X430', 'topografia', 'Material citológico endometrial'),
  ('T-8X440', 'topografia', 'Cavidade uterina (soe)'),
  ('T-91000', 'topografia', 'Hipófise'),
  ('T-91120', 'topografia', 'Pituitária, célula acidófila'),
  ('T-92000', 'topografia', 'Glândula pineal'),
  ('T-93000', 'topografia', 'Glândula supra-renal'),
  ('T-93010', 'topografia', 'Glândula adrenal direita'),
  ('T-93020', 'topografia', 'Glândula adrenal esquerda'),
  ('T-93100', 'topografia', 'Adrenal direita'),
  ('T-93200', 'topografia', 'Medula adrenal'),
  ('T-93300', 'topografia', 'Tecido peri-glândula adrenal'),
  ('T-94000', 'topografia', 'Corpo carotídeo'),
  ('T-95000', 'topografia', 'Paraganglion'),
  ('T-95200', 'topografia', 'Glomus coccígeo'),
  ('T-95500', 'topografia', 'Paraganglion de extremidade'),
  ('T-96000', 'topografia', 'Tireoide (soe)'),
  ('T-96030', 'topografia', 'Folículo tireoidiano'),
  ('T-96100', 'topografia', 'Pulmão (direito, lobo inferior)'),
  ('T-96200', 'topografia', 'Lobo direito da tireóide, nodulectomia'),
  ('T-96300', 'topografia', 'Istmo da tireoide'),
  ('T-96400', 'topografia', 'Lobo piramidal da glândula tireóide'),
  ('T-96500', 'topografia', 'Ducto tireoglosso'),
  ('T-97000', 'topografia', 'Glândula paratireóide'),
  ('T-97800', 'topografia', 'Glândulas paratireoide, todas'),
  ('T-98000', 'topografia', 'Timo'),
  ('T-9X100', 'topografia', 'Material citológico de tireóide'),
  ('T-X0460', 'topografia', 'Microglia'),
  ('T-X0500', 'topografia', 'Nervo periférico'),
  ('T-X0710', 'topografia', 'Corpúsculo de pacini'),
  ('T-X0960', 'topografia', 'Medula espinhal e meninges'),
  ('T-X0980', 'topografia', 'Ponte e cerebelo'),
  ('T-X1000', 'topografia', 'Líquido céfalo-raquidiano'),
  ('T-X1010', 'topografia', 'Líquido cerebro-espinhal, material citológico'),
  ('T-X1101', 'topografia', 'Meninge'),
  ('T-X1110', 'topografia', 'Espaço subdural'),
  ('T-X1130', 'topografia', 'Dura-máter'),
  ('T-X1250', 'topografia', 'Seio cavernoso'),
  ('T-X1280', 'topografia', 'Espaço epidural'),
  ('T-X1321', 'topografia', 'Aracnóide'),
  ('T-X1380', 'topografia', 'Pia máter'),
  ('T-X1500', 'topografia', 'Espaço subaracnóide'),
  ('T-X1520', 'topografia', 'Cisterna magna'),
  ('T-X1550', 'topografia', 'Cisterna superior'),
  ('T-X1570', 'topografia', 'Cisterna quiasmática'),
  ('T-X1600', 'topografia', 'Cérebro, ventrículo lateral direito'),
  ('T-X1730', 'topografia', 'Foramen de monro'),
  ('T-X1740', 'topografia', 'Terceiro ventrículo'),
  ('T-X1900', 'topografia', 'Plexo coróide'),
  ('T-X1910', 'topografia', 'Ventrículo lateral, plexo coróide'),
  ('T-X1920', 'topografia', 'Ventrículo lateral, coróide'),
  ('T-X1930', 'topografia', 'Plexo coróide do terceiro ventrículo'),
  ('T-X1940', 'topografia', 'Coróide do terceiro ventrículo'),
  ('T-X1950', 'topografia', 'Plexo coróide do quarto ventrículo'),
  ('T-X1960', 'topografia', 'Coróide do quarto ventrículo'),
  ('T-X2000', 'topografia', 'Cérebro'),
  ('T-X2020', 'topografia', 'Córtex cerebelar'),
  ('T-X2050', 'topografia', 'Tronco cerebral'),
  ('T-X2202', 'topografia', 'Lobo frontal direito do cérebro'),
  ('T-X2210', 'topografia', 'Cérebro, córtex do lobo frontal'),
  ('T-X2262', 'topografia', 'Cérebro, córtex motor'),
  ('T-X2263', 'topografia', 'Cérebro, córtex pré-motor'),
  ('T-X2293', 'topografia', 'Cérebro, lobos frontal e parietal'),
  ('T-X2294', 'topografia', 'Cérebro, lobos frontal e parietal direitos'),
  ('T-X2295', 'topografia', 'Cérebro, lobos frontal e parietal esquerdos'),
  ('T-X2310', 'topografia', 'Cérebro, córtex do lobo parietal'),
  ('T-X2341', 'topografia', 'Sulco intra-parietal'),
  ('T-X2410', 'topografia', 'Cérebro, córtex do lobo occipital'),
  ('T-X2430', 'topografia', 'Córtex visual'),
  ('T-X2502', 'topografia', 'Cérebro, lobo temporal esquerdo'),
  ('T-X2510', 'topografia', 'Cérebro, córtex do lobo temporal'),
  ('T-X2610', 'topografia', 'Ínsula'),
  ('T-X2620', 'topografia', 'Ínsula, córtex'),
  ('T-X2630', 'topografia', 'Substância branca da ínsula'),
  ('T-X2650', 'topografia', 'Ínsula anterior'),
  ('T-X2790', 'topografia', 'Comissura posterior'),
  ('T-X2971', 'topografia', 'Comissura hipocampal'),
  ('T-X3010', 'topografia', 'Cérebro, glânglios da base'),
  ('T-X3200', 'topografia', 'Núcleo caudado'),
  ('T-X4010', 'topografia', 'Tálamo'),
  ('T-X4890', 'topografia', 'Fibras diencefálicas peri-ventriculares'),
  ('T-X4982', 'topografia', 'Nervo tibial posterior'),
  ('T-X5123', 'topografia', 'Núcleo pedúnculo-pontino'),
  ('T-X5330', 'topografia', 'Trato tecto-bulbar'),
  ('T-X5640', 'topografia', 'Ângulo cerebelo-pontino'),
  ('T-X6000', 'topografia', 'Cerebelo'),
  ('T-X6100', 'topografia', 'Lobo cerebelar anterior'),
  ('T-X6350', 'topografia', 'Lobo digástrico'),
  ('T-X7410', 'topografia', 'Canal espinal'),
  ('T-X7580', 'topografia', 'Gânglio espinhal'),
  ('T-X7900', 'topografia', 'Cauda equina'),
  ('T-X8020', 'topografia', 'Nervo olfatório'),
  ('T-X8040', 'topografia', 'Nervo óptico'),
  ('T-X8050', 'topografia', 'Quiasma óptico'),
  ('T-X8070', 'topografia', 'Terceiro nervo cranial'),
  ('T-X8130', 'topografia', 'Sexto nervo cranial'),
  ('T-X8150', 'topografia', 'Nervo trigêmio'),
  ('T-X8210', 'topografia', 'Nervo oftálmico'),
  ('T-X8320', 'topografia', 'Nervo infraorbital'),
  ('T-X8400', 'topografia', 'Nervo alveolar inferior'),
  ('T-X8500', 'topografia', 'Nervo acústico'),
  ('T-X8570', 'topografia', 'Nono nervo cranial'),
  ('T-X8580', 'topografia', 'Núcleo glossofaríngeo'),
  ('T-X8640', 'topografia', 'Décimo nervo craniano'),
  ('T-X8820', 'topografia', 'Décimo-segundo nervo craniano'),
  ('T-X9001', 'topografia', 'Nervo'),
  ('T-X9170', 'topografia', 'Nervo ulnar direito'),
  ('T-X9186', 'topografia', 'Nervo mediano direito'),
  ('T-X9201', 'topografia', 'Plexo braquial'),
  ('T-X9383', 'topografia', 'Nervo safeno'),
  ('T-X9440', 'topografia', 'Nervo ciático'),
  ('T-X9450', 'topografia', 'Nervo tibial'),
  ('T-X9470', 'topografia', 'Nervo sural'),
  ('T-X9640', 'topografia', 'Gânglio simpático'),
  ('T-X9712', 'topografia', 'Plexo carotídeo comum'),
  ('T-X9760', 'topografia', 'Cadeia simpática torácica'),
  ('T-X9792', 'topografia', 'Sistema nervoso simpático, porção lombar'),
  ('T-X9793', 'topografia', 'Sistema nervoso simpático lombar, ramo espinhal'),
  ('T-X9840', 'topografia', 'Plexo de auerbach'),
  ('T-X9860', 'topografia', 'Plexo pélvico'),
  ('T-XX000', 'topografia', 'Olho'),
  ('T-XX010', 'topografia', 'Olho direito'),
  ('T-XX020', 'topografia', 'Olho esquerdo'),
  ('T-XX110', 'topografia', 'Esclera'),
  ('T-XX130', 'topografia', 'Junção esclero-córnea'),
  ('T-XX200', 'topografia', 'Córnea'),
  ('T-XX310', 'topografia', 'Coróide'),
  ('T-XX312', 'topografia', 'Espaço peri-coroidal'),
  ('T-XX360', 'topografia', 'Coróide e retina'),
  ('T-XX500', 'topografia', 'Íris'),
  ('T-XX610', 'topografia', 'Retina'),
  ('T-XX810', 'topografia', 'Pálpebra'),
  ('T-XX812', 'topografia', 'Comissura palpebral'),
  ('T-XX821', 'topografia', 'Pálpebra superior direita'),
  ('T-XX822', 'topografia', 'Pálpebra superior esquerda'),
  ('T-XX831', 'topografia', 'Pálpebra direita'),
  ('T-XX832', 'topografia', 'Pálpebra inferior esquerda'),
  ('T-XX860', 'topografia', 'Conjuntiva'),
  ('T-XX862', 'topografia', 'Carúncula lacrimal'),
  ('T-XX868', 'topografia', 'Glândulas conjuntivais'),
  ('T-XX870', 'topografia', 'Conjuntiva palpebral'),
  ('T-XX880', 'topografia', 'Conjuntiva bulbar'),
  ('T-XX931', 'topografia', 'Ponto lacrimal'),
  ('T-XX932', 'topografia', 'Glândula lacrimal'),
  ('T-XX940', 'topografia', 'Saco lacrimal'),
  ('T-XX950', 'topografia', 'Canalículo lacrimal'),
  ('T-XX970', 'topografia', 'Lágrimas'),
  ('T-XX980', 'topografia', 'Olho e glândula lacrimal'),
  ('T-XX990', 'topografia', 'Conjuntiva e saco lacrimal')
ON CONFLICT (codigo) DO NOTHING;
